### ISSUE TITLE
Sorry,why i got the wrong predict pose ,when i used your pretrained model?

### ISSUE THREAD

**Issue by kevin860213** [zju3dv/clean-pvnet#1]
![Figure_1](https://user-images.githubusercontent.com/57515518/70909290-25ac3b80-2048-11ea-8939-14ec2fbb249c.png)
I got the image from your pretrained model. Do you have any ideas with this problem? thank you and your project

**Comment by pengsida** [comment]
The pretrained model should be put at `$ROOT/data/model/pvnet/cat/199.pth`.
And run `python run.py --type visualize --cfg_file configs/linemod.yaml model cat`.

**Comment by kevin860213** [comment]
sorry, i didn't create the folder of pvnet , i directly put the model into data.
thank you , it was sloved

**Comment by pengsida** [comment]
Enjoy this code!

**Comment by pengsida** [comment]
If possible, make more people to know this project.
Thank you!

**Comment by kevin860213** [comment]
OK, I will.
Thanks!

**Comment by jinglan0829** [comment]
I put the pretrained model at $ROOT/data/model/pvnet/cat/199.pth.
But I have error with :
Traceback (most recent call last):
  File "run.py", line 198, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 90, in run_visualize
    load_network(network, cfg.model_dir, resume=cfg.resume, epoch=cfg.test.epoch)
  File "/home/jinglan/clean-pvnet-master/lib/utils/net_utils.py", line 318, in load_network
    pretrained_model = torch.load(os.path.join(model_dir, '{}.pth'.format(pth)))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '	'.

**Comment by pengsida** [comment]
The pth file is broken.

**Comment by jinglan0829** [comment]
I'll check it. Thanks!
