### ISSUE TITLE
 Error in `python': free(): invalid pointer: 0x000055e1deea4028 *** Aborted (core dumped)

### ISSUE THREAD

**Issue by tiexuedanxin** [zju3dv/clean-pvnet#10]
sorry to bother you , when i run the command python run.py --type evaluate --cfg_file configs/linemod.yaml model cat test.icp True, i come across the following error " Error in `python': free(): invalid pointer: 0x000055e1deea4028 *** Aborted (core dumped)", and i find the "evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)" code cause the problem. Can you help me, very thanks.

**Comment by pengsida** [comment]
`test.icp True` causes this problem.
Ensure that your python is 3.7 and the labraries strictly admit the requirement.txt, especially `open3d-python==0.5.0.0`.

**Comment by tiexuedanxin** [comment]
@pengsida ,thank you, after i installed open3d-python==0.5.0.0. the before error disappear, but another error occured "Traceback (most recent call last):
  File "run.py", line 201, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 73, in run_evaluate
    evaluator = make_evaluator(cfg)
  File "/mnt/data/heyong/PycharmProjects/clean-pvnet-master/lib/evaluators/make_evaluator.py", line 25, in make_evaluator
    return _evaluator_factory(cfg)
  File "/mnt/data/heyong/PycharmProjects/clean-pvnet-master/lib/evaluators/make_evaluator.py", line 16, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "lib/evaluators/linemod/pvnet.py", line 34, in __init__
    self.icp_render = icp_utils.SynRenderer(cfg.cls_type) if cfg.test.icp else None
  File "/mnt/data/heyong/PycharmProjects/clean-pvnet-master/lib/utils/icp_utils.py", line 181, in __init__
    self.renderer
  File "/mnt/data/heyong/PycharmProjects/clean-pvnet-master/lib/utils/icp_utils.py", line 32, in decorator
    setattr(self, attribute, function(self))
  File "/mnt/data/heyong/PycharmProjects/clean-pvnet-master/lib/utils/icp_utils.py", line 188, in renderer
    return meshrenderer.Renderer([self.model_path],1,'.',1000)
  File "/mnt/data/heyong/PycharmProjects/clean-pvnet-master/lib/utils/meshrenderer/meshrenderer.py", line 26, in __init__
    GL_DEPTH_ATTACHMENT: gu.Renderbuffer(GL_DEPTH_COMPONENT32F, W, H) } )
  File "/mnt/data/heyong/PycharmProjects/clean-pvnet-master/lib/utils/meshrenderer/gl_utils/fbo.py", line 26, in __init__
    raise RuntimeError('Framebuffer not complete.')
RuntimeError: Framebuffer not complete."

**Comment by pengsida** [comment]
Ensure that your computer is not headless.

**Comment by pengsida** [comment]
Ensure that your python libraries are the same as those listed in the requirement.txt.

**Comment by tiexuedanxin** [comment]
I have tried my best to ensure compliance with the requirement.txt, but some packages can't installed ,so the package version may be different.

**Comment by pengsida** [comment]
Our implementation of the icp algorithm requires the specific version of python libararies and a computer with a head.

**Comment by tiexuedanxin** [comment]
could you give me your wechat, i am also a student of zju, I hope I can learn from you, very thank you.

**Comment by pengsida** [comment]
You could email me.

**Comment by tiexuedanxin** [comment]
sorry again, i have installed the correct version of these package, but it still can't work,  the version of the packages are as follow, the first is the requirement.txt and the second is me.
requirement.txt.
yacs==0.1.4
numpy==1.16.4
torchvision==0.2.1
opencv-python==3.4.2.17
tqdm==4.28.1
pycocotools==2.0.0
matplotlib==2.2.2
plyfile==0.6
scikit-image==0.14.2
scikit-learn
PyOpenGL==3.1.1a1
ipdb==0.11
cyglfw3==3.1.0.2
pyassimp==3.3
progressbar==2.5
open3d-python==0.5.0.0
tensorboardX==1.2
cffi==1.11.5
//--------------------------------------------------------------------------------------------------------------
(PVNet) heyong@csc104-server1:/mnt/data/heyong/PycharmProjects/clean-pvnet-master$ pip list
Package               Version   
--------------------- ----------
attrs                 19.3.0    
backcall              0.1.0     
bleach                3.1.0     
certifi               2019.9.11 
cffi                  1.11.5    
cloudpickle           1.2.2     
cycler                0.10.0    
cyglfw3               3.1.0.2   
Cython                0.28.2    
cytoolz               0.10.1    
dask                  2.9.0     
decorator             4.4.1     
defusedxml            0.6.0     
easydict              1.7       
entrypoints           0.3       
filelock              3.0.12    
glumpy                1.0.6     
imageio               2.6.1     
importlib-metadata    1.3.0     
ipdb                  0.11      
ipykernel             5.1.3     
ipython               7.11.1    
ipython-genutils      0.2.0     
ipywidgets            7.5.1     
jedi                  0.15.2    
Jinja2                2.10.3    
joblib                0.14.0    
jsonschema            3.2.0     
jupyter-client        5.3.4     
jupyter-core          4.6.1     
kiwisolver            1.1.0     
knn-pytorch           0.1       
lmdb                  0.94      
MarkupSafe            1.1.1     
matplotlib            2.2.2     
mistune               0.8.4     
mkl-fft               1.0.15    
mkl-random            1.1.0     
mkl-service           2.3.0     
more-itertools        8.0.2     
nbconvert             5.6.1     
nbformat              4.4.0     
networkx              2.4       
nose                  1.3.7     
notebook              6.0.2     
numpy                 1.16.4    
olefile               0.46      
open3d                0.9.0.0   
open3d-python         0.5.0.0   
opencv-contrib-python 3.4.2.17  
opencv-python         3.4.2.17  
pandocfilters         1.4.2     
parso                 0.5.2     
pexpect               4.7.0     
pickleshare           0.7.5     
Pillow                4.3.0     
pip                   19.3.1    
plyfile               0.6       
progressbar           2.5       
prometheus-client     0.7.1     
prompt-toolkit        3.0.2     
protobuf              3.11.2    
ptyprocess            0.6.0     
pyassimp              3.3       
pycocotools           2.0.0     
pycparser             2.19      
Pygments              2.5.2     
PyOpenGL              3.1.1a1   
pyparsing             2.4.6     
pyrsistent            0.15.6    
python-dateutil       2.8.1     
python-pcl            0.3.0a1   
pytz                  2019.3    
PyWavelets            1.1.1     
PyYAML                5.1.2     
pyzmq                 18.1.1    
scikit-image          0.14.2    
scikit-learn          0.21.3    
scipy                 1.3.2     
Send2Trash            1.5.0     
setuptools            39.1.0    
six                   1.13.0    
tensorboardX          1.2       
terminado             0.8.3     
testpath              0.4.4     
toolz                 0.10.0    
torch                 1.0.0     
torchsummary          1.5.1     
torchvision           0.2.1     
tornado               6.0.3     
tqdm                  4.28.1    
traitlets             4.3.3     
transforms3d          0.3.1     
triangle              20190115.3
wcwidth               0.1.7     
webencodings          0.5.1     
wheel                 0.33.6    
widgetsnbextension    3.5.1     
yacs                  0.1.4     
zipp                  0.6.0

**Comment by pengsida** [comment]
Is your computer headless?

**Comment by tiexuedanxin** [comment]
i am very sorry to bother you, i don't know whether the computer headless, because it is a Server computer, and i find the following code cause the error.I would appreciate it if you could help me.
> # self.__id:  [1491265040]
 # GL_FRAMEBUFFER:  GL_FRAMEBUFFER(36160)
 # GL_FRAMEBUFFER_COMPLETE:  GL_FRAMEBUFFER_COMPLETE(36053)
 if glCheckNamedFramebufferStatus(self.__id, GL_FRAMEBUFFER) !=GL_FRAMEBUFFER_COMPLETE:
            raise RuntimeError('Framebuffer not complete.')
>

**Comment by pengsida** [comment]
If it is a server computer, it is probably not connected with a display device.

**Comment by tiexuedanxin** [comment]
our server computer have the display device, and we can't find where the problem is. I would like to ask you face to face, if you are convenient

**Comment by pengsida** [comment]
I think that there is no difference from discussion online.
If you want, you could email me for my address.
Actually, I didn't encounter such problem.
How about searching on the google first?
https://github.com/DLR-RM/AugmentedAutoencoder/issues/3
