### ISSUE TITLE
How to split train, validation and test data in linemod?

### ISSUE THREAD

**Issue by Masahiro1002** [zju3dv/clean-pvnet#100]
Hello, I would like to ask how to split train, validation, and test data in linemod.
According to your repo, I prepared 10000 rendering images and 10000 fuse images by using pvnet-rendering. Then I retrained about the duck dataset and compare the result with your provided weight.

My question is about test.json and occ.json. It seems that test.json and occ.json contain all of linemod dataset and occlusion linemod dataset, and use them as validation dataset in the training. In each validation step, it seems that all of the test datasets are checked. 
Is this recognition correct? 
If I misunderstand it, could you tell me where you split training and validation data in the source code?

The duck results are the following. I think I could get the expected results.

====== mine ======
linemod
2d projections metric: 0.9887323943661972
ADD metric: 0.6187793427230047
5 cm 5 degree metric: 0.9568075117370892
mask ap70: 0.9981220657276996
occlusion linemod
2d projections metric: 0.5670464504820333
ADD metric: 0.3067484662576687
5 cm 5 degree metric: 0.17703768624014024
mask ap70: 0.8466257668711656
====== provided ======
linemod
2d projections metric: 0.9877934272300469
ADD metric: 0.5596244131455399
5 cm 5 degree metric: 0.9230046948356807
mask ap70: 0.9971830985915493
occlusion linemod
2d projections metric: 0.6073619631901841
ADD metric: 0.32602979842243646
5 cm 5 degree metric: 0.16126205083260298
mask ap70: 0.8098159509202454

Thank you!

**Comment by pengsida** [comment]
I simply trained the network for 200 epochs.
I do not split the validation and test data.

**Comment by Masahiro1002** [comment]
Thank you for your quick reply.
So you mean you used all of linemod dataset and occluded linemod dataset as validation and test dataset. Is my understanding correct?

**Comment by pengsida** [comment]
I used the test split of linemod dataset as the test dataset.

**Comment by Masahiro1002** [comment]
I got it. For example, you used 189 images as training and 1065 images as validation and testing, in the 1254 images of linemod duck. 
Sorry to bother you again.

**Comment by pengsida** [comment]
Yes.
