### ISSUE TITLE
Creating a dataset

### ISSUE THREAD

**Issue by ahmedreyad2019** [zju3dv/clean-pvnet#103]
I have the .ply model, how do I create a dataset from it?

**Comment by pengsida** [comment]
You could render synthetic data using https://github.com/zju3dv/pvnet-rendering
If you have a real object model, you could annotate the 6d poses manually.

**Comment by ahmedreyad2019** [comment]
but there is an issue in pvnet-rendering about creating custom dataset, and the solution is to use clean-pvnet instead. 

> You could render synthetic data using https://github.com/zju3dv/pvnet-rendering
> If you have a real object model, you could annotate the 6d poses manually.

**Comment by pengsida** [comment]
Clean-pvnet is able to render synthetic data, but I do not provide the guidance.

**Comment by ahmedreyad2019** [comment]
> Clean-pvnet is able to render synthetic data, but I do not provide the guidance.

Thank you. I was able to generate renders for the custom dataset. However, I don't understand what the arrays generated in blender_poses.npy are used for. and do I need to combine them with the original poses to be used for training?

**Comment by pengsida** [comment]
`blender_poses.npy` stores poses for rendering images.

**Comment by pengsida** [comment]
You do not need to combine them for training.

**Comment by ahmedreyad2019** [comment]
so I need only the RT in the pkl files generated?

> You do not need to combine them for training.

**Comment by pengsida** [comment]
Yes.
