### ISSUE TITLE
Resume training

### ISSUE THREAD

**Issue by hubbup** [zju3dv/clean-pvnet#104]
Thank you for such a good inplementation.

I have an issue when I try to resume training from your pretrained model.

In the load_model function in net_utils.py,
the optim.load_state_dict line causes valueerror "loaded state dict has a different number of parameter groups".

How can I solve this problem?

**Comment by pengsida** [comment]
What is your command?

**Comment by hubbup** [comment]
I tried to resume with the following command:
python train_net.py --cfg_file configs/linemod.yaml model cat cls_type cat

**Comment by pengsida** [comment]
The pretrained models were trained on https://github.com/zju3dv/pvnet

**Comment by hubbup** [comment]
Do you mean
we can load the pretrained models and test them with the clean-pvnet code, but cannot resume training?

**Comment by pengsida** [comment]
Yes.

**Comment by hubbup** [comment]
Thank you for your fast and clear response.
