### ISSUE TITLE
Is this RANSAC algorithm works the same way as openCV's solvepnpransac?

### ISSUE THREAD

**Issue by darwinharianto** [zju3dv/clean-pvnet#105]
Hello, thanks for sharing this wonderful piece of works.
I was trying to understand how the algorithm works. I see that you are inferring multiple key points, then putting it on Ransac algorithm which then would be passed over to solvePNP p3p.

Will this yields the same result if we skip the ransac part, then passed the inferred key points to solvepnpransac?

**Comment by pengsida** [comment]
The keypoints are given by the RANSAV algorithm.
