### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by KatharinaSchmidt** [zju3dv/clean-pvnet#108]
First I want to thank you for providing the code handle_custom_dataset.py. I've got a question regarding the usage of my own custom dataset. 
I generated a Dataset using [NDDS](https://github.com/NVIDIA/Dataset_Synthesizer/tree/1.2.2). So i got rgb images, depth images, class segmentation and Annotation. I also got my models in .ply-files. 
Is there a way to use this synthetic dataset instead of creating a new one with [pvnet-rendering](https://github.com/zju3dv/pvnet-rendering) and [ObjectDatasetTools](https://github.com/F2Wang/ObjectDatasetTools).

To give you some expamples, my images and Annotation look like this: 

RGB-Image:
![000000](https://user-images.githubusercontent.com/62353042/86157415-a7a51300-bb07-11ea-949a-800243217023.png)
Depth-Image:
![000000 depth](https://user-images.githubusercontent.com/62353042/86157420-aa076d00-bb07-11ea-8f8e-7ecc95ed4f6e.png)
Instance-Segmentation:
![000000 is](https://user-images.githubusercontent.com/62353042/86157427-ac69c700-bb07-11ea-8582-84d22d270c12.png)

Camera-Settings: 
{
	"camera_settings": [
		{
			"name": "Viewpoint",
			"horizontal_fov": 90,
			"intrinsic_settings":
			{
				"resX": 512,
				"resY": 512,
				"fx": 256,
				"fy": 256,
				"cx": 256,
				"cy": 256,
				"s": 0
			},
			"captured_image_size":
			{
				"width": 512,
				"height": 512
			}
		}
	]
}

Annotation for each set of images in my custom dataset: 
 "camera_data":
	{
		"location_worldframe": [ 66.380996704101563, -21.26409912109375, 90.514198303222656 ],
		"quaternion_xyzw_worldframe": [ -0.19810000061988831, 0.018400000408291817, 0.97579997777938843, 0.090599998831748962 ]
	},
	"objects": [
		{
			"class": "BC283R_CPA_000",
			"instance_id": 342392,
			"visibility": 1,
			"location": [ -29.71150016784668, -11.213100433349609, 81.0697021484375 ],
			"quaternion_xyzw": [ 0.30889999866485596, 0.82309997081756592, 0.4341999888420105, -0.19650000333786011 ],
			"pose_transform": [
				[ -0.055300001055002213, 0.83609998226165771, -0.54570001363754272, 0 ],
				[ -0.73189997673034668, 0.33779999613761902, 0.59170001745223999, 0 ],
				[ -0.67909997701644897, -0.43220001459121704, -0.5932999849319458, 0 ],
				[ -29.71150016784668, -11.213100433349609, 81.0697021484375, 1 ]
			],
			"cuboid_centroid": [ -29.71150016784668, -11.213100433349609, 81.0697021484375 ],
			"projected_cuboid_centroid": [ 162.17759704589844, 220.59150695800781 ],
			"bounding_box":
			{
				"top_left": [ 205.67410278320313, 146.977294921875 ],
				"bottom_right": [ 237.40379333496094, 177.33610534667969 ]
			},
			"cuboid": [
				[ -36.237098693847656, -6.4878997802734375, 84.178596496582031 ],
				[ -24.215599060058594, -12.036399841308594, 74.459602355957031 ],
				[ -23.475200653076172, -11.565199851989746, 75.106498718261719 ],
				[ -35.496700286865234, -6.0166997909545898, 84.82550048828125 ],
				[ -35.947898864746094, -10.861100196838379, 87.03289794921875 ],
				[ -23.926399230957031, -16.409500122070313, 77.31390380859375 ],
				[ -23.186000823974609, -15.938300132751465, 77.960800170898438 ],
				[ -35.207401275634766, -10.389900207519531, 87.679801940917969 ]
			],
			"projected_cuboid": [
				[ 145.79730224609375, 236.26919555664063 ],
				[ 172.74409484863281, 214.61759948730469 ],
				[ 175.98500061035156, 216.58009338378906 ],
				[ 148.87249755859375, 237.84170532226563 ],
				[ 150.26229858398438, 224.0531005859375 ],
				[ 176.77540588378906, 201.66520690917969 ],
				[ 179.86430358886719, 203.66329956054688 ],
				[ 153.20429992675781, 225.66459655761719 ]
			]
		},
		{
			"class": "BH442R_CPA_000",
			"instance_id": 684784,
			"visibility": 0.69010001420974731,
			"location": [ -59.664798736572266, 42.804401397705078, 75.334297180175781 ],
			"quaternion_xyzw": [ -0.05429999902844429, 0.79720002412796021, -0.58289998769760132, -0.14710000157356262 ],
			"pose_transform": [
				[ -0.17129999399185181, -0.94539999961853027, -0.27709999680519104, 0 ],
				[ -0.95080000162124634, 0.085000000894069672, 0.29789999127388, 0 ],
				[ 0.2581000030040741, -0.31450000405311584, 0.91350001096725464, 0 ],
				[ -59.664798736572266, 42.804401397705078, 75.334297180175781, 1 ]
			],
			"cuboid_centroid": [ -59.664798736572266, 42.804401397705078, 75.334297180175781 ],
			"projected_cuboid_centroid": [ 53.248100280761719, 401.4573974609375 ],
			"bounding_box":
			{
				"top_left": [ 389.09820556640625, 29.354999542236328 ],
				"bottom_right": [ 413.40301513671875, 74.427398681640625 ]
			},
			"cuboid": [
				[ -67.807502746582031, 40.099800109863281, 76.961402893066406 ],
				[ -52.600299835205078, 38.740898132324219, 72.196197509765625 ],
				[ -52.721698760986328, 38.888698577880859, 71.766799926757813 ],
				[ -67.928802490234375, 40.247699737548828, 76.531997680664063 ],
				[ -66.607803344726563, 46.720100402832031, 78.901802062988281 ],
				[ -51.400699615478516, 45.361198425292969, 74.1365966796875 ],
				[ -51.522098541259766, 45.508998870849609, 73.707199096679688 ],
				[ -66.729202270507813, 46.867900848388672, 78.472396850585938 ]
			],
			"projected_cuboid": [
				[ 30.449199676513672, 389.38580322265625 ],
				[ 69.484703063964844, 393.37109375 ],
				[ 67.935997009277344, 394.72030639648438 ],
				[ 28.777900695800781, 390.62860107421875 ],
				[ 39.888301849365234, 407.585205078125 ],
				[ 78.508903503417969, 412.6361083984375 ],
				[ 77.053497314453125, 414.06210327148438 ],
				[ 38.310001373291016, 408.89700317382813 ]
			]
		}
}
]
}

My overall target is to train pvn3d with my custom dataset, but for that I still need the keypoints of my models, etc. 
I hope you can help me with my problem.

**Comment by pengsida** [comment]
Yes, you can synthesize training data with https://github.com/zju3dv/pvnet-rendering
But the code synthesizes only one object in an image.

**Comment by KatharinaSchmidt** [comment]
Thanks for the advice

**Comment by emilychen6160** [comment]
@KatharinaSchmidt 
Hello! Do you use the NDDS to build the custom datasets?
When you use the NDDS generating the pictures, is there any problem in the corner3d points for executing the "base_utils.py"?
Thank you~

**Comment by emilychen6160** [comment]
Because I have a problem: "ValueError: operands could not be broadcast together with shapes (8,3,480) (3,637,480)" . My .ply is generated by blender, and pictures are synthesized by NDDS in Unreal.
