### ISSUE TITLE
Can I get a webcam demo?

### ISSUE THREAD

**Issue by tjdalsckd** [zju3dv/clean-pvnet#11]
Thank you, your document is very useful to me.

I want to use your network through my webcam.

Can I get a webcam demo?

**Comment by pengsida** [comment]
Maybe. I will upload a video version in this weekend.

**Comment by pengsida** [comment]
I have to postpone the demo, since I am busy at other things.
It is feasible to decode the video into images and use the PVNet to predict every image.

**Comment by tjdalsckd** [comment]
Since then, I have succeeded in using Azure Kinect to create demo
files. Thank you for your answer.

2020년 1월 12일 (일) 오후 8:39, pengsida <notifications@github.com>님이 작성:
