### ISSUE TITLE
t-less performance

### ISSUE THREAD

**Issue by AingLee** [zju3dv/clean-pvnet#110]
Hi, guy, thank you for your code. I have a little wonder related to the performance of t-less dateset. It seems that the performance is very low. I do not know whether I have trained and tested in the right way or not. I have tested the model of tless_04, and I got this.
vsd metric: 0.0
adi metric: 0.013888888888888888
5 cm 5 degree metric: 0.001984126984126984

is this performance correct?

**Comment by pengsida** [comment]
Did you test with your own model?

**Comment by AingLee** [comment]
No, I tested it with your provided model. What is your performance then related to tless_04? Let me check again whether I have modified something.

**Comment by AingLee** [comment]
I have found out that I had modified "test.json". After replacing the original one and testing again, I got this result for tless_04. 
vsd metric: 0.0
adi metric: 0.10198412698412698
5 cm 5 degree metric: 0.060714285714285714
Is that normal? The vsd metric is zero?

**Comment by pengsida** [comment]
No, it is not normal.

![image](https://user-images.githubusercontent.com/11582122/87295833-631e6c00-c538-11ea-883d-0587447bbb1d.png)

**Comment by AingLee** [comment]
Ok, I have found the problem. Thank you so much.

**Comment by monajalal** [comment]
@AingLee  @pengsida 

Could you please let me know why my results are very different and how to fix it? Thanks for your time

```
(clean-pvnet) mona@ada:~/clean-pvnet$ python run.py --type evaluate --cfg_file configs/tless/tless_01.yaml test.vsd True
/home/mona/anaconda3/envs/clean-pvnet/lib/python3.10/site-packages/imgaug/imgaug.py:184: DeprecationWarning: Function `ContrastNormalization()` is deprecated. Use `imgaug.contrast.LinearContrast` instead.
  warn_deprecated(msg, stacklevel=3)
loading annotations into memory...
Done (t=3.80s)
creating index...
index created!
loading annotations into memory...
Done (t=4.34s)
creating index...
index created!
yaml file path is:  data/tless/models_cad/models_info.yml
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2927/2927 [03:20<00:00, 14.57it/s]
0it [00:00, ?it/s]/home/mona/.local/lib/python3.10/site-packages/imageio/plugins/pillow.py:312: UserWarning: Loading 16-bit (uint16) PNG as int32 due to limitations in pillow's PNG decoder. This will be fixed in a future version of pillow which will make this warning dissapear.
  warnings.warn(
2927it [05:53,  8.28it/s]
vsd metric: 0.0
adi metric: 0.0009953550099535502
5 cm 5 degree metric: 0.0

```
