### ISSUE TITLE
version `GLIBC_2.27' not found 

### ISSUE THREAD

**Issue by Apollo19971206** [zju3dv/clean-pvnet#114]
When I run the code :

`python run.py --type linemod cls_type cat`

ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found

Is that due to my ubuntu version of 16.04 which only support GLIBC2.23 only?
Which version of ubuntu do you use?

Look forward to your reply，thank you!

> ``

**Comment by pengsida** [comment]
It is caused by the open3d version.
You could install `open3d-python==0.5.0.0`.

**Comment by Apollo19971206** [comment]
> It is caused by the open3d version.
> You could install `open3d-python==0.5.0.0`.

This solved my problem. First of all, thank you very much! 

May you tell me how did you find it was due to the version of open3d? Did you meet the same question and fixed it by changing the version? It bothered me for a long time and I didn't find the reason.

**Comment by pengsida** [comment]
I used google to find the solution.

**Comment by Apollo19971206** [comment]
> I used google to find the solution.
ha-ha  fine  thank you again!
