### ISSUE TITLE
Original tless dataset

### ISSUE THREAD

**Issue by AingLee** [zju3dv/clean-pvnet#115]
Thank you for your clean pvnet code, recently, I am trying to re-train the tless dataset with new features, so that I have to re-generate the file of train.json for each tless object. However, I found that there was no the original tless dataset in "train_primesense/01-30"  which contains folders of rgb, mask, gt.yaml, and etc. Actually, I can download some of them from the internet, but it seems that there are more folders or files needed. Would you mind uploading the original tless dataset? Thank you.

**Comment by pengsida** [comment]
The original tless is too big to upload.
You could download it from the official site.

**Comment by AingLee** [comment]
Thank you for your reply. I have another question which is related to FPS for tless dataset. I have reproduced the 3D FPS by using tless CAD models provided in the folder of "data/tless/models_cad". The reproduced 8 farthest points are different from the ones in "data/tless/farthest", and I also have found that the CAD models are strange. They seem to be incomplete. I would like to know that whether you have added some more techniques on original FPS or not, and also I would like to confirm about your provided CAD models are correct or not, because I am afraid that I have used the wrong CAD models to compare with yours. The following images are the plotted from the CAD model for tless_02. The left side image is from your CAD model and the right one is from official site.

![save3](https://user-images.githubusercontent.com/46101939/88453247-cfce2a80-ce97-11ea-9ce4-cfc4cac50e73.png)

**Comment by pengsida** [comment]
1. It is common for the FPS algorithm to produce different sets of keypoints.
2. What is the cad model?

**Comment by AingLee** [comment]
On the left side, I used the model of "obj_002.ply" from the folder "clean-pvnet/data/tless/models_cad". On the right side, I used the model of "obj_02.ply" from the original dataset folder 
"t-less_v2_models_cad_subdivided/models_cad_subdivided". I found that either "colobj_02.ply" or "obj_02.ply" in "clean-pvnet/data/tless/models_cad" are all the same when they are plotted in 3D space. Is "obj_002.ply" the model you used to find the FPS keypoints for "farthest_02.txt"?

**Comment by AingLee** [comment]
This is the cad model of "obj_02.ply" from "t-less_v2_models_reconst/models_reconst" (original dataset).

![Picture1](https://user-images.githubusercontent.com/46101939/88577800-2c893b00-d07a-11ea-88c6-f40f0a4415f2.png)

**Comment by pengsida** [comment]
The unit is the only difference between `obj_002.ply` and `obj_01.ply`.
The units of `obj_002.ply` and `obj_01.ply` are m and mm, respectively.

**Comment by AingLee** [comment]
Ok, I got it. However, could you show where the code to generate "farthest_02.txt" in "data/tless/farthest" is? I could not find it in "clean-pvnet". Thanks

**Comment by pengsida** [comment]
I do not provide this script.
You could generate the FPS points using https://github.com/zju3dv/clean-pvnet/blob/f54fefa1e88cc50cce603f37815a011f3137d137/tools/handle_custom_dataset.py#L19

**Comment by AingLee** [comment]
Thanks.
