### ISSUE TITLE
Missing diameter.txt

### ISSUE THREAD

**Issue by KatharinaSchmidt** [zju3dv/clean-pvnet#117]
Hey, 

I try to customize clean-pvnet for my own dataset and running on CUDA 10.2 with a GeForce GTX 960 (it's very slow, but it works). I generated rgb-files, depth-files, maks and annotations (json-File) with [NDDS](https://github.com/NVIDIA/Dataset_Synthesizer). I already adapted the code for processing my dataset with `python run.py --type custom` and it works fine. 
If I try to run `python train_net.py --cfg_file configs/custom.yaml train.batch_size 1` I get the following error:
```
OSError: data/custom/diameter.txt not found.
```

That makes sense, since I don't have a file called diameter.txt. 
But I have my 3D-modells as .ply-files. How can I get the diameter.txt from them? 

Thanks in advance for any help or advice.

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/issues/36
