### ISSUE TITLE
关于划分custom数据集

### ISSUE THREAD

**Issue by chenjiale5** [zju3dv/clean-pvnet#119]
作者你好!
目前我已经严格按照你给的步骤训练了自己的数据集,但是效果却不尽人意,我想可能是以下两个问题造成的
1.目前我一共有3727张图片,程序自动划分了九百多张图片作为训练集,而测试却有3727(全部)张图片,请问我如何自己划分数据集呢?
2.Prepare the data步骤只为我的数据集生成了train.json,请问我需要生成test.json这个文件吗?如果test.json是必要的,我应该做些什么呢?

**Comment by chenjiale5** [comment]
另外ply文件中的face数据是必须的吗?我只给了程序顶点数据,这会对结果造成影响吗?

**Comment by pengsida** [comment]
1. 我没看过你的训练数据，不知道你效果不好的原因。我们在自己的数据上只用100多张图片训练，效果还不错。
2. 我不知道划分数据集的标准，你要自己建立一个数据集吗。
3. 如果你不测试，不需要生成test.json。可以参考生成linemod数据集test.json的代码。

**Comment by chenjiale5** [comment]
感谢你的回复!
我在论文中看到PVNet可以应对multiple instances的情况,如果我的数据集中一张图片存在几个相同的物体,我应该如何操作呢?

**Comment by chenjiale5** [comment]
> 1. 我没看过你的训练数据，不知道你效果不好的原因。我们在自己的数据上只用100多张图片训练，效果还不错。
> 2. 我不知道划分数据集的标准，你要自己建立一个数据集吗。
> 3. 如果你不测试，不需要生成test.json。可以参考生成linemod数据集test.json的代码。

感谢你的回复!
我在论文中看到PVNet可以应对multiple instances的情况,如果我的数据集中一张图片存在几个相同的物体,我应该如何操作呢?

**Comment by pengsida** [comment]
建议加一个object detector。

**Comment by chenjiale5** [comment]
好的,谢谢

**Comment by kiterunnerly** [comment]
你好，请问一下你自己的数据集是用的ObjectDatasetTools方法生成的吗？如果是的话，我想问一下是如何生成多个对象的数据集的呢？

**Comment by chenjiale5** [comment]
不好意思，我没有用过ObjectDatasetTools



------------------&nbsp;Original&nbsp;------------------

**Comment by pengsida** [comment]
合成数据集可以用这个：https://github.com/DLR-RM/BlenderProc

**Comment by kiterunnerly** [comment]
好的，谢谢

**Comment by RiplleYang** [comment]
> 作者你好!
> 目前我已经严格按照你给的步骤训练了自己的数据集,但是效果却不尽人意,我想可能是以下两个问题造成的
> 1.目前我一共有3727张图片,程序自动划分了九百多张图片作为训练集,而测试却有3727(全部)张图片,请问我如何自己划分数据集呢?
> 2.Prepare the data步骤只为我的数据集生成了train.json,请问我需要生成test.json这个文件吗?如果test.json是必要的,我应该做些什么呢?

请问程序自动划分训练集和测试集的地方您找到了吗,麻烦告知我一声,谢谢了

**Comment by pengsida** [comment]
代码没有自动划分训练集和数据集。我们用的是以前别人划分好的。

**Comment by RiplleYang** [comment]
你好，再次打扰到你我在用custom数据集训练时发现您使用linemod和tless训练时，实例化了icp_utils中的ICPRefiner，这在相同目录位置的custom/pvnet.py中表现为SynRenderer，这个类却不在icp_utils中，请问这个render具体是做什么用呢另外用您的方法训练自制数据集，vote_loss大了一个数据级，seg_loss表现很好，请您指教一下可能存在的问题-------- 原始邮件 --------发件人： pengsida ***@***.***>日期： 2021年3月31日周三 22:05收件人： zju3dv/clean-pvnet ***@***.***>抄送： RiplleYang ***@***.***>, Comment ***@***.***>主    题： Re: [zju3dv/clean-pvnet] 关于划分custom数据集 (#119)

代码没有自动划分训练集和数据集。我们用的是以前别人划分好的。

**Comment by cgm6666** [comment]
> 作者你好!
> 目前我已经严格按照你给的步骤训练了自己的数据集,但是效果却不尽人意,我想可能是以下两个问题造成的
> 1.目前我一共有3727张图片,程序自动划分了九百多张图片作为训练集,而测试却有3727(全部)张图片,请问我如何自己划分数据集呢?
> 2.Prepare the data步骤只为我的数据集生成了train.json,请问我需要生成test.json这个文件吗?如果test.json是必要的,我应该做些什么呢?

你好,请问你解决了自制数据集训练效果差的问题了吗?

**Comment by RiplleYang** [comment]
你好，我是自制的linmed格式数据集，并分成了2（train）：1（test），vote_loss效果很差，但是seg_loss效果很好可能是由什么原因造成的呢，重新检查了一下anno里面的fps等信息也没有很明显的错误-------- 原始邮件 --------发件人： pengsida ***@***.***>日期： 2021年3月31日周三 22:05收件人： zju3dv/clean-pvnet ***@***.***>抄送： RiplleYang ***@***.***>, Comment ***@***.***>主    题： Re: [zju3dv/clean-pvnet] 关于划分custom数据集 (#119)

代码没有自动划分训练集和数据集。我们用的是以前别人划分好的。

**Comment by pengsida** [comment]
最终pose estimation的效果怎样。

**Comment by cgm6666** [comment]
> 最终pose estimation的效果怎样。

我目前解决了这一问题，3个epoch后就已经收敛的十分出色。
