### ISSUE TITLE
What is the format of camera.txt in custom dataset ?

### ISSUE THREAD

**Issue by IaroslavS** [zju3dv/clean-pvnet#12]
What is the format of camera.txt in custom dataset ?
Organize the dataset as the following structure:
├── /path/to/dataset
│   ├── model.ply
│   ├── camera.txt
│   ├── rgb/
│   │   ├── 0.jpg
│   │   ├── ...
│   │   ├── 1234.jpg
│   │   ├── ...
│   ├── mask/
│   │   ├── 0.png
│   │   ├── ...
│   │   ├── 1234.png
│   │   ├── ...
│   ├── pose/
│   │   ├── 0.npy
│   │   ├── ...
│   │   ├── 1234.npy
│   │   ├── ...
│   │   └──

And I'd like to see an eample of this camera.txt. there's no such file camera.txt In LINEMOD dataset

**Comment by pengsida** [comment]
If you download the custom dataset,  you will see it.

**Comment by IaroslavS** [comment]
> If you download the custom dataset, you will see it.

Where can I download the custom dataset ?

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/71882953-5b889f80-3170-11ea-8097-69f54a99c2de.png)

**Comment by IaroslavS** [comment]
Now, I see. Thanks for your quickest ever answer, pengsida.

**Comment by neighthan** [comment]
The example `camera.txt` has the following content:

```
5.724113999999999578e+02 0.000000000000000000e+00 3.252610999999999990e+02
0.000000000000000000e+00 5.735704299999999876e+02 2.420489900000000034e+02
0.000000000000000000e+00 0.000000000000000000e+00 1.000000000000000000e+00
```

Could you describe what the entries in this 3x3 matrix are?

**Comment by pengsida** [comment]
Intrinsic camera matrix.
