### ISSUE TITLE
关于linemod数据集

### ISSUE THREAD

**Issue by shanniruo** [zju3dv/clean-pvnet#120]
您好，请问一下linemod数据集中有两个文件，mesh.ply和object.xyz。似乎都是前三列存储着点云坐标，它们有什么区别吗？因为我看它们前三列并不一致。

**Comment by pengsida** [comment]
都存着点云坐标，两个模型坐标系不同。

**Comment by shanniruo** [comment]
彭总，可以耽误您1分钟问个代码问题吗？请问这篇工作这行代码获取2D坐标
https://github.com/yshah43/DPOD/blob/master/create_ground_truth.py#L102
这里的@  是什么用法？

**Comment by pengsida** [comment]
矩阵相乘的意思，和np.dot()差不多。
