### ISSUE TITLE
Validation for Linemod and Occlusion Linemod

### ISSUE THREAD

**Issue by Anshul-Gupta24** [zju3dv/clean-pvnet#121]
Hi, can you explain how you perform validation to select the best epoch for Linemod and Occlusion Linemod? Do you use the LinemodTest or LinemodOccTest split for this? Also, is the epoch selected through validation the same for Linemod and Occlusion Linemod? Thanks.

**Comment by pengsida** [comment]
We simply train the network for 200 epochs.
The selected epoch is the same for Linemod and Occluded Linemod.

**Comment by Anshul-Gupta24** [comment]
Thanks for the clarification.
