### ISSUE TITLE
question about segmentation

### ISSUE THREAD

**Issue by KatharinaSchmidt** [zju3dv/clean-pvnet#122]
Hello, 
in your paper you said, that PVNet can detect multiple instances of one objectclass. That would be great for my own project too. I've got classbased segmentation-masks and instancebased segmentation-masks. May you help me with the question, which mask I should use for training? So my trained PVNet can find 2 oder more objects from the same class in a picture.
Thank you for helping me with this question.

**Comment by pengsida** [comment]
The code does not implement instance segmentation.
You could add a detector to handle multiple objects.
