### ISSUE TITLE
Some problems about keypoints 

### ISSUE THREAD

**Issue by pyni** [zju3dv/clean-pvnet#127]
Hi~ 
i have several questions about this project:
1.Could you please share the codes of visualization of keypoints for detected model?
2.After reading your paper, i am interested about keypoints. I wonder whether the location of keypoints will affect the final performance.
For an example, will the keypoints located on the sharp edges may be easier to be detected or get better accuracy?

**Comment by pengsida** [comment]
1.Which keypoints do you want to visualize, 2D keypoints or 3D keypoints?
2. Yes, the keypoints do affect the performance.

**Comment by pyni** [comment]
Thanks, 2D keypoints.
 i have found them in visualization.ipynb.
