### ISSUE TITLE
Set Up in Docker

### ISSUE THREAD

**Issue by mandywoo** [zju3dv/clean-pvnet#128]
I noticed that the original pvnet could be run in a docker: https://github.com/zju3dv/pvnet/blob/master/docker/how-to-docker.md. Could this version of clean-pvnet be run in a docker following the same instructions or are there new instructions on how to run this in a docker?

**Comment by pengsida** [comment]
No.
It is Joe Dinius that provides the docker implementation.
I seldom use docker.

**Comment by SaphireFalcon** [comment]
I actually made the clean-pvnet run in a docker. If you're interested, I could share it.

**Comment by mandywoo** [comment]
@SaphireFalcon  Please do! Thank you!

**Comment by SaphireFalcon** [comment]
Oke. I'm now doing training to test if it works (and I can use it for what I have to do).
Then I'll have to adjust a few things (its missing tensorboard). I'll post here again after the weekend with an update.

**Comment by mandywoo** [comment]
Sounds good, thanks!

**Comment by mandywoo** [comment]
@SaphireFalcon Is there any update?

**Comment by mandywoo** [comment]
@SaphireFalcon Is there any update?

**Comment by SaphireFalcon** [comment]
Sorry! I forgot about it, I'll try to make a docker file this week.

**Comment by SaphireFalcon** [comment]
I managed to strip the docker of all the things that I needed in the docker.
Here you can find it in my git: https://github.com/SaphireFalcon/clean-pvnet/tree/feature/docker
I'll also create a pull request.

**Comment by mandywoo** [comment]
Thank you!

**Comment by susuhu** [comment]
> I managed to strip the docker of all the things that I needed in the docker. Here you can find it in my git: https://github.com/SaphireFalcon/clean-pvnet/tree/feature/docker I'll also create a pull request.

thank you for the dockerfile, but I ran into version problem below with the later part of the dockerfile.
from the previous output, it seems that cuda and python are successfully installed.  how do I proceed further? 

`Collecting ipdb==0.11
  Downloading ipdb-0.11.tar.gz (9.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/pvnet/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7iwu8g4p/ipdb_174792d67b5a480ba9d7314     86b03ec31/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7iwu8g4p/ipdb_174792d67b5a480ba9d731486b03ec31/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__fil     e__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exe     c(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-r7rk700p
         cwd: /tmp/pip-install-7iwu8g4p/ipdb_174792d67b5a480ba9d731486b03ec31/
    Complete output (1 lines):
    error in ipdb setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/80/fe/4564de08f174f3846364b3add8426d14cebee228f741c27e702b2877e85b/ipdb-0.11.tar.gz#sha256=7081c65ed7bfe77     37f83fa4213ca8afd9617b42ff6b3f1daf9a3419839a2a00a (from https://pypi.org/simple/ipdb/) (requires-python:>=2.7). Command errored out with exit status 1: python setup.p     y egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement ipdb==0.11 (from versions: 0.1dev-r1556, 0.1dev-r1713, 0.1dev-r1714, 0.1dev-r1716, 0.1, 0.2, 0.3, 0.4,      0.5, 0.6, 0.6.1, 0.7, 0.7.1, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11, 0.12, 0.12.1, 0.12.2, 0.12.3.dev0, 0.1     2.3, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9)
ERROR: No matching distribution found for ipdb==0.11
The command '/bin/sh -c cd /opt &&     git clone https://github.com/zju3dv/clean-pvnet.git pvnet &&     cd pvnet &&     conda init bash &&     conda create -n pvnet p     ython=3.7 &&     . /opt/conda/etc/profile.d/conda.sh &&     conda activate pvnet &&     pip install --user torch==1.1.0 -f https://download.pytorch.org/whl/cu90/stabl     e &&     pip install --user Cython==0.28.2 &&     pip install -r requirements.txt &&     pip install --user transforms3d &&     cd .. &&     rm -rf pvnet' returned a `
