### ISSUE TITLE
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

### ISSUE THREAD

**Issue by SuperSivan** [zju3dv/clean-pvnet#129]
Thank you for your code!
I try "Testing on Linemod" and "Visualization on Linemod",same bug occurs in both procedure,when I run run.py：

Load model: data/model/pvnet/cat/199.pth
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
  0%|                                                     | 0/1002 [00:00<?, ?it/s]THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

Traceback (most recent call last):
  File "run.py", line 227, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 78, in run_evaluate
    output = network(inp)
  File "/home/sivan7/anaconda3/envs/clean-pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/pvnet/resnet18.py", line 100, in forward
    self.decode_keypoint(ret)
  File "lib/networks/pvnet/resnet18.py", line 75, in decode_keypoint
    kpt_2d = ransac_voting_layer_v3(mask, vertex, 128, inlier_thresh=0.99, max_num=100)
  File "/home/sivan7/clean-pvnet/lib/csrc/ransac_voting/ransac_voting_gpu.py", line 190, in ransac_voting_layer_v3
    ATA = torch.matmul(normal.permute(0, 2, 1), normal)              # [vn,2,2]
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:450

and my environment is :
CUDA:9.0
torch:1.1.0
NVIDIA 1660timq

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/issues/44

**Comment by Kuppharish** [comment]
@pengsida I have the same problem and the solution you've provided is not working. Can you please help me with this.

**Comment by pengsida** [comment]
The reason may be a mismatch between the CUDA version and pytorch version.
