### ISSUE TITLE
Use in a multi-object setting

### ISSUE THREAD

**Issue by damianomal** [zju3dv/clean-pvnet#13]
Hi,

thank you for your great work!

I noticed that [here](https://github.com/zju3dv/pvnet/issues/116) you suggested a few modifications to be done to the code to make it work in a multi-object setting.

I am interested in training a single network with samples containing multiple objects (with different class), can you give me a few hints about which parts of the network architecture should be modified to adapt it to this case?

**Comment by pengsida** [comment]
ver_dim and seg_dim: https://github.com/zju3dv/clean-pvnet/blob/master/lib/networks/pvnet/resnet18.py#L100

seg_dim means the number of object classes.
ver_dim is seg_dim * 2 * num_keypoints.

The dataset is also needed to revise to return the corresponding ground-truth.
