### ISSUE TITLE
Training of symmetric objects

### ISSUE THREAD

**Issue by Anshul-Gupta24** [zju3dv/clean-pvnet#130]
Hi, I tried training PVNet for eggbox but got much lower results than reported in the paper. I assume this is because of ambiguities in keypoint locations as mentioned in your paper. You mention that you _rotate the symmetric object to a canonical
pose during training_ to eliminate ambiguities. Can you please elaborate on this and provide the code for the rotation? Thanks!

**Comment by pengsida** [comment]
I took eggbox as a symmetric object during evaluation, not during training, so I did not rotate it to a canonical pose.

**Comment by Anshul-Gupta24** [comment]
I see, however does this not cause problems in training? As there could be ambiguities in keypoint location. Ex. The keypoint may be predicted symmetrically opposite to the ground truth keypoint, however it will incur a large loss.

**Comment by pengsida** [comment]
I did not find that it caused problem.
It may be because that eggbox is not completely symmetric.

**Comment by Anshul-Gupta24** [comment]
Ok, I'll probably try to rerun the experiment in that case. Also, in evaluation, do you consider eggbox to be symmetric only for the ADD metric?

**Comment by pengsida** [comment]
The eggbox is taken as symmetric for all metrics.

**Comment by Anshul-Gupta24** [comment]
Can you point to the code where eggbox is considered symmetric for the other metrics? I can see that eggbox and glue are considered separately for the ADD metric in line 192 of lib/evaluators/linemod/pvnet.py

**Comment by pengsida** [comment]
Sorry, I forgot to add projection_2d_sym in the repository: https://github.com/zju3dv/pvnet/blob/master/lib/utils/evaluation_utils.py#L83

**Comment by Anshul-Gupta24** [comment]
Thanks, I will use this code.

**Comment by Anshul-Gupta24** [comment]
To reconfirm, for glue class as well, do you only consider it as symmetric during evaluation?

**Comment by pengsida** [comment]
Yes.

**Comment by Anshul-Gupta24** [comment]
Thanks.
