### ISSUE TITLE
Error caused by pytorch version

### ISSUE THREAD

**Issue by sandy-ssdut** [zju3dv/clean-pvnet#131]
Hi,

As suggested at https://github.com/zju3dv/clean-pvnet/issues/4, I turn torch version form 1.10 to 0.4.1.

But I found that there seem to be some errors at ransac_vote when torch version = 0.4.1.

Using the same model weight, the bounding box drawn by run.py -- type visualized is right when torch = 1.1.0, but is wrong when torch = 0.4.1.

**Comment by pengsida** [comment]
What error?

**Comment by sandy-ssdut** [comment]
With the same pre-trained model weight， the kpt_2d computed after network forward under torch 1.1.0 is right， but that under torch 0.4.1 is wrong.

**Comment by pengsida** [comment]
I did not encounter this problem.
On my computer, the code works with both torch 1.1.0 and 0.4.1.

**Comment by sandy-ssdut** [comment]
Ah... 
I will check my local environment to find what happens.
