### ISSUE TITLE
Masked Images

### ISSUE THREAD

**Issue by mandywoo** [zju3dv/clean-pvnet#132]
I trained a model with on a dataset of black rectangular masked images. I then used this model to get the pose from black rectangular masked images and I noticed that the masks return by the model are not as expected. As you can see, the first image has the predicted pose and the second image is the predicted mask and it has a lot of white where in the original image it was the black mask. Is there a reason for this? For this image, the black mask doesn't seem to be a huge issue but I have other images with different size masks that result in a predicted mask being completely white which in turn gives wrong pose predictions. I have tried testing different color masks besides just black but have gotten the same result. Note, for the dataset I did the training on, the masks I have in that dataset are correct and outlines just the object, disregarding the black, so I'm not sure what went wrong.

![19_tested jpg_img](https://user-images.githubusercontent.com/31107127/93163561-53eca380-f6cc-11ea-997c-428194e84ff8.jpg)
![19_tested jpg_mask](https://user-images.githubusercontent.com/31107127/93163569-56e79400-f6cc-11ea-8f39-a488d276fdde.jpg)

**Comment by pengsida** [comment]
You could do some data augmentation.

**Comment by mandywoo** [comment]
I suppose I could make the black mask augmented in some way but the point of it was to block out some some of the unnecessary background. As you can see, the image underneath the mask is augmented. I tried training a model with images without the black mask and testing the model with images with the mask and it works fine but when I trained the model with masked images and tested it using masked images, I get this weird predicted mask.

**Comment by pengsida** [comment]
I do not know why.
Maybe there are some bugs existing in your data.
