### ISSUE TITLE
compile the uncertainty-driven PnP 

### ISSUE THREAD

**Issue by DCC-lzhy** [zju3dv/clean-pvnet#133]
```
python setup.py build_ext --inplace
generating ./_ext.c
(already up-to-date)
the current directory is '/home/luzhenyu/6D_Pose/clean-pvnet/lib/csrc/uncertainty_pnp'
running build_ext
building '_ext' extension
gcc -pthread -B /home/luzhenyu/miniconda3/envs/pvnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/luzhenyu/miniconda3/envs/pvnet/include/python3.7m -c _ext.c -o ./_ext.o
gcc -pthread -shared -B /home/luzhenyu/miniconda3/envs/pvnet/compiler_compat -L/home/luzhenyu/miniconda3/envs/pvnet/lib -Wl,-rpath=/home/luzhenyu/miniconda3/envs/pvnet/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_ext.o src/uncertainty_pnp.cpp.o ./lib/libceres.so ./lib/libglog.so -lstdc++ -o ./_ext.cpython-37m-x86_64-linux-gnu.so
/home/luzhenyu/miniconda3/envs/pvnet/compiler_compat/ld:./lib/libceres.so: file format not recognized; treating as linker script
/home/luzhenyu/miniconda3/envs/pvnet/compiler_compat/ld:./lib/libceres.so:0: syntax error
collect2: error: ld returned 1 exit status
```
I found some suggestions about it on the Web, but I have no idea. Could you check it?

**Comment by pengsida** [comment]
You need to git clone the code.

**Comment by DCC-lzhy** [comment]
Of course, I git clone it. 
 `collect2: error: ld returned 1 exit status`means some functions are defined in the .h, but not realized int .cpp file. 
`file format not recognized; treating as linker script` means `If you specify a linker input file which the linker can not recognize as an object file or an archive file, it will try to read the file as a linker script. If the file can not be parsed as a linker script, the linker will report an error.`
Btw, is uncertainty-driven PnP necessary to run the code?

**Comment by pengsida** [comment]
No.
This problem is caused by the format of `libceres.so`, which might have changed on your computer.

**Comment by DCC-lzhy** [comment]
`diameter.txt  // the object diameter, whose unit is meter` how to calculate the diameter?

**Comment by DCC-lzhy** [comment]
> No.
> This problem is caused by the format of `libceres.so`, which might have changed on your computer.

I download it again, but it failed again.Although it doesn't matter.

**Comment by pengsida** [comment]
> `diameter.txt // the object diameter, whose unit is meter` how to calculate the diameter?

https://github.com/zju3dv/clean-pvnet/issues/36
