### ISSUE TITLE
PVNet Retrained Scores

### ISSUE THREAD

**Issue by Anshul-Gupta24** [zju3dv/clean-pvnet#134]
Hi, I retrained PVNet for the cat, duck and holepuncher classes. I generated the render data for duck and holepuncher using the pvnet-rendering code. Here are my scores with uncertainty PnP at 240 epochs:

Cat
2d projections metric: 59.98
ADD metric: 17.10

Duck
2d projections metric: 59.68
ADD metric: 31.63

Holepuncher
2d projections metric: 71.04
ADD metric: 43.26

While the cat class scores are similar to the scores reported in the paper, I get higher scores for duck and holepuncher. Do you know the reason for this mismatch? Is it simply due to data or are there differences in code from the paper? Thanks!

**Comment by pengsida** [comment]
No, there is no difference in the code from the paper.
Such results are normal.
