### ISSUE TITLE
Selecting 2D Keypoints

### ISSUE THREAD

**Issue by mandywoo** [zju3dv/clean-pvnet#135]
Let's say I knew a bounding box of the object in the image, so I knew approximate where the object was in an image. Is there any way to confine the predicted 2d keypoints to be within this bounding box for more accurate pose predicitons?

**Comment by pengsida** [comment]
Crop the object with the bounding box.
This will improve the performance of object pose estimation.

**Comment by mandywoo** [comment]
What if from the estimated pose matrix, I need to calculate the correct camera location and rotation. If the image is cropped, would these values change?

**Comment by pengsida** [comment]
Estimate the keypoints and then map them to the coordinate system of original image.

**Comment by mandywoo** [comment]
I didn't think of that! Thank you!
