### ISSUE TITLE
some questions about uncertainty pnp

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/clean-pvnet#137]
Dear author:
I have notice that recently the work "Single-Stage 6D Object Pose Estimation" has proposed to integrate the RANSAC_based pnp into a network and combine it with PVNet to yield a single-stage framework. So I have some questions:

PVNet uses pnp, not RANSAC_based pnp , is it right?
I wonder to know if uncertainty pnp can be merged into the deep network?
I would appreciate it if you could reply.

**Comment by pengsida** [comment]
1. PVNet uses PnP, not Ransac-based PnP.
2. What do you mean by "merge PnP into the deep network". You could replace PnP with a deep network like "Single-Stage 6D Object Pose Estimation" or make PnP differentiable.

**Comment by zhuyazhi** [comment]
ok ~ I mean that replace PnP with a deep network like "Single-Stage 6D Object Pose Estimation" or make PnP differentiable.
and I wonder if uncertainty pnp could be differentiable and also use deep network to realize it.

**Comment by pengsida** [comment]
1. Uncertainty PnP can be made differentiable, but this is not trivial.
2. "Single-Stage 6D Object Pose Estimation" has replaced PnP with a network, which is able to handle the uncertainty of detected keypoints.

**Comment by zhuyazhi** [comment]
thanks for your reply~
