### ISSUE TITLE
关于训练的问题请教您

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/clean-pvnet#138]
您好，我想起来之前训练某个物体的模型200轮，然后测试训练到100轮的模型性能还是还好的，但是测试训练到150轮的模型性能比之前低，最终低到在测试集上四个指标下都是0.0的结果，不知道为什么会出现这种越往后训练性能降低的情况呢？而且会降到0.0，如果是过拟合应该不是这种准确率吧~
您能给我一些建议吗~

**Comment by pengsida** [comment]
在训练集上效果怎样。

**Comment by zhuyazhi** [comment]
损失一直降低，最后几十个epoch左右的loss都差不多~

**Comment by pengsida** [comment]
指标效果怎样。

**Comment by zhuyazhi** [comment]
因为我中途没有记录，所以没注意观察，我再试试，谢谢您的回复~
