### ISSUE TITLE
图片中是否有目标需要怎么判断？

### ISSUE THREAD

**Issue by rush9838465** [zju3dv/clean-pvnet#139]
感谢你们的工作，我在训练自己的数据集后推理时我希望能检测画面中是否有目标存在，通过mask似乎可以拿到bounding box。但是没有目标在画面中的时候9个keypoints和mask也是有的输出的，只是bounding box会非常大。是否可以通过用mask做一个阈值过滤（看代码视乎需要加softmax或者sigmoid），或者有什么其它思路呢？谢谢！

**Comment by pengsida** [comment]
可以用mask进行一个阈值过滤。
