### ISSUE TITLE
dpkg: error processing package docker-ce (--configure):

### ISSUE THREAD

**Issue by zhuqianqian-judy** [zju3dv/clean-pvnet#14]
![1](https://user-images.githubusercontent.com/40655640/72219113-5450ff80-357d-11ea-9e73-935339e91b65.png)
你好，这个是怎么回事。在网上搜了搜，还是没有解决。麻烦您看看，谢谢。

**Comment by pengsida** [comment]
你之前装docker-ce有问题。你看报错信息，会发现libglfw3已经装上了。

**Comment by zhuqianqian-judy** [comment]
如果不解决docker-ce这个问题，先直接按照Installation中的步骤进行，会有影响吗？

**Comment by pengsida** [comment]
不会。

**Comment by pengsida** [comment]
你试试就知道了。
