### ISSUE TITLE
some questions about the conda env

### ISSUE THREAD

**Issue by ghoshaw** [zju3dv/clean-pvnet#141]
Hi, I follows the readme and to create a conda env, it works ok until install requirements.  when this line is finshed, then the python can not run, and says " bash: /root/miniconda3/envs/pvnet/bin/python: Invalid argument"  . I create the env in a docker in centos7.

**Comment by pengsida** [comment]
It is a problem about conda.

**Comment by ghoshaw** [comment]
And how to solve this problem?
