### ISSUE TITLE
Question about the vote method

### ISSUE THREAD

**Issue by ghoshaw** [zju3dv/clean-pvnet#142]
Hi, Thanks for your sharing.
I have a question about the vote method in the paper.  Why is the vector-field? I mean if let the network learn the difference between coord and 2d point, then the RANSAC-based voting scheme is not necessary, and then the method can run a lot faster.  The prediction add the coord can lead to the 2d point in image.  Did you ever tried this way and found the result is worse?

**Comment by pengsida** [comment]
Yes.

**Comment by ghoshaw** [comment]
ok, thanks
