### ISSUE TITLE
編譯通過以後，無法使用un-pnp

### ISSUE THREAD

**Issue by qixxyy** [zju3dv/clean-pvnet#143]

**Comment by qixxyy** [comment]
from lib.csrc.uncertainty_pnp._ext import lib, ffi
ImportError: libspqr.so.2.0.2: cannot open shared object file: No such file or directory
總是出現這個錯誤

**Comment by pengsida** [comment]
要用ubuntu 16.04。

**Comment by WW-0** [comment]
> 要用ubuntu 16.04。

必须要16.04吗😂18.04试了好多方法还是有这个问题

**Comment by pengsida** [comment]
可以学习ceres，用适合ubuntu18.04的ceres编译。

**Comment by WW-0** [comment]
> 可以学习ceres，用适合ubuntu18.04的ceres编译。

好的，谢谢回答
