### ISSUE TITLE
libspqr.so.2.0.2 cannot open....

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/clean-pvnet#146]
hello, I have read the [issue](https://github.com/zju3dv/clean-pvnet/issues/116) about this error ,I also have libspqr.so.2.0.8,
but how can I recompile with libspqr.so.2.0.8?
because I didn't find the build under the lib/csrc/uncertainty_pnp
![image](https://user-images.githubusercontent.com/48109799/97857945-67fe6a00-1d39-11eb-8b1e-dc5b3b7cfca8.png)

thanks for your reply

**Comment by zhuyazhi** [comment]
![image](https://user-images.githubusercontent.com/48109799/97862597-92075a80-1d40-11eb-9859-24e4e0eff1eb.png)

**Comment by pengsida** [comment]
If you do not have a `build` directory, you do not need to remove it.

**Comment by zhuyazhi** [comment]
ok, thank you~
but I need to recompile it, right?
at the first time I do compile it in my environment with libspqr.so.2.0.8,
do you have some suggestions what  should I do ?

**Comment by pengsida** [comment]
You need to compile it.
You could follow https://github.com/zju3dv/clean-pvnet/issues/146

**Comment by zhuyazhi** [comment]
#146 is this issue
