### ISSUE TITLE
Questions about parameters on Tensorboard

### ISSUE THREAD

**Issue by JZhao12** [zju3dv/clean-pvnet#148]
Hi Sida

Currently, I am retraining the cat model on PVNet, and watching the training progress on Tensorboard. However, I don't understand some parameters on Tensorboard. I can show you my screenshot.
![PVNet_cat](https://user-images.githubusercontent.com/43590151/98383032-e1e96880-2043-11eb-8b2f-ad40d6fdf810.png)

I can understand most of them by reading your paper, for example, 'add' means average 3D distance of model points (ADD) metric, 'proj2d' means 2D Projection metric, but what does 'ap' and 'cmd5' mean? Where can I find the meaning of these parameters?

Also, if you don't mind, I would like to ask one more question, is my training curve correct?

Thank you so much!

**Comment by pengsida** [comment]
`ap` means the accuracy of predicted masks.
``cmd5` means 5 cm and 5 degree metric.
The training curves are correct.

**Comment by JZhao12** [comment]
Sida, thank you for your fast reply!
