### ISSUE TITLE
Issue with Docker Set Up

### ISSUE THREAD

**Issue by TheCharlesAshen** [zju3dv/clean-pvnet#149]
Hello, 
I followed the docker instructions and I encounter a problem with the GPU. I think this problem is because my OS is Windows and I have GTX 1070, the docker cannot access my GPU so I cannot use RANSAC for example..
Can someone help me or confirm if my theory is correct?

Thank you.

**Comment by pengsida** [comment]
You could google how to use docker with cuda.
