### ISSUE TITLE
Fatal IO error: client killed

### ISSUE THREAD

**Issue by tjdalsckd** [zju3dv/clean-pvnet#15]
I made Azure-kinect demo file. This file worked normally on my computer(Ubuntu 18.04, RTX 2080 Ti, CUDA 10.1)

https://hyu-my.sharepoint.com/:u:/g/personal/wdrac331_hanyang_ac_kr/EY7ODSE0DL5EoEK150cIW-IBAN71KNMlcMqjK1MP2kFdTw?e=82MTHR 

However, an error occurs 20 to 30 seconds after operation.
The following is the error information.

-------------------------------------------------------------------------------------------------------------------------------
   [xcb] Unknown request in queue while dequeuing
   [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
   [xcb] Aborting, sorry about that.
   python3: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion 
   `!xcb_xlib_unknown_req_in_deq' failed.
   : Fatal IO error: client killed
-------------------------------------------------------------------------------------------------------------------------------

Have you ever seen such an error?

**Comment by pengsida** [comment]
It does not seems like a problem related to pvnet.
I never used kinect, so I do not know.
