### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by DCC-lzhy** [zju3dv/clean-pvnet#151]
It's still me. I have another trouble when i read the lib.datasets.custom.pvnet.py.I can't understand `Dataset.__getitem__(self.index_tuple)`, why it's a tuple? `index, height, width = index_tuple`,where are height, width from? And self.img_ids is a number list.

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/samplers.py#L31
