### ISSUE TITLE
about training on the YCB-Video dataset

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/clean-pvnet#153]
Dear author, sorry to bother you again.
I have some questions which need your reply:
1. I don't know whether this code "clean-pvnet " could be used to train on the YCB-Video dataset, I know it is a far too big dataset, and I have read the [https://github.com/zju3dv/pvnet/issues/4](url)
2. Could you provide the YCB-Video dataset which has been processed by your scripts to us?
I really need to konw if it's possible that I use this code and the YCB-Video dataset with the same process as yours to do the comparison expriments, and I hope you to give me some advice. 
I would be appreciated if you give me a reply.
sincerely.

**Comment by pengsida** [comment]
1. The YCB-video dataset is too big, so I cannot send it to you.
2. I cannot find the codes for processing the YCB-video dataset.
