### ISSUE TITLE
RGB相機測試

### ISSUE THREAD

**Issue by emilychen6160** [zju3dv/clean-pvnet#154]
您好，請問訓練完成後有一般色彩相機的測試程式版本嗎？

**Comment by pengsida** [comment]
这个：https://github.com/zju3dv/clean-pvnet#testing-on-linemod

**Comment by emilychen6160** [comment]
謝謝，另外想請教您，我在您提供的pvnet還有clean-pvnet版本執行過程都會遇到這樣的問題：
ModuleNotFoundError: No module named 'lib.utils'
我使用的版本是:
python:3.6.7 
torch.version.cuda、Cuda compilation tools:10.0.130
不知道有沒有什麼解決方式呢？

**Comment by emilychen6160** [comment]
> 这个：https://github.com/zju3dv/clean-pvnet#testing-on-linemod

請問這是有包含即時視頻的部份嗎？

**Comment by pengsida** [comment]
不包括。实时视频的代码需要加一个detector，这个代码没有。

**Comment by emilychen6160** [comment]
您好，請問要訓練自己的資料集，這樣資料準備需要什麼規則嗎？
python3 run.py --type custom
Error: Only triangular faces are supported.
Number of face corners: 4

**Comment by pengsida** [comment]
输入的mesh要是三角形的，你可以根据代码报错看看问题在哪。
