### ISSUE TITLE
Windows Planform

### ISSUE THREAD

**Issue by DCC-lzhy** [zju3dv/clean-pvnet#157]
这个能在windows上跑吗，我在ubuntu上训练好了，我想在windows上做实际测试，但lib里的代码编译过不去，有没有好的推荐方法，谢谢作者。

**Comment by pengsida** [comment]
我看有人在windows上成功编译了。你只要解决编译错误就可以了吧。

**Comment by pengsida** [comment]
你可以试试docker。

**Comment by DCC-lzhy** [comment]
我试试
