### ISSUE TITLE
ransac voting vs ransac voting v3

### ISSUE THREAD

**Issue by darwinharianto** [zju3dv/clean-pvnet#158]
Hello, thanks for sharing.

I could run all the code perfectly on ubuntu machine with cuda. When I transfer the code to another hardware, it seems like ransac voting v3 is failing on calculation. It gives a weird number as result (keypoints outside images). When i tried to use ransac voting instead of ransac voting v3, it gives me a better result.
Can you tell me the difference between the two?
Is it better for me to try debug why ransac v3 doesnt work?

**Comment by pengsida** [comment]
The difference:
1. ransac voting: https://github.com/zju3dv/clean-pvnet/blob/master/lib/csrc/ransac_voting/ransac_voting_gpu.py#L87
2. ransac voting v3: https://github.com/zju3dv/clean-pvnet/blob/master/lib/csrc/ransac_voting/ransac_voting_gpu.py#L193

**Comment by Y1996-wwj** [comment]
您好，思达学长，我在复现您的clean-pvnet的时候碰到1个问题希望您能够解答。
就是我想可视化投票点在整张图像上的分布情况，请问应该在哪个文件里添加代码呢？
