### ISSUE TITLE
custom dataset problem

### ISSUE THREAD

**Issue by mimiggle** [zju3dv/clean-pvnet#159]
Hello, if I use the code you supply to train my model, the result show that bounding boxes are not at correct position.
Therefore, I want to ask some questions to you. 
1. I am curious about how the bounding boxes was draw in the visualization()
2. The difference between not only visualization() and evaluation()  but also green bounding box and blue bounding box
3. Is there any reason for uncertain training result?
![Screenshot from 2020-12-24 17-22-55](https://user-images.githubusercontent.com/76553444/103078499-f4782b00-460c-11eb-8ef9-cd5df471dcd1.png)

**Comment by pengsida** [comment]
1. https://github.com/zju3dv/clean-pvnet/blob/master/lib/visualizers/linemod/pvnet.py#L23
2. I do not know what you mean.
3. Maybe the data format is not correct.
