### ISSUE TITLE
OpenGL.error.NullFunctionError: Attempt to call an undefined function glCreateTextures, check for bool(glCreateTextures) before calling

### ISSUE THREAD

**Issue by zhuqianqian-judy** [zju3dv/clean-pvnet#16]
![1578985280(1)](https://user-images.githubusercontent.com/40655640/72321439-dc024f80-36de-11ea-9668-f9cc335e16c7.png)
你好，我执行这一步python run.py --type evaluate --cfg_file configs/linemod.yaml model cat test.icp True，出现OpenGL.error.NullFunctionError: Attempt to call an undefined function glCreateTextures, check for bool(glCreateTextures) before calling
这个是怎么回事?在网上搜了些方法试了也没好。麻烦你看看。

**Comment by pengsida** [comment]
python包版本问题。如果要用icp，必须要用我在requirements.txt里面指定的包版本。

**Comment by zhuqianqian-judy** [comment]
那就有点诡异了 就是requirements.txt的版本装的，都没改过。

**Comment by pengsida** [comment]
可能和显卡或驱动有关系。
https://github.com/DLR-RM/AugmentedAutoencoder/issues/1

**Comment by zhuqianqian-judy** [comment]
![Figure_1](https://user-images.githubusercontent.com/40655640/72322346-18cf4600-36e1-11ea-84a1-8aeb68bb1a61.png)
执行python run.py --type linemod cls_type cat

**Comment by pengsida** [comment]
model没放在正确的路径下。

**Comment by zhuqianqian-judy** [comment]
ROOT=/home/zqq/project/clean-pvnet-master1
model的路径：/home/zqq/project/clean-pvnet-master1/data/model/pvnet/cat/199.pth
是对的吧

**Comment by pengsida** [comment]
好像没问题，比较奇怪。
这种问题都是模型没加载正确。

**Comment by zhuqianqian-judy** [comment]
![1578988815(1)](https://user-images.githubusercontent.com/40655640/72324964-0eb04600-36e7-11ea-9f8f-5b35511d750e.png)
这个底下显示的数据有没有问题嘞？

**Comment by pengsida** [comment]
从mask ap上看说明你模型加载是对的。但pose有问题。
你数据是从哪里下的，可能是3d keypoints定义变了。

**Comment by zhuqianqian-judy** [comment]
行 我重新去下载数据 这个数据应该是我之前在其他链接下载的，我再看看

**Comment by zhuqianqian-judy** [comment]
Pretrained-Model是在你给的链接里。那三个数据集不是

**Comment by pengsida** [comment]
这个代码仓库下给的数据有处理好的数据。
