### ISSUE TITLE
clean-pvnet in google colab

### ISSUE THREAD

**Issue by KatCla** [zju3dv/clean-pvnet#160]
Dear author,

I am trying to install clean pvnet on google colab, because I don't have access to a nvidia gpu. Therefore, I changed the runtime settings in colab on "GPU" and started the installation. The issue is, that compiling the cuda extensions does not work for me.

Entering the following two lines gives an error: 

cd ../nn
python setup.py build_ext --inplace

The error I am getting is:

Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    cuda_include=os.path.join(os.environ.get('CUDA_HOME'), 'include')
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

How can I fix this error?
I would be thankful for any advice!

I attached the commands I am running so far for installation.
[musv0.txt](https://github.com/zju3dv/clean-pvnet/files/5742950/musv0.txt)

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/103153212-f0ddd300-47c9-11eb-980b-8d4cd9332a32.png)
