### ISSUE TITLE
about project_2d_sym

### ISSUE THREAD

**Issue by joyjoyzyz** [zju3dv/clean-pvnet#164]
hello, thanks for your sharing code.
I have read #130 , and modify the code lib/evaluators/linemod/pvnet.py, looks as follow:

    def projection_2d(self, pose_pred, pose_targets, K, icp=False, syn=False, threshold=5):
        model_2d_pred = pvnet_pose_utils.project(self.model, K, pose_pred)
        model_2d_targets = pvnet_pose_utils.project(self.model, K, pose_targets)
        #proj_mean_diff = np.mean(np.linalg.norm(model_2d_pred - model_2d_targets, axis=-1))
        
        if syn:
            idxs = nn_utils.find_nearest_point_idx(model_2d_pred, model_2d_targets)
            proj_mean_diff = np.mean(np.linalg.norm(model_2d_pred[idxs] - model_2d_targets, 2, 1))
        else:
            proj_mean_diff = np.mean(np.linalg.norm(model_2d_pred - model_2d_targets, axis=-1))
        
        if icp:
            self.icp_proj2d.append(proj_mean_diff < threshold)
        else:
            self.proj2d.append(proj_mean_diff < threshold)

I don't know if it's a right modification, because i got strange results 2d projections results  after evaluate on "eggbox" and "glue":
Occlusion_linemod eggbox：
2d projections metric: 0.8238297872340425
ADD metric: 0.44340425531914895
5 cm 5 degree metric: 0.007659574468085106
mask ap70: 0.5140425531914894

Occlusion_linemod glue：
2d projections metric: 0.8560354374307863
ADD metric: 0.4097452934662237
5 cm 5 degree metric: 0.20376522702104097
mask ap70: 0.6843853820598007
Could you add this part of code? because I want to use project_2d_sym() to evaluate on symmetric objects, like ADD metirc.
thanks in advance.

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet/blob/master/lib/utils/evaluation_utils.py#L83

**Comment by joyjoyzyz** [comment]
I have read it https://github.com/zju3dv/pvnet/blob/master/lib/utils/evaluation_utils.py#L83, and modified as it, but get strange  results, so I ask your advice, if my modification is right.

**Comment by pengsida** [comment]
Why do you say the results are strange?
