### ISSUE TITLE
Tensorboard of training

### ISSUE THREAD

**Issue by mimiggle** [zju3dv/clean-pvnet#166]
Hello, when I am training my own custom dataset, the curves of  'add', 'cmd5', and 'proj2d' are not correct. 
![1](https://user-images.githubusercontent.com/76553444/107877684-e4900f80-6f08-11eb-8fe4-68b72e5da34e.png)
when training, I got an UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. Is it possible the UserWarning cause the problem ,or there are other reasons? How can I fix it? 
What factors will affect the training process such 2d_keypoints, 3d_keypoints, and.ply, etc?  
Thank you in advance!

**Comment by pengsida** [comment]
when training, I got an UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. Is it possible the UserWarning cause the problem?

No

**Comment by mimiggle** [comment]
Thank you for your response!

This is the result of visualization. It seems that the ground truth BB is not correct in every angle.
![2](https://user-images.githubusercontent.com/76553444/107880613-ee227300-6f1a-11eb-9624-8566b490ee8b.png)
![4](https://user-images.githubusercontent.com/76553444/107880615-efec3680-6f1a-11eb-8463-119ff23666ac.png)

Will the camera parameters(camera.txt) affect the add and cmd in the training process? Dose it generate by the external parameters or quaternion？

**Comment by pengsida** [comment]
1. The ground-truth 2D keypoints are not correct. It may be caused by wrong camera parameters.
2. PVNet do not need depth information.

**Comment by mimiggle** [comment]
Thank you!
Therefore, the wrong ground-truth 2D keypoints may be caused by the wrong camera parameters. 
Is it the file of "camera.txt"? I use the parameters in the matrix of camera.txt  below.
fx  0  cx
0  fy  cy
0  0   1
I am curious that what are cx and cy ? Furthermore, the camera parameters may cause 'add', 'cmd5' curve not change from 0.0 , and 'proj2d' are not correct because 'add', 'cmd5' are too large to present the values?

**Comment by pengsida** [comment]
1. You probably need to learn the camera model.
2. The pose ie estimated based on the 2d keypoints. If the keypoints are wrong, the object pose will be wrong.

**Comment by mimiggle** [comment]
Thank you.
Whether the format to represent the camera parameters could affect the result of 2d keypoints? (For example, '234.000000e+00' and '2.340000e+02')
In the custom dataset, all pictures may be training and testing. How can I assign and make my testing dataset with different pictures?

**Comment by pengsida** [comment]
1. I am not sure.
2. You could follow the Linemod dataset.
3. I did not separate the training and validation data.

**Comment by mimiggle** [comment]
After I read my camera model in the tool I use to synthesize the dataset and revise the parameters' format, the 2d keypoints bounding box is more correct and the curve of 2dproj is better. Thank you so much! 

However, the 'add', 'cmd5' are still always 0.0. Is there any reason to cause this result? Is their values too large to be change or too small to present the number?

Does the testing dataset of using pictures generate by ourselves need rgb, mask ,and pose? How can we make testing in the real-time demo?

**Comment by pengsida** [comment]
1. Maybe the ground-truth is still wrong.
2. Real-time demo does not require ground-truth masks and poses.

**Comment by mimiggle** [comment]
Sorry to bother you.
This is a part of my training result now. ( 'Yellow'  is ground-ruth ; 'Purple' is bounding box )
![001](https://user-images.githubusercontent.com/76553444/108471729-c63e6100-72c6-11eb-95c5-5c3c536396ce.png)
![002](https://user-images.githubusercontent.com/76553444/108471730-c6d6f780-72c6-11eb-92a0-940c74e6ae61.png)
It seems that the ground-truth has better position and rotation. However, maybe it still has some problem I did'n find. Is there any solution to make the training result more correct?

**Comment by pengsida** [comment]
You need to make the ground-truth correct.

**Comment by cgm6666** [comment]
> 抱歉打扰你。
> 这是我现在训练结果的一部分。（“黄色”是真实边界框，“紫色”是预测边界框） 这是结果的训练曲线。 地面真相似乎具有更好的位置和旋转度。但是，也许它仍然有我找不到的问题。有什么解决方案可以使训练结果更正确？
> ![001](https://user-images.githubusercontent.com/76553444/108471729-c63e6100-72c6-11eb-95c5-5c3c536396ce.png)
> ![002](https://user-images.githubusercontent.com/76553444/108471730-c6d6f780-72c6-11eb-92a0-940c74e6ae61.png)
> 
> ![2](https://user-images.githubusercontent.com/76553444/108475697-03592200-72cc-11eb-9126-38ad5d8aa025.png)

Hi, how did you solve this question?

**Comment by mimiggle** [comment]
> Hi, how did you solve this question?

Hello, I haven't solved this problem. My 'add' and 'cmd5' are always 0. 
Do you use the tool "Unreal Engine" to generate the dataset?I think the reason may be that Unreal Engine is left-hand coordination and .ply model is right-hand coordination, so the sequence of points in corner_gt which is projected by the pose_gt, camera value, and corner_3d is not correct although it looks good.
Do you solve the problem? Can you share with me?
You can type with Chinese. I am a Chinese user, too.

**Comment by cgm6666** [comment]
> > 嗨，你是怎么解决这个问题的？
> 
> 你好，我还没解决这个问题。我的"添加"和"cmd5"始终为0。
> 您是否使用工具"虚幻引擎"生成数据集？我认为原因可能是虚幻引擎是左手协调和.ply模型是右手协调，所以在corner_gt点的顺序，这是由pose_gt投影，相机值和corner_3d是不正确的，虽然它看起来不错。
> 你解决问题了吗？你能和我分享吗？
> 你可以用中文打字。我也是中国用户。

我是使用的作者提供的工具包进行的数据集制作，我的问题出现在pytorch版本上，改为1.1.0就恢复了正常

**Comment by mimiggle** [comment]
請問是用這個數據包嗎？https://github.com/DLR-RM/BlenderProc

**Comment by cgm6666** [comment]
> 請問有這個數據的嗎？https://github.com/DLR-RM/BlenderProc

Create a dataset using https://github.com/F2Wang/ObjectDatasetTools

**Comment by mimiggle** [comment]
這個有需要使用深度相機嗎？還是一般RGB相機就可以了

**Comment by chengm0-0** [comment]
> 這個有需要使用深度相機嗎？還是一般RGB相機就可以了

是的，我使用的是realsense D435i相机，我认为需要根据深度信息进行位姿解算

**Comment by mimiggle** [comment]
我目前使用的pytorch版本是1.3.0+cu100
但是用Unreal 去產生只有彩度資訊的合成資料集，想說是否有辦法可以不要同時使用深度進行資料蒐集？

**Comment by chengm0-0** [comment]
> 我目前使用的pytorch版本是1.3.0+cu100
> 但是用Unreal 去產生只有彩度資訊的合成資料集，想說是否有辦法可以不要同時使用深度進行資料蒐集？

这个我也不太清楚了，我也是刚接触，目前仅使用深度相机做了测试

**Comment by mimiggle** [comment]
謝謝，另外想請教您用的方法是否需另外準備要辨識物件的實際模型，還是使用電腦模型檔即可實踐？

**Comment by chengm0-0** [comment]
> 謝謝，另外想請教您用的方法是否需另外準備要辨識物件的實際模型，還是使用電腦模型檔即可實踐？

我没有准确的电脑模型，是在实际模型下进行的拍摄计算。

**Comment by LEONHWH** [comment]
> > 這個有需要使用深度相機嗎？還是一般RGB相機就可以了
> 
> 是的，我使用的是realsense D435i相机，我认为需要根据深度信息进行位姿解算

你好，我也是打算使用 https://github.com/F2Wang/ObjectDatasetTools去建立数据集去训练，但遇到一个比较尴尬的问题是我目前使用的深度相机kinect2，它的分辨率是1920×1080（16：9），低精度下是960×640 他的分辨率无法满足训练pvnet所用的640×480（即4：3）。因为训练pvnet需要提供内参的，我无法轻易在kinect2上得到对应640×480分辨率的相机内参、深度图以及RGB图。

请问你使用的realsense D435i拍出来的深度和rgb图分辨率是多大，有遇到这种问题该怎么解决？是使用resize去做吗？

**Comment by monajalal** [comment]
@mimiggle  did you create the foot dataset using the BlenderProc? Could you please share your script and/or how does your ls in data dir look like?
