### ISSUE TITLE
tensorboard issue

### ISSUE THREAD

**Issue by cgm6666** [zju3dv/clean-pvnet#169]
Hi, I have tried to train my dataset with your code, but after 9 epochs, I found that my "add" and "cmd5" and "proj2d" is always 0.0, and my "ap" is always 1.0. Would this cause the failure in the future? Thanks:)
And my modle.ply is not very precise, Did this casue the problem?

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/issues/166

**Comment by cgm6666** [comment]
> #166

是的我看到了这个回复,但是我的相机参数是正确的,很不解为什么会出现这样的答案,是和我的自制模型不精确有关系吗,谢谢:)

**Comment by cgm6666** [comment]
当我使用python run.py --type visualize --cfg_file configs/custom.yaml时,图片中并没有显示出6D位姿,请问是什么原因呢?非常感谢!

**Comment by cgm6666** [comment]
下面是我输出的一个polygon的坐标,很奇怪会出现-值,希望能得到你的解答,非常感谢!
[[  221.84084215  -738.53691039]
 [  222.29687283 -1296.37833035]
 [  532.88726139 -1160.60775665]
 [  463.79937096  -672.23567766]
 [  221.84084215  -738.53691039]
 [  226.23038488  -870.08283011]
 [  525.217265    -776.5382191 ]
 [  463.79937096  -672.23567766]]

**Comment by pengsida** [comment]
我不知道你数据的情况，可能是相机参数有问题。

**Comment by cgm6666** [comment]
有没有可能是我训练的代数太少导致数据十分奇怪?我刚刚训练了9 epoch,因为训练的比较慢.

**Comment by pengsida** [comment]
建议你看一下训练数据的gt对不对。

**Comment by cgm6666** [comment]
请问训练数据的gt从哪里看呢?我在使用你提供的方法制作数据集时最后进行了可视化,数据集的3d box是没问题的.

**Comment by cgm6666** [comment]
我发现在数据中生成的train.json文件中"cls"为cat,请问这个会有影响吗

**Comment by cgm6666** [comment]
会不会和我的pytorch版本有关系?我目前是使用的pytorch0.4.1,但是在dcn_v2是使用pytorch1.1.0编译的,因为使用0.4.1版本会出现error,在ransac_voting,nn,fps都是使用0.4.1编译的

**Comment by cgm6666** [comment]
我感觉应该是我的gt有问题,因为我在visialize的时候发现两个三维box均未绘制,请问gt和什么有关系呢?
我之前数据集生成的pose.npy是4*4的,我看最后一行是0,0,0,1,就把最后一行删去了,这个应该不会影响吧?

**Comment by cgm6666** [comment]
我发现错误出现在了train.json中,我的corner_2d,center_2d,fps_2d三个numpy的第二个参数(应该是y)全部都是负数,请问你知道这是由于什么原因造成的吗?非常感谢您的细心解答!

**Comment by cgm6666** [comment]
下面是我在用工具包制作数据集时产生的相机参数:
{"fx": 608.4978637695312, "fy": 608.1328125, "ppx": 322.1357421875, "ppy": 238.8262481689453, "height": 480, "width": 640, "depth_scale": 0.0010000000474974513}
所以在camera.txt,我使用了如下的参数:
6.084978637695312000e+02 0.000000000000000000e+00 3.221357421875000000e+02
0.000000000000000000e+00 6.081328125000000000e+02 2.388262481689453000e+02
0.000000000000000000e+00 0.000000000000000000e+00 1.000000000000000000e+00

**Comment by cgm6666** [comment]
我找到了问题所在,问题在pose.npy的获取上,我使用您提供的方法进行数据集的制作,发现会产生两个文件,其中一个是transform.npy,一个是transform文件夹下图片名称(i).npy,我不知道该怎么和您的方法的pose文件使用相同,希望得到解答,非常感谢.

**Comment by pengsida** [comment]
我没用过ObjectDatasetTools。

**Comment by cgm6666** [comment]
非常感谢您的细心解答,我应该找到了问题所在,正在重新训练模型,期待得到好的结果.

**Comment by cgm6666** [comment]
我想知道这个模型大约运行多少epoch后收敛,我现在运行了9epoch,生成了两个模型,但是运行visialize程序效果很糟糕,预测的box坐标很多在几千,这种情况正常吗?

**Comment by QRayMoor** [comment]
@chengm0-0  Please ask how do you use objectdatasettools to make a dataset for pvnet training，
and I want to make pose annotations from keypoints for PVNet. This PVNet needs dataset formed like this:
├── /path/to/dataset
│ ├── model.ply
│ ├── camera.txt
│ ├── rgb/
│ │ ├── 0.jpg
│ │ ├── ...
│ │ ├── 1234.jpg
│ │ ├── ...
│ ├── mask/
│ │ ├── 0.png
│ │ ├── ...
│ │ ├── 1234.png
│ │ ├── ...
│ ├── pose/
│ │ ├── 0.npy
│ │ ├── ...
│ │ ├── 1234.npy
│ │ ├── ...
│ │ └──

Each .npy file contains transoframtion matrix 3x4 (not 4x4). What it can be ?
For example file "pose0.npy" for category "cat" looks like this:
array([[ 0.0950661 , 0.983309 , -0.155129 , 0.0717302 ],
[ 0.741596 , -0.173913 , -0.647911 , -0.14907229],
[-0.664076 , -0.0534489 , -0.745752 , 1.0606388 ]],
dtype=float32)

Were you able to use this repository to create a custom dataset for PVnet successfully ?
