### ISSUE TITLE
Sorry, i want to ask some questions about custom data 

### ISSUE THREAD

**Issue by kevin860213** [zju3dv/clean-pvnet#17]
I saw your command which is like this
python run.py --type evaluate --cfg_file configs/linemod.yaml train.dataset CustomTrain test.dataset CustomTrain model mycat
On your custom object, you alaways use the CustomTrain  on the train.dataset and test.dataset.Does it mean that you use the same data on traning and testing? Thanks you.

**Comment by pengsida** [comment]
Yes.
For the custom dataset, you can define your own dataset for training and testing.

**Comment by kevin860213** [comment]
OK. But , i followed your tutorial on prepare the dataset.
python run.py --type custom
Do you know does there have a fast way to prepare the test data? 
Thanks.

**Comment by pengsida** [comment]
Look into the code and you will know.
Register your own dataset at `dataset_catalog.py`, as described at https://github.com/zju3dv/clean-pvnet/blob/master/project_structure.md#dataset
