### ISSUE TITLE
problem when run pvnet_docker

### ISSUE THREAD

**Issue by Yan-Xiaodi** [zju3dv/clean-pvnet#172]
Hello, I fellow the way to set up environment with docker,Everything was right.
but when I run with comman 'pvnet_docker' ,it turn out with an erro:
```
starting pvnet docker
non-network local connections being added to access control list
docker: unknown server OS: .
See 'docker run --help'.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/pvnet_dev/json: dial unix /var/run/docker.sock: connect: permission denied
```
I thought is was the root problem,so I Enter root permission，it was not work:
```
root@yanxiaodi-System:/home/yanxiaodi/Pytorch/Pvnet/clean-pvnet/docker# pvnet_docker
pvnet_docker：未找到命令
```
I have searched this problem in google ,but cannot find the correct way to solve this,also I tried to delet the docker and install it again ,but is not work.
here is the docker images  infomation:
```
REPOSITORY    TAG                     IMAGE ID       CREATED          SIZE
pvnet_clean   latest                  d0d61e96d82f   28 minutes ago   5.99GB
nvidia/cuda   9.0-devel-ubuntu16.04   0fc4f44baefe   2 weeks ago      1.82GB
hello-world   latest                  d1165f221234   2 months ago     13.3kB
```
I use the latest docker version.
Can someone help me to fix this problem?I just want to konw why I can't use the docker

**Comment by pengsida** [comment]
It is a docker problem, not about the code.

**Comment by Yan-Xiaodi** [comment]
@pengsida Thanks for your response,I will try another way to set the environment,but I dont konw what's the problem with docker, is the version not Match or any other problem

**Comment by pengsida** [comment]
I am not sure.

**Comment by Yan-Xiaodi** [comment]
it does'n mater,I have  set up the environment and run the demo successfully,it's a great work!Thanks

**Comment by yangfei4** [comment]
> it does'n mater,I have set up the environment and run the demo successfully,it's a great work!Thanks

Hi, how did you resolve the issue?
