### ISSUE TITLE
What should we get as output?

### ISSUE THREAD

**Issue by jfemiani** [zju3dv/clean-pvnet#174]
What values will indicate that things are working correctly?

For example, are these numbers indicating correct results?
Compared to the reported results on 'cat' in the paper, they seem to be slightly better  for ADD and worse 2d projections.  Is this expected based on the latest model/configuration on github?

**Testing with Uncertainty Driven PnP**
```
python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat test.un_pnp True
```
> 2d projections metric: 0.9970059880239521
> ADD metric: 0.7894211576846307
> 5 cm 5 degree metric: 0.9860279441117764
>  mask ap70: 0.9960079840319361

```
python run.py --type evaluate --cfg_file configs/linemod.yaml test.dataset LinemodOccTest model cat cls_type cat test.un_pnp 
```
> 2d projections metric: 0.6343723673125526
> ADD metric: 0.18534119629317608
> 5 cm 5 degree metric: 0.18534119629317608
> mask ap70: 0.6731255265374895

**Comment by pengsida** [comment]
Yes, these numbers indicate correct results.

**Comment by 1230678** [comment]
您好，我在使用un_pnp进行测试时遇到了zero-dimensional arrays cannot be concatenated这个错误，请问您有遇到吗，求教该如何解决
