### ISSUE TITLE
Real-time demo

### ISSUE THREAD

**Issue by Hudson1996** [zju3dv/clean-pvnet#175]
非常感谢您对pvnet的分享！
我想实现您在Real-time demo中调用摄像头来实现对目标物体的估计，您有公布这部分代码的计划吗？
还有关于这个demo部分，python run.py --type demo --cfg_file configs/linemod.yaml demo_path demo_images/cat，就只是检测数据集中的图片吗？

**Comment by pengsida** [comment]
现在没有摄像头让我调试这个代码，建议自己修改demo代码来实现real-time demo。

**Comment by Hudson1996** [comment]
您好，demo_images/cat/meta.npy该文件是如何生成的呢？

**Comment by pengsida** [comment]
用numpy把相关数据存成npy文件。

**Comment by Hudson1996** [comment]
感谢您的回答，我读取了一下meta.npy的内容，这里的"kpt_3d","corner_3d","K"具体是哪一部分的代码生成的呢？

{'kpt_3d': array([[ 0.02178441, -0.05869994, -0.0414618 ],
       [-0.02093567,  0.0655842 ,  0.03955495],
       [ 0.02779895,  0.02978627, -0.04446336],
       [ 0.00139469, -0.05708839,  0.03459186],
       [ 0.01266971,  0.01578414,  0.07163165],
       [-0.032556  , -0.03509996, -0.04010978],
       [-0.02941702,  0.02281759, -0.03967477],
       [ 0.02389689,  0.04313551,  0.03052332],
       [-0.0002315 ,  0.0020155 ,  0.0132825 ]]), 'corner_3d': [[-0.033737, -0.061801, -0.045446], [-0.033737, -0.061801, 0.072011], [-0.033737, 0.065832, -0.045446], [-0.033737, 0.065832, 0.072011], [0.033274, -0.061801, -0.045446], [0.033274, -0.061801, 0.072011], [0.033274, 0.065832, -0.045446], [0.033274, 0.065832, 0.072011]], 'K': [[572.4114, 0.0, 325.2611], [0.0, 573.57043, 242.04899], [0.0, 0.0, 1.0]]}

**Comment by pengsida** [comment]
kpt_3d和corner_3d是物体关键点和3D bounding box的corner points，K是相机内参。
建议你根据自己的物体模型和相机生成这些参数。

**Comment by BoBoINVIDICUS** [comment]
> kpt_3d和corner_3d是物体关键点和3D bounding box的corner points，K是相机内参。 建议你根据自己的物体模型和相机生成这些参数。

作者您好，最近在使用您得PVnet，发现除了cat,其他物体都没有meta.npy这个文件，如果自己生成这些文件的话，K是替换为自己的相机的内参吗？

**Comment by BoBoINVIDICUS** [comment]
> 感谢您的回答，我读取了一下meta.npy的内容，这里的"kpt_3d","corner_3d","K"具体是哪一部分的代码生成的呢？
> 
> {'kpt_3d': array([[ 0.02178441, -0.05869994, -0.0414618 ], [-0.02093567, 0.0655842 , 0.03955495], [ 0.02779895, 0.02978627, -0.04446336], [ 0.00139469, -0.05708839, 0.03459186], [ 0.01266971, 0.01578414, 0.07163165], [-0.032556 , -0.03509996, -0.04010978], [-0.02941702, 0.02281759, -0.03967477], [ 0.02389689, 0.04313551, 0.03052332], [-0.0002315 , 0.0020155 , 0.0132825 ]]), 'corner_3d': [[-0.033737, -0.061801, -0.045446], [-0.033737, -0.061801, 0.072011], [-0.033737, 0.065832, -0.045446], [-0.033737, 0.065832, 0.072011], [0.033274, -0.061801, -0.045446], [0.033274, -0.061801, 0.072011], [0.033274, 0.065832, -0.045446], [0.033274, 0.065832, 0.072011]], 'K': [[572.4114, 0.0, 325.2611], [0.0, 573.57043, 242.04899], [0.0, 0.0, 1.0]]}

您好，请问您知道如何制作meta.npy这个文件了吗？如果可以，希望您可以指点一下。

**Comment by BoBoINVIDICUS** [comment]
> corner points

您好，kpt_3d是通过什么获取的呢？
