### ISSUE TITLE
 How to find correspondence between 2d keypoints and 3d keypoints

### ISSUE THREAD

**Issue by hkd724** [zju3dv/clean-pvnet#176]
你好，
          有幸拜读你的论文，但是对文中列举的2d-3d对应关系不甚了解。文中提到2d的keypoints可以用像素的向量投票决定，3d keypoints 可以由 farthest point sampling确定。但是这些2d、3d的keypoint好像没有联系，没有建立一对一的匹配呢？这个配对关系是可以根据cad模型直接得出还是需要用其他算法判断呢？
感谢！

**Comment by pengsida** [comment]
3d关键点是预先定义好的，2d关键点是3d关键点的投影。网络输出的2d关键点是可以知道顺序的。

**Comment by hkd724** [comment]
> 3d关键点是预先定义好的，2d关键点是3d关键点的投影。网络输出的2d关键点是可以知道顺序的。

谢谢解答。

我可以这样理解吗。我们通过模型事先规定好哪些3d点是我们要找的。我们训练好的网络是为了找规定好的3d点对应的2d点，网络好坏的标准就是找到这些对应的2d点准确与否？

**Comment by hkd724** [comment]
> > 3d关键点是预先定义好的，2d关键点是3d关键点的投影。网络输出的2d关键点是可以知道顺序的。
> 
> 谢谢解答。
> 
> 我可以这样理解吗。我们通过模型事先规定好哪些3d点是我们要找的。我们训练好的网络是为了找规定好的3d点对应的2d点，网络好坏的标准就是找到这些对应的2d点准确与否？

那我是不是可以这样理解，ply模型只在训练的时候起作用。当在线判断6dof pose的时候是不需要读取ply模型来计算的

**Comment by pengsida** [comment]
可以这么理解。

**Comment by hkd724** [comment]
> 可以这么理解。

感谢解答～
