### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by nickhward** [zju3dv/clean-pvnet#178]
My training time is very slow. It's showing 1 hour and 30 minutes per epoch if I run at batch size 16, and 30 minutes per epoch if I run at batch size 2. I'm using a GeForce GTX 1080 Ti GPU, CUDA 10.2, and torch version 1.5.0.  It took 16 hours to reach 35 epochs for me. 

Are there any ways I could speed up the training?

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/issues/101

**Comment by nickhward** [comment]
I've tried using cuda 9.0 with torch version 0.4.1 and it didn't work. I kept getting the error that "<torch/extension.h>" was not found when I recompiled.

**Comment by pengsida** [comment]
It sounds strange, since others can compile the code with torch 0.4.1.

**Comment by nickhward** [comment]
(pvnet) nicholasward2@nicholasward2-Alienware-Aurora-R7:~/clean-pvnet/lib/csrc/dcn_v2$ python setup.py build_ext --inplace
running build_ext
building '_ext' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/home
creating build/temp.linux-x86_64-3.7/home/nicholasward2
creating build/temp.linux-x86_64-3.7/home/nicholasward2/clean-pvnet
creating build/temp.linux-x86_64-3.7/home/nicholasward2/clean-pvnet/lib
creating build/temp.linux-x86_64-3.7/home/nicholasward2/clean-pvnet/lib/csrc
creating build/temp.linux-x86_64-3.7/home/nicholasward2/clean-pvnet/lib/csrc/dcn_v2
creating build/temp.linux-x86_64-3.7/home/nicholasward2/clean-pvnet/lib/csrc/dcn_v2/src
creating build/temp.linux-x86_64-3.7/home/nicholasward2/clean-pvnet/lib/csrc/dcn_v2/src/cpu
creating build/temp.linux-x86_64-3.7/home/nicholasward2/clean-pvnet/lib/csrc/dcn_v2/src/cuda
gcc -pthread -B /home/nicholasward2/anaconda3/envs/pvnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/nicholasward2/clean-pvnet/lib/csrc/dcn_v2/src -I/home/nicholasward2/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/lib/include -I/home/nicholasward2/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/lib/include/TH -I/home/nicholasward2/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/nicholasward2/anaconda3/envs/pvnet/include/python3.7m -c /home/nicholasward2/clean-pvnet/lib/csrc/dcn_v2/src/vision.cpp -o build/temp.linux-x86_64-3.7/home/nicholasward2/clean-pvnet/lib/csrc/dcn_v2/src/vision.o -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/nicholasward2/clean-pvnet/lib/csrc/dcn_v2/src/dcn_v2.h:3:0,
                 from /home/nicholasward2/clean-pvnet/lib/csrc/dcn_v2/src/vision.cpp:2:
/home/nicholasward2/clean-pvnet/lib/csrc/dcn_v2/src/cpu/vision.h:2:29: fatal error: torch/extension.h: No such file or directory
 #include <torch/extension.h>
                             ^
compilation terminated.
error: command 'gcc' failed with exit status 1

This is my exact error. I've tried multiple different ways of installing torch 0.4.1. How did you install it if you don't mind me asking. I can't seem to figure out why I can't get rid of this error.

**Comment by pengsida** [comment]
The code does not require dcn_v2.

**Comment by nickhward** [comment]
Thank you very much for your fast responses! It now takes 15 minutes per epoch.

**Comment by Y1996-wwj** [comment]
> 非常感谢您的快速回复！现在时代需要 15 分钟。

请问您最终用的是torch0.4.1和cuda9.0吗
