### ISSUE TITLE
Training 

### ISSUE THREAD

**Issue by nickhward** [zju3dv/clean-pvnet#179]
Why am I getting 0 values for ADD, cmd5, and proj2d (trained on Linemod, to create a model for cat)? I can't seem to figure out my problem? I changed from pytorch 1.1 to 0.4.1, and now I'm not seeing any values for those. I double checked and when I can compile dcn_v2, I have no issues with training. But I get a torch/extenstions.h missing error when I try to compile with torch 0.4.1. Any suggestions would be very helpful. Thank you.

Here are my TensorBoard graphs:
![image](https://user-images.githubusercontent.com/78880630/128056867-0e8a8b0a-6432-4fd6-a44d-7a5062857aac.png)

**Comment by pengsida** [comment]
Looks strange.
Did you use the provided data in this repository?
