### ISSUE TITLE
Custom Dataset Pose Format

### ISSUE THREAD

**Issue by neighthan** [zju3dv/clean-pvnet#18]
From the example custom dataset, I see that for each image you need to have a 3x4 matrix with the pose saved in a numpy array. E.g. one of these arrays has the pose

```
[ -0.857243  ,  0.376382  , -0.351385  , -0.06970996],
[  0.499056  ,  0.775362  , -0.386984  , -0.0512582 ],
[  0.126797  , -0.5071      , -0.852509  ,  0.746117  ]
```

What is the format of this pose matrix (i.e. what does each of the entries mean)?

**Comment by neighthan** [comment]
Ah, if we represent this as

```
[a, b, c, d]
[e, f, g, h]
[i, j, k, l]
```

then we have that `[d, h, l]` is the translation (in x, y, z) and the rest is the rotation matrix with `a`, `f`, and `k` multiplied by any scaling (in x, y, z)?

**Comment by pengsida** [comment]
pose: [R; t]
rotation:
```
[a, b, c]
[e, f, g]
[i, j, k]
```
translation: `[d, h, l]`

**Comment by darwinharianto** [comment]
Sorry to bump the post.

Can you please explain what that pose mean?
Is that pose relative to model.ply?

**Comment by pengsida** [comment]
Yes.
Pose means 6dof object pose.

**Comment by darwinharianto** [comment]
Is this correct?
If I multiply model.ply with the pose annotation, I will get current pose in the given image?

**Comment by pengsida** [comment]
What do you mean by "get current pose in the given image relative to camera"?

**Comment by darwinharianto** [comment]
Currently I am confused on pose matrix. Is it relative to camera frame or world frame. 
Suppose I have a standing up can as my model.ply, If the dcm looks like this
[1.0000000,  0.0000000,  0.0000000, 1
   0.0000000,  0.0000000, -1.0000000,1
   0.0000000,  1.0000000,  0.0000000, 2]

will this mean from camera it would be 1 meter to the right, 1 meter below with 2 meter depth?
From camera, can's orientation would be rotated 90 degree (lying down, but in world it could be standing straight).
Am I right?

**Comment by pengsida** [comment]
The object pose is relative to the camera frame.
