### ISSUE TITLE
Have you made changes in the original LINEMOD and Oculusion LINEMOD datasets for this project?

### ISSUE THREAD

**Issue by faheemullah** [zju3dv/clean-pvnet#180]
Hi! its just a question. What changes have you made in these datasets? Does original datasets stores the bounding box corners coordinates as keypoints? And you specified there other 3D keypoints on the surface of the 3D models in the datasets? Did you do that manually? And then Farthest Point Sampling (FPS) finds 3D keypoints on runtime? What helps in finding 2D keypoints in the segmented images?

**Comment by pengsida** [comment]
1. We did not make changes to the original dataset.
2. We generated 3D keypoints using the Farthest Point Sampling algorithm.
