### ISSUE TITLE
关于ransac_voting_kernel.cu参数的一些问题

### ISSUE THREAD

**Issue by Xenos24R** [zju3dv/clean-pvnet#181]
您好，我在阅读ransac_voting_kernel.cu文件时遇到了一些问题，请问代码中的tn，vn，hn代表的都是什么呢？

**Comment by pengsida** [comment]
They are dimensions of inliers: https://github.com/zju3dv/clean-pvnet/blob/master/lib/csrc/ransac_voting/src/ransac_voting_kernel.cu#L273

**Comment by Xenos24R** [comment]
Thank you for your reply, I mean I want to know what they really mean, for example: does tn represent feature points?vn represent the vector?
Thank you again for your contribution to this project.

**Comment by pengsida** [comment]
They are shape dimensions.

**Comment by Xenos24R** [comment]
Does vertex represent feature points?

**Comment by pengsida** [comment]
What vertex?

**Comment by Xenos24R** [comment]
The parameter in ransac_voting_layer_v5

**Comment by pengsida** [comment]
It is the vector field.

**Comment by Xenos24R** [comment]
Thank you for your reply
