### ISSUE TITLE
About the TruncationLinemod

### ISSUE THREAD

**Issue by JiChun-Wang** [zju3dv/clean-pvnet#185]
How can I get the respective depth images according to your supplied information?

**Comment by pengsida** [comment]
There is no depth information in the TruncationeLinemod dataset.

**Comment by QRayMoor** [comment]
请问TruncationeLinemod数据集没有json文件，如何进行测试？同时lib/datasets/dataset_catalog.py里没有LinemodtrunTest，需要自己写吗？json文件缺失如何处理，希望解答，谢谢谢谢 @pengsida @JiChun-Wang
