### ISSUE TITLE
Ahout the TruncationLINEMOD dataset

### ISSUE THREAD

**Issue by JiChun-Wang** [zju3dv/clean-pvnet#186]
Hi, so sorry for bothering you again.
Actually I want to consult you about how you get the truncated version from the original linemod dataset and I want to get the depth images following your pipeline.
I think the cropping process from an original 640*480 color image  to a 256*256 one don't contain any scaling operation but only select a fixed size window, is that right?

**Comment by pengsida** [comment]
Yes.

**Comment by QRayMoor** [comment]
@JiChun-Wang 请问TruncationLINEMOD数据集如何测试？测试指令和代码没有在项目里看到，请您指点。另外，请问论文中的语义分割图和向量场图如何生成
