### ISSUE TITLE
TLESS Problem when testing

### ISSUE THREAD

**Issue by KAOeric** [zju3dv/clean-pvnet#187]
I hope to reproduce this project but when I run the command 
**
python run.py --type evaluate --cfg_file configs/tless/tless_01.yaml
**
it got some wrong with 
cv2.error: OpenCV(3.4.2) /io/opencv/modules/imgproc/src/imgwarp.cpp:2610: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'warpAffine'
How can i solve it ?   Thanks!!

**Comment by Chrisspf** [comment]
Download tless test dataset from http://cmp.felk.cvut.cz/t-less/download.html. 
The error may be caused by not finding the test datasets.
