### ISSUE TITLE
TLESS Visuzlize Problem

### ISSUE THREAD

**Issue by KAOeric** [zju3dv/clean-pvnet#190]
![圖片2](https://user-images.githubusercontent.com/36849812/142591374-450645fe-8c76-433c-b24a-58d1d419340b.png)
When I Continue to training and visualize the data about tless_01, it cause the problem just like the picture
How can i solve it?

**Comment by pengsida** [comment]
It seems that the ground-truth is not correct.

**Comment by KAOeric** [comment]
Sorry, But I train and predict the model with the code that you share, and I use the pretrain model. How can I solve this problem?
I didn't know whether I can adjust

**Comment by pengsida** [comment]
Check if your data format is correct.

**Comment by KAOeric** [comment]
The data format is follow by that you share on the website

**Comment by pengsida** [comment]
I did not encounter this problem. Please check the details by yourself.
