### ISSUE TITLE
关于ransac_voting_layer_v3代码的问题

### ISSUE THREAD

**Issue by MaxShi007** [zju3dv/clean-pvnet#191]
你好，我正在尝试理解并复现您的论文，在阅读ransac_voting_layer_v3这个代码时无法理解从176行到196行的代码，请问您的这段代码的作用是什么呢https://github.com/zju3dv/clean-pvnet/blob/5870c509e3cc205e1bb28910a7b1a9a3c8add9a8/lib/csrc/ransac_voting/ransac_voting_gpu.py#L176

我尝试注释掉176行之后的代码，发现测试结果有明显下降，其中ADD metric下降最明显。根据我的理解在176行之前的代码已经完成了ransac并得到关键点（batch_win_pts）所以并不能理解176行之后代码的作用

很抱歉问您一些比较简单的问题，谢谢

**Comment by pengsida** [comment]
使用inliler voting重新算一次关键点。

**Comment by MaxShi007** [comment]
那么请问normal，b，ATA，ATb分别代表什么呢

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet/issues/54

**Comment by MaxShi007** [comment]
明白了，非常感谢
