### ISSUE TITLE
following

### ISSUE THREAD

**Issue by asd646942825** [zju3dv/clean-pvnet#192]
I tried to compile ceres-solver-1.14.0

it can find some files at ceres-solver-1.14.0/build/lib called

libceres.so  libceres.so.1  libceres.so.1.14.0  libgtest.so libtest_util.so.

i see you say the steps about the problem.but i can not understand how to delete files what they are  and recompile the files what they are???thanks

**Comment by asd646942825** [comment]
The files called libspqr.so.2  libspqr.so.2.0.8 which i can not find.

**Comment by pengsida** [comment]
I did not get what you mean.
Please google about how to compile the ceres.

**Comment by asd646942825** [comment]
It's solved for the time being. Thank you
