### ISSUE TITLE
2d projection

### ISSUE THREAD

**Issue by miErfolg** [zju3dv/clean-pvnet#194]
您好，想请问
1. 2d projection points的点会有顺序问题吗？
2. 有什么方式是可以验证资料集的2d投影点是对的吗？
我们当前gt bounding box投影点的视觉看起来是对的，但是模型训练结果看似是错的，因为阶段中add、cmd5数值始终没有变动，谢谢您！

**Comment by pengsida** [comment]
你指的2d projection points是3d bounding box corners的2d投影点吗，是有相应的顺序的。

**Comment by miErfolg** [comment]
是的，
因为想产生自己的数据集，同样子以ape为目标用您提供的visualization部份进行验证，虽然视觉一样有8个点 2d projection，发现顺序上和linemod是不一样。
请问是否照linemod的顺序即可？
谢谢您！

**Comment by pengsida** [comment]
需要按linemod的顺序。

**Comment by miErfolg** [comment]
您好，今天将我们自己的数据集依照linemod相对角点顺序进行gt投影，验证得到的结果分别如下，训练中add以及cmd5的数值始终为零、,mask ap的数值一直为1了，请问有什么建议嘛？谢谢您
![image](https://user-images.githubusercontent.com/95376499/144596166-da7120e9-6c98-4571-a807-65edb0e051e7.png)
![L_R T](https://user-images.githubusercontent.com/95376499/144597006-5df85d42-e100-44f7-84ab-776d18a89ef7.png)

**Comment by Vemokaz** [comment]
> 您好，今天将我们自己的数据集按照linemod相对角点顺序进行gt投影，验证得到的结果分别如下，中add以及cmd5的数值始终训练、，mask ap的数值一直为1了，请问有有啥建议嘛？谢谢 ![图像](https://user-images.githubusercontent.com/95376499/144596166-da7120e9-6c98-4571-a807-65edb0e051e7.png) ![左右T](https://user-images.githubusercontent.com/95376499/144597006-5df85d42-e100-44f7-84ab-776d18a89ef7.png)

您好，请问您解决了吗？同时还想问问您是如何按照Linemod相对角点顺序进行投影的，这个还需要修改源代码吗？
