### ISSUE TITLE
Custom Dataset create train.json

### ISSUE THREAD

**Issue by KAOeric** [zju3dv/clean-pvnet#195]
Sorry, I had already create my own custom dataset, but I still loss the **train.json** file, how can I create it with the code to start my training?
Thanks for helping!!

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/144566947-3ccdaab0-5285-4aa2-a2b4-4e60cc09eb9c.png)

**Comment by KAOeric** [comment]
OK, I already solve it, thanks for your helping @pengsida !
