### ISSUE TITLE
Tless Dataset visualize Performance

### ISSUE THREAD

**Issue by KAOeric** [zju3dv/clean-pvnet#196]
![1638737126857](https://user-images.githubusercontent.com/36849812/144763284-86e4dc67-dda9-4c7d-b25d-95666c5a489f.jpg)
There are some great bounding box performance and some bad predict with my tless dataset visualize, how can I fix with the problem about this, anything I can do, Please give me some advice, thanks for helping!

**Comment by pengsida** [comment]
Improve the algorithm.

**Comment by KAOeric** [comment]
OK, I think i will try something to improve, thanks @pengsida
