### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by miErfolg** [zju3dv/clean-pvnet#197]
您好，我们自己的数据集依照linemod相对角点顺序进行gt投影，验证得到的结果分别如下，训练中add以及cmd5的数值始终为零、,mask ap的数值一直为1了，请问有什么建议嘛？谢谢您
![144596166-da7120e9-6c98-4571-a807-65edb0e051e7](https://user-images.githubusercontent.com/95376499/144792914-c08ba48e-0811-4af4-a600-580094d4cb8d.png)
![144597006-5df85d42-e100-44f7-84ab-776d18a89ef7](https://user-images.githubusercontent.com/95376499/144792918-fc59532e-4e8e-4bd7-9a35-15ff829042ba.png)

**Comment by pengsida** [comment]
可能是你们的数据集有bug。

**Comment by miErfolg** [comment]
想向您请教问题大概会在哪个方向？我们有办法确定转换实际已经是对的嘛？谢谢

**Comment by pengsida** [comment]
从你画出的图片上看起来关键点的顺序好像不对。

**Comment by miErfolg** [comment]
这是我们的训练结果，不管怎么调整model.ply的模型档案都会有差不多的结果，不知道还有什么调整方向您给建议吗?
![image](https://user-images.githubusercontent.com/95376499/145246531-22b3de8a-6128-4930-b037-8e6675e38144.png)
![image](https://user-images.githubusercontent.com/95376499/145246873-a22c035d-f38e-41b9-9103-1166a6c79c77.png)

**Comment by miErfolg** [comment]
目前验证的结果，观察是pred角点顺序和转向没有照着gt

**Comment by pengsida** [comment]
需要保证自己的数据集里角点顺序和转向和linemod的一样。

**Comment by MaxShi007** [comment]
> 您好，我们自己的数据集依照linemod相对角点顺序进行gt投影，验证得到的结果分别如下，训练中add以及cmd5的数值始终为零、,mask ap的数值一直为1了，请问有什么建议嘛？谢谢您 ![144596166-da7120e9-6c98-4571-a807-65edb0e051e7](https://user-images.githubusercontent.com/95376499/144792914-c08ba48e-0811-4af4-a600-580094d4cb8d.png) ![144597006-5df85d42-e100-44f7-84ab-776d18a89ef7](https://user-images.githubusercontent.com/95376499/144792918-fc59532e-4e8e-4bd7-9a35-15ff829042ba.png)

我也遇到了同样的问题，loss可以下降但2d投影，add和5cm5d一直是0，mask一直是1，请问您解决了吗，怎么解决的
