### ISSUE TITLE
Custom data training

### ISSUE THREAD

**Issue by KAOeric** [zju3dv/clean-pvnet#198]
![1638865569137](https://user-images.githubusercontent.com/36849812/144993710-1060393e-4077-4fb7-92c8-4e55f4512c7d.jpg)
When I start training the own custom dataset, I got the zero value with **2d projection metric** and **add metric** and **5 cm 5 degree metric** and got the mask with 1, I think this is the wrong result, how can I solve it?

**Comment by pengsida** [comment]
Please check if your data is correct.

**Comment by RoyAmoyal** [comment]
> ![1638865569137](https://user-images.githubusercontent.com/36849812/144993710-1060393e-4077-4fb7-92c8-4e55f4512c7d.jpg) When I start training the own custom dataset, I got the zero value with **2d projection metric** and **add metric** and **5 cm 5 degree metric** and got the mask with 1, I think this is the wrong result, how can I solve it?

did you find any solution? I don't know how to solve it..
