### ISSUE TITLE
libceres.so.2

### ISSUE THREAD

**Issue by asd646942825** [zju3dv/clean-pvnet#199]
请问一下，我用终端训练是可以的，为什么用pycharm训练就跳出这个错误？
ImportError: libceres.so.2: cannot open shared object file: No such file or directory

**Comment by Lexie971102** [comment]
想问一下，为什么我在编译nn和fps时会报错误，你们有报错吗
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
LINK : fatal error LNK1181: 无法打开输入文件“stdc++.lib”
cffi.VerificationError: LinkError: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

**Comment by pengsida** [comment]
@asd646942825 需要加环境变量。

**Comment by pengsida** [comment]
@Lexie971102 这个程序没有在windows上运行过。建议在ubuntu上运行。

**Comment by Lexie971102** [comment]
> 

我设置了cuda环境变量了

另外想请问一下，clean pvnet和pvnet有什么区别吗

**Comment by pengsida** [comment]
clean pvnet在效果上和pvnet没有区别。clean-pvnet整理了代码，然后有其他数据集上的结果，而且在tless数据集上加了detector。

**Comment by pengsida** [comment]
需要设置ceres的环境变量。
![image](https://user-images.githubusercontent.com/11582122/146299118-d9cf8d9b-2c71-47a5-b7c6-b202719fd8b9.png)
