### ISSUE TITLE
About diameter

### ISSUE THREAD

**Issue by firstdeep** [zju3dv/clean-pvnet#20]
Thank you for sharing your amazing research.

I wonder how you got the Diameter of the Linemod dataset you saved in advance.

If you have a code, I'd appreciate it if you could share it.

cheers

David

**Comment by pengsida** [comment]
I read it from https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/EaoGIPguY3FAgrFKKhi32fcB_nrMcNRm8jVCZQd7G_-Wbg?e=ig4aHk

**Comment by firstdeep** [comment]
Thank you. 

I hope your lab is safe from the infectious disease.

David

**Comment by pengsida** [comment]
Thank you.
