### ISSUE TITLE
Train time

### ISSUE THREAD

**Issue by tendernesswty** [zju3dv/clean-pvnet#200]
Hello! When I used my dataset for training, I found that the ADD's metric and other evaluation values were normal at the beginning, and the loss also decreased normally. But when I trained up to 15 epochs, the ADD Metric went to zero, and then the loss started getting bigger. I was wondering is this a problem with my dataset? And under what circumstances does ADD‘s’ metric go to 0

**Comment by pengsida** [comment]
Yes, there is probably a problem with your dataset.
If the data is wrong, the network cannot be trained well, which results in poor performance.

**Comment by tendernesswty** [comment]
> Yes, there is probably a problem with your dataset. If the data is wrong, the network cannot be trained well, which results in poor performance.

thanks for your reply. Maybe I will  reconstruct my dataset.
