### ISSUE TITLE
编译nn和fps时报错

### ISSUE THREAD

**Issue by Lexie971102** [zju3dv/clean-pvnet#201]
想问一下，为什么我在编译nn和fps时会报错误，你们有报错吗
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
LINK : fatal error LNK1181: 无法打开输入文件“stdc++.lib”
cffi.VerificationError: LinkError: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
我是在win10运行的

**Comment by pengsida** [comment]
这个程序没有在windows上运行过。建议在ubuntu上运行。
