### ISSUE TITLE
Training question

### ISSUE THREAD

**Issue by KAOeric** [zju3dv/clean-pvnet#202]
![1639649418576](https://user-images.githubusercontent.com/36849812/146351992-10559830-9adb-4a32-a087-ffe1eee89158.jpg)
When I start training and run 500 step, my batch_size setting is 64 and then training stop, it doesn' t do anything.
Please help me know anything i can do to continue the training, thanks for helping.

**Comment by pengsida** [comment]
Each epoch takes 500 iterations: https://github.com/zju3dv/clean-pvnet/blob/master/configs/tless/tless_01.yaml#L10

**Comment by KAOeric** [comment]
Yes, but sometimes it can not continue to next epoch when it already run 500 iterations, how can I solve it?

**Comment by pengsida** [comment]
What dataset you use to train the network?

**Comment by KAOeric** [comment]
I use the TLESS Dataset that shared in this project

**Comment by pengsida** [comment]
I do not know. I did not encounter this problem.
