### ISSUE TITLE
Dataset Generation with Larger Aruco Markers

### ISSUE THREAD

**Issue by spencervoiss** [zju3dv/clean-pvnet#205]
Hi,
I'm having trouble with the ObjectDatasetTools dataset generator.  Specifically, I'm running into some issues with registering a large target. I'm trying to generate a dataset for a model plane with a wingspan of 2.1m, but it's not registering properly. I've scanned a small target with moderate success, but the bigger target seems to be confusing the algorithm. I've attached photos of a successful registration (the small plane) and of the unsuccessful registrations (the big plane).
My hypothesis is that the problems are resulting from the Aruco markers being too small for the cameras to pick up at the distances required to get the whole target in the shot. What all would I need to change in the source code for it to work with larger Aruco markers (perhaps 8"x8" per marker)? Do you think that enlarging the Aruco markers would solve this issue?
**Successful Registration with a Small Target:**
![miniCessnaMetrology](https://user-images.githubusercontent.com/32341644/151873929-a5708f68-adc4-40d0-9be7-20c360ad4fa2.png)
**Example from small target RGB inputs**
![2594](https://user-images.githubusercontent.com/32341644/151874597-379b8955-a331-4f33-b279-566393567bbd.jpg)

**Unsuccessful Registration with the Large Target:**
![bigCessnaZED](https://user-images.githubusercontent.com/32341644/151874287-e43815d3-eb2b-4898-a77c-0124a97d6129.png)
**Example from large target RGB inputs**
![881](https://user-images.githubusercontent.com/32341644/151874788-678f3acb-58e3-48dc-b8b5-a005a914f4e8.jpg)

**Comment by pengsida** [comment]
I did not use ObjectDatasetTools before. So I do not know how to revise the code.
I think that enlarging the Aruco markers is a good idea.

**Comment by KAOeric** [comment]
@spencervoiss Sorry to asking you, Did you success bounding your custom Dataset, How did you make it?

**Comment by spencervoiss** [comment]
@KAOeric I've had some success, but I still haven't gotten it quite right. It looks like ObjectDatasetTools doesn't care what size your AR markers are, so you can print them whatever size you want. It computes the positions of the markers by finding their centers from their corners rather than by scanning the actual markers themselves. I increased the size of the markers to 180 mm rather than 60 mm and had much better results, but there was still some error in registration. I can see the clear outline of the target, but it didn't register quite right. Any thoughts on how to improve this? 
All data was captured using an Intel Realsense L515 with ObjectDatasetTools
**Sample Photo from Dataset**
![1](https://user-images.githubusercontent.com/32341644/153016138-ec180c51-7015-4062-bca7-ddc5adc91f48.jpg)
**Registered Scene**
![CessnaRSBigPCBack](https://user-images.githubusercontent.com/32341644/153021025-1510f008-2bf5-4199-814b-75cea909fd59.png)
![CessnaRSBigPCSide](https://user-images.githubusercontent.com/32341644/153021032-1201c339-32cc-46c0-a7a4-66cf53ccb00d.png)

**Comment by KAOeric** [comment]
Hi @spencervoiss:
Maybe you can adjust the AR marker to be straight, I already did it, just like this 
![1](https://user-images.githubusercontent.com/36849812/153054701-efad47dd-da21-4633-a6fb-76388253b859.jpg)
But my question is, I still cannot have a correct Bounding box result. Can you show me your success result?
![1644346198825](https://user-images.githubusercontent.com/36849812/153055779-f74432e2-8519-44c4-8756-992cfdf9fb65.jpg)
And this is my current result, it looks terrible.

**Comment by kygotocv** [comment]
@spencervoiss I encountered the same problem, have you solved it?
