### ISSUE TITLE
meta files for the rest of linemod objects

### ISSUE THREAD

**Issue by RoyAmoyal** [zju3dv/clean-pvnet#206]
hey, 
where can I find the rest of the meta.npy files for visualization of the linemod objects or how I am suppose to generate them (particularly for the ape and the duck)?

and when I want to use custom object, how can I generate this information?

**Comment by pengsida** [comment]
I did not provide the meta.npy of other objects.
You could look at what is in meta.npy and generate them yourself.

**Comment by RoyAmoyal** [comment]
{'kpt_3d': array([[ 0.02178441, -0.05869994, -0.0414618 ],
       [-0.02093567,  0.0655842 ,  0.03955495],
       [ 0.02779895,  0.02978627, -0.04446336],
       [ 0.00139469, -0.05708839,  0.03459186],
       [ 0.01266971,  0.01578414,  0.07163165],
       [-0.032556  , -0.03509996, -0.04010978],
       [-0.02941702,  0.02281759, -0.03967477],
       [ 0.02389689,  0.04313551,  0.03052332],
       [-0.0002315 ,  0.0020155 ,  0.0132825 ]]), 'corner_3d': [[-0.033737, -0.061801, -0.045446], [-0.033737, -0.061801, 0.072011], [-0.033737, 0.065832, -0.045446], [-0.033737, 0.065832, 0.072011], [0.033274, -0.061801, -0.045446], [0.033274, -0.061801, 0.072011], [0.033274, 0.065832, -0.045446], [0.033274, 0.065832, 0.072011]], 'K': [[572.4114, 0.0, 325.2611], [0.0, 573.57043, 242.04899], [0.0, 0.0, 1.0]]}


so I understand it is the kpt_3 and the corner_3d. (the K is just the camera intrinsics).

can you please explain how can I generate them? (prettry new in Computer graphics)

**Comment by RoyAmoyal** [comment]
> I did not provide the meta.npy of other objects. You could look at what is in meta.npy and generate them yourself.


{'kpt_3d': array([[ 0.02178441, -0.05869994, -0.0414618 ],
[-0.02093567, 0.0655842 , 0.03955495],
[ 0.02779895, 0.02978627, -0.04446336],
[ 0.00139469, -0.05708839, 0.03459186],
[ 0.01266971, 0.01578414, 0.07163165],
[-0.032556 , -0.03509996, -0.04010978],
[-0.02941702, 0.02281759, -0.03967477],
[ 0.02389689, 0.04313551, 0.03052332],
[-0.0002315 , 0.0020155 , 0.0132825 ]]), 'corner_3d': [[-0.033737, -0.061801, -0.045446], [-0.033737, -0.061801, 0.072011], [-0.033737, 0.065832, -0.045446], [-0.033737, 0.065832, 0.072011], [0.033274, -0.061801, -0.045446], [0.033274, -0.061801, 0.072011], [0.033274, 0.065832, -0.045446], [0.033274, 0.065832, 0.072011]], 'K': [[572.4114, 0.0, 325.2611], [0.0, 573.57043, 242.04899], [0.0, 0.0, 1.0]]}

so I understand it is the kpt_3 and the corner_3d. (the K is just the camera intrinsics).

can you please explain how can I generate them? (prettry new in Computer graphics)

**Comment by pengsida** [comment]
Yes, you just need the ply file.
9 points consists of 8 fps points and 1 center points.

**Comment by pengsida** [comment]
Yes.

**Comment by RoyAmoyal** [comment]
> Yes.

I didn't really understand how to generate the meta.npy for custom object. How can I do that?

**Comment by pengsida** [comment]
The mean of 8 points is the center point.
