### ISSUE TITLE
run on cuda11

### ISSUE THREAD

**Issue by HannahHaensen** [zju3dv/clean-pvnet#209]
is it possible to compile it with the latest pytorch version using cuda 11.3?

System Info:
Ubuntu 20.04
**CUDA_HOME**: /usr/local/cuda-11.3

**nvcc:**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

**Comment by RainYQ** [comment]
Use torch < 1.11.0

**Comment by pengsida** [comment]
You could try it.
