### ISSUE TITLE
OSError: data/linemod/cam/test_occlusion.txt not found.

### ISSUE THREAD

**Issue by QRayMoor** [zju3dv/clean-pvnet#210]
您好，我在执行`python run.py --type linemod cls_type cam`时遇到报错：OSError: data/linemod/cam/test_occlusion.txt not found.发现Linemod数据集下`cam`、`iron`、`phone`里没有test_occlusion.txt文件，请问要如何解决？
另外，TruncationLINEMOD数据集如何测试？测试指令和代码没有在项目里看到，请您指点。
最后，请问论文中的语义分割图和向量场图如何生成？

**Comment by pengsida** [comment]
1. occlusion dataset没有这几个物体。
2. 我们没有放TruncationLINEMOD数据集的测试，需要自己实现。
3. 语义分割图请看这个代码：https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/linemod/pvnet.py#L44
4. 向量场图请看这个代码：https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/linemod/pvnet.py#L53
