### ISSUE TITLE
the meta.npy in demo folder

### ISSUE THREAD

**Issue by renren66** [zju3dv/clean-pvnet#215]
感谢对pvnet的开源。
最近遇到一个问题，在meta.npy 里面”kpt_3d“中是8个fps点和1个中心点组成的，我有疑问的是这个中心点是如何生成的呢？

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/issues/206

**Comment by pengsida** [comment]
中心点是8个corner points的平均。

**Comment by renren66** [comment]
明白了，十分感谢

**Comment by BoBoINVIDICUS** [comment]
> 明白了，十分感谢

你好，最近我也在使用PVnet，想请教下您是否知道如何制作meta.py这个文件？期待您的回复，感谢！
