### ISSUE TITLE
Build the ransac_voting_layer with cuda11+ and pytorch1.10+

### ISSUE THREAD

**Issue by GUOShuxuan** [zju3dv/clean-pvnet#218]
Hi, it is a beautiful work. I tried to build the repo based on pytorch1.7 and cuda-11.5. It failed. 

Have you ever tried to rebuild the repo based on the up-to-date pytorch and cuda? It would be great if you can give some updates to the new version.

Thanks,
Shuxuan

**Comment by pengsida** [comment]
What error did it report when you build the repo?

**Comment by neverstoplearn** [comment]
> What error did it report when you build the repo?
running build_ext
building 'ransac_voting' extension
creating /home/zhengxin/clean-pvnet/lib/csrc/ransac_voting/build
creating /home/zhengxin/clean-pvnet/lib/csrc/ransac_voting/build/temp.linux-x86_64-3.7
creating /home/zhengxin/clean-pvnet/lib/csrc/ransac_voting/build/temp.linux-x86_64-3.7/src
Emitting ninja build file /home/zhengxin/clean-pvnet/lib/csrc/ransac_voting/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.7.2
creating build/lib.linux-x86_64-3.7
g++ -pthread -B /home/zhengxin/anaconda3/envs/torch182/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/zhengxin/anaconda3/envs/torch182/compiler_compat -L/home/zhengxin/anaconda3/envs/torch182/lib -Wl,-rpath=/home/zhengxin/anaconda3/envs/torch182/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/zhengxin/clean-pvnet/lib/csrc/ransac_voting/build/temp.linux-x86_64-3.7/./src/ransac_voting.o /home/zhengxin/clean-pvnet/lib/csrc/ransac_voting/build/temp.linux-x86_64-3.7/./src/ransac_voting_kernel.o -L/home/zhengxin/anaconda3/envs/torch182/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda-11.1/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-3.7/ransac_voting.cpython-37m-x86_64-linux-gnu.so
g++: error: /home/zhengxin/clean-pvnet/lib/csrc/ransac_voting/build/temp.linux-x86_64-3.7/./src/ransac_voting.o: 没有那个文件或目录
g++: error: /home/zhengxin/clean-pvnet/lib/csrc/ransac_voting/build/temp.linux-x86_64-3.7/./src/ransac_voting_kernel.o: 没有那个文件或目录
error: command '/usr/bin/g++' failed with exit code 1
I build in pytorch 1.8.1 cuda-11.1 but I got this error?
