### ISSUE TITLE
No CUDA runtime is found

### ISSUE THREAD

**Issue by ishangupta3** [zju3dv/clean-pvnet#22]
I am getting the error below, but I have double checked and the cuda-9.0 does exist in the specified usr/local directory. I am following the exact setup directions as listed on a Ubuntu machine 16.04

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-9.0'
/usr/local/cuda-9.0
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 41, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel

**Comment by pengsida** [comment]
Did you use cuda in your computer?

**Comment by ishangupta3** [comment]
It came already installed in the Ubuntu instance, and located here: **/usr/local/cuda-9.0**

Do I need to run any other commands before this command: CUDA_HOME='/usr/local/cuda-9.0'

**Comment by ishangupta3** [comment]
Did not mean to close the issue.

**Comment by pengsida** [comment]
No. Did you use the pytorch with cuda in your computer?

**Comment by ishangupta3** [comment]
I did not connect my pytorch with the cuda in the computer, how would I go about doing that?

**Comment by pengsida** [comment]
Google.

**Comment by ishangupta3** [comment]
Does this command not connect the pytorch to the cuda on my machine?:

pip install torch==1.1.0 -f https://download.pytorch.org/whl/cu90/stable

**Comment by ishangupta3** [comment]
or would i have to do this:

conda install pytorch torchvision cudatoolkit=9.0 -c pytorch

**Comment by pengsida** [comment]
I don't know the situation of your computer environment.
Google about how to use pytorch with cuda.
