### ISSUE TITLE
some problems about unit vector

### ISSUE THREAD

**Issue by helloyuning** [zju3dv/clean-pvnet#220]
Thanks for your grate work and sharing
After reading your paper I have some problems about unit verctors and loss function

1. I noticed that you said  we do not nedd to pay more attention on the values of v(k), cause we just nedd to know what is the direction.
My question is that how can I know if all the vectors get correct directions? 

2. And the loss fuction seems only calculate Vector error, I am confused if the sematic segmentaion will affects the result?  

Sorry for asking so many questions

**Comment by pengsida** [comment]
1. You can see it from the final results.
2. The loss functions include the semantic segmentation loss.
