### ISSUE TITLE
Seg_loss didn't drop 

### ISSUE THREAD

**Issue by sean6585** [zju3dv/clean-pvnet#223]
I trained a model using my own dataset.
I'm just wondering why seg_loss didn't drop a lot from the begining.
![messageImage_1664879311167](https://user-images.githubusercontent.com/59359578/193803756-38298e1e-1712-48cd-91f5-23bdadd38a25.jpg)

When I evaluated it, the mask ap70 is zero. While others metric make sense.
![image](https://user-images.githubusercontent.com/59359578/193803387-fb8dad52-9efd-4f9c-9465-97d950f3ac16.png)

**Comment by pengsida** [comment]
Maybe the annotation is not correct.
