### ISSUE TITLE
ransac voting question

### ISSUE THREAD

**Issue by RainYQ** [zju3dv/clean-pvnet#226]
In `ransac_voting_layer_v3`:

```python
(1 - (1 - cur_min_ratio ** 2) ** hyp_num) > confidence
```

The `confidence` is set to 0.99, so it may mean the probability when all selected points are inliers. The `cur_min_ration` is the min inlier probability in all keypoints.

what does `(1 - (1 - cur_min_ratio ** 2) ** hyp_num)` mean? The `(1 - cur_min_ratio ** 2) ** hyp_num` always equals to 0.

Maybe it's wrong?

**Comment by pengsida** [comment]
If the hyp_num is big enough, the predicted result has high confidence.
