### ISSUE TITLE
ValueError when processing custom dataset

### ISSUE THREAD

**Issue by youngwoo1** [zju3dv/clean-pvnet#231]
Hi, thanks for your work

In Training on the custom object,  Process the dataset
when I run the code, ValueError occurred.

Traceback (most recent call last):
  File "run.py", line 276, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 222, in run_custom
    handle_custom_dataset.custom_to_coco(data_root)
  File "/home/youngwoo/clean-pvnet/tools/handle_custom_dataset.py", line 110, in custom_to_coco
    img_id, ann_id = record_ann(model_meta, img_id, ann_id, images, annotations)
  File "/home/youngwoo/clean-pvnet/tools/handle_custom_dataset.py", line 67, in record_ann
    corner_2d = base_utils.project(corner_3d, K, pose)
  File "/home/youngwoo/clean-pvnet/lib/utils/base_utils.py", line 24, in project
     xyz = np.dot(xyz, K.T)
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (8,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)

Could you please help me with this error?

**Comment by lululovecode** [comment]
So am I. Have you solved this problem now? I don't know how to solve it.Thank you very much!

**Comment by youngwoo1** [comment]
> So am I. Have you solved this problem now? I don't know how to solve it. Thank you very much!

Yeah, I solved it. 
It seems that the transformation matrix should be changed from 4x4 to 3x4. 
In lib/utils/pvnet/pvnet_pose_utils.py def project, I just change RT =->RT[0:3,:] 
and lib/evaluators/custom/pvnet.py  def add_metric, def cm_degree_5_metric I changed pose_targets -> pose_targets[0:3,:]
Good luck!

**Comment by lululovecode** [comment]
> > So am I. Have you solved this problem now? I don't know how to solve it. Thank you very much!
> 
> Yeah, I solved it. It seems that the transformation matrix should be changed from 4x4 to 3x4. In lib/utils/pvnet/pvnet_pose_utils.py def project, I just change RT =->RT[0:3,:] and lib/evaluators/custom/pvnet.py def add_metric, def cm_degree_5_metric I changed pose_targets -> pose_targets[0:3,:] Good luck!

I just solve this problem,too! Thanks for your reply! But I met another error just now, please look at this print screen:
![LQBJ_0{E`L%NTC~)NM8A5JJ](https://user-images.githubusercontent.com/113014125/208853907-ece85093-15ad-4f9e-9278-0fb27f73ca45.png)
Could you please help me solve this problem? Thanks a lot! Sincerely.

**Comment by youngwoo1** [comment]
> > > So am I. Have you solved this problem now? I don't know how to solve it. Thank you very much!
> > 
> > 
> > Yeah, I solved it. It seems that the transformation matrix should be changed from 4x4 to 3x4. In lib/utils/pvnet/pvnet_pose_utils.py def project, I just change RT =->RT[0:3,:] and lib/evaluators/custom/pvnet.py def add_metric, def cm_degree_5_metric I changed pose_targets -> pose_targets[0:3,:] Good luck!
> 
> I just solve this problem,too! Thanks for your reply! But I met another error just now, please look at this print screen: ![LQBJ_0{E`L%NTC~)NM8A5JJ](https://user-images.githubusercontent.com/113014125/208853907-ece85093-15ad-4f9e-9278-0fb27f73ca45.png) Could you please help me solve this problem? Thanks a lot! Sincerely.

I'm sorry. I've never seen an error like this.
