### ISSUE TITLE
運行Demo時，預測框沒有框住物體，偏差較大

### ISSUE THREAD

**Issue by BoBoINVIDICUS** [zju3dv/clean-pvnet#233]
當我按照您的指示，一步一步運行指令到“python run.py --type demo --cfg_file configs/linemod.yaml demo_path demo_images/cat”時，演示結果似乎不對，如下圖所示：
![image](https://user-images.githubusercontent.com/102162738/203539737-6e56f112-b45d-428f-b8a4-7dbbc048f86d.png)
以下是我的終端輸出的內容，麻煩您看一下是什麼原因導致的：
(pvnet-cuda-11.1) akon@akon-System-Product-Name:~/clean-pvnet$ python run.py --type demo --cfg_file configs/linemod.yaml demo_path demo_images/cat
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
/home/akon/clean-pvnet/lib/csrc/ransac_voting/ransac_voting_gpu.py:142: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /opt/conda/conda-bld/pytorch_1614378098133/work/aten/src/ATen/native/IndexingUtils.h:30.)
  direct = vertex[bi].masked_select(torch.unsqueeze(torch.unsqueeze(cur_mask, 2), 3))  # [tn,vn,2]

但是當我運行指令：python run.py --type visualize --cfg_file configs/linemod.yaml model cat cls_type cat時，效果圖和您的效果一致，如下所示：
![image](https://user-images.githubusercontent.com/102162738/203540334-8b0837cf-a4b7-47b0-a6d5-ce9efeaf4d26.png)

**Comment by WHHHHY** [comment]
请问您最后是如何解决这个问题的
