### ISSUE TITLE
Negative Z Value Prediction for unseen images

### ISSUE THREAD

**Issue by Divyam10** [zju3dv/clean-pvnet#234]
Hey @pengsida, thanks for publishing code for this amazing research!

I am trying to train PVNET on custom dataset and I have generated data using for - Objectdatasetools and BlenderProc. For both of them I visualised the GT labels ( pose ) and they are correct. All the poses also have Z value positive.

However post training, the pose received from keypoints predicted, have negative Z values quite often. Could you help understand what could be the reason? 

My end goal is to render and overlay the 3D CAD model's projection using the pose on the object in the image. The negative Z valued pose does not project the points in the camera frame.

**Comment by pengsida** [comment]
Maybe your objects are relatively flat.

**Comment by Divyam10** [comment]
I am training on the upper part of a spray gun. Here are the example images

![28](https://user-images.githubusercontent.com/29382463/210526078-b86dae20-321c-4c4c-aaa3-b2be40985541.png)

![0](https://user-images.githubusercontent.com/29382463/210526063-672af18a-8ecf-405b-a368-aa082b09c089.png)

**Comment by Divyam10** [comment]
Also, could you suggest good number of images for optimal training? currently I am using 2000 images.

**Comment by Divyam10** [comment]
Solved it, thanks!

**Comment by assia855** [comment]
Hi @Divyam10  how did you visualize the pose please?

**Comment by monajalal** [comment]
@Divyam10 could you please share the BlenderProc script you used for creating the dataset as well as the format of the dataset? Thank you
