### ISSUE TITLE
Augmentation on my custom dataset

### ISSUE THREAD

**Issue by sean6585** [zju3dv/clean-pvnet#236]
Does anyone know how to apply the augmentation on my custom dataset? Please help me.
I found the function, but don't know how to use it.
Should I modify something in run.py python script?
https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/custom/pvnet.py

**Comment by pengsida** [comment]
The code will apply the augmentation during training: https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/custom/pvnet.py#L46
