### ISSUE TITLE
下载链接失效

### ISSUE THREAD

**Issue by lululovecode** [zju3dv/clean-pvnet#237]
你好，linemod预训练权重的下载链接打不开了，麻烦补个链接可以吗，谢谢！

**Comment by lululovecode** [comment]
“Testing on Linemod

We provide the pretrained models of objects on Linemod, which can be found at [here](https://1drv.ms/f/s!AtZjYZ01QjphgQBQDQghxjbkik5f).“这里的

**Comment by pengsida** [comment]
我可以打开这个链接。可能需要翻墙。
