### ISSUE TITLE
在VScode上debug出现问题

### ISSUE THREAD

**Issue by TiRaMisu1024** [zju3dv/clean-pvnet#239]
你好！我在终端运行python run.py --type visualize --cfg_file configs/linemod.yaml model cat cls_type cat成功，可以显示结果
但是在vscode上调试的时候，出现了错误：No module named 'lib.csrc.ransac_voting.ransac_voting'，请问这个问题怎么解决？
![2023-02-23 18-49-31 的屏幕截图](https://user-images.githubusercontent.com/95954901/220886030-31a30e13-7786-4712-85fb-a31e5caf65b7.png)

**Comment by pengsida** [comment]
我不熟悉vscode的python运行。可能是环境变量的问题。

**Comment by TiRaMisu1024** [comment]
请问你是用的pycharm调试代码吗？

**Comment by TiRaMisu1024** [comment]
好的，十分感谢！
