### ISSUE TITLE
请问pvnet有办法转换成onnx格式吗？

### ISSUE THREAD

**Issue by ShiMiaohui0426** [zju3dv/clean-pvnet#240]
感谢彭总，我在pvnet这个项目中学到了许多新的知识。目前，我已经完成了pvnet在本地的复现。并且能够对实时视频流进行估计。

https://user-images.githubusercontent.com/112537368/221396583-c1844b36-3126-4a64-a388-08f0b082cb9d.mp4

就像这个视频演示的这样
根据我的测试，pvnet在我的设备上可以以最快35ms的速度对一张图片中的但个对象进行推理。
我想知道pvnet能否通过转化为onnx等格式进一步提升运行速度。

**Comment by pengsida** [comment]
你好，我没有用过onnx。

**Comment by ShiMiaohui0426** [comment]
感谢你的回复，了解了。
