### ISSUE TITLE
请教一些函数的意思

### ISSUE THREAD

**Issue by BoBoINVIDICUS** [zju3dv/clean-pvnet#241]
在pvnet.py里的 “ visualize_demo()” 函数中，“pose_red”是否是预测的物体在相机坐标系下的位姿？“corner_2d_pred”代表的是什么？
![image](https://user-images.githubusercontent.com/102162738/221784092-19970ebc-b9c8-4931-ad4d-fc2efc88fc92.png)

**Comment by pengsida** [comment]
`pose_pred`是预测的pose，`corner_2d_pred`是根据预测的pose投影3d keypoints得到的2d points。

**Comment by BoBoINVIDICUS** [comment]
> `pose_pred`是预测的pose，`corner_2d_pred`是根据预测的pose投影3d keypoints得到的2d points。

感谢您回答，请问得到的位姿中的平移向量的单位是米吗？根据预测的pose投影3d keypoints得到的2d points是指识别出物体后的边界框的八个顶点吗？

**Comment by pengsida** [comment]
1. 是的，单位是米。
2. 2d points是物体三维点的投影点，不是识别得到的点。
