### ISSUE TITLE
关于multiple instances的位姿估计问题

### ISSUE THREAD

**Issue by TiRaMisu1024** [zju3dv/clean-pvnet#243]
彭思达同学你好：
首先十分感谢你能够提供开源的PVNet网络。
我已经复现了PVNet网络，能够对LInemod数据集和Tless数据集进行测试，并且实现了linemod数据集中的单个物体在线位姿估计。
在阅读代码时我有一些困惑想请教你一下：
1. 在linemod数据集上只能实现单一种类单个目标的位姿估计，但是tless数据集上能偶实现单一种类多个目标的位姿估计，我观察了Resnet18网络，在跑这两个数据集的时候设置的{'vote_dim': 18, 'seg_dim': 2}都是一样的，但是输出的kpt_2d和mask的shape不一样，请问为什么在tless数据集上能够实现多个目标的位姿估计？这个区别主要体现在哪些文件或者参数上？
2. 请问如果要对多个种类（比如cat、duck等）同时进行位姿估计，需要修改数据集的格式吗？或者需要修改什么地方？
十分期待你的回复
from zju.me

**Comment by pengsida** [comment]
1. 因为加了2D detection，所以能处理多个物体。
2. 需要修改数据集。dataloader、网络和loss都要改。

**Comment by TiRaMisu1024** [comment]
多谢这么快的回复！
抱歉我还想问一下，方便指明一下2D detection加在哪里了吗？
谢谢！

**Comment by pengsida** [comment]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/11582122/225007584-ea5beec8-a5d6-4183-9cfe-eaed425f4684.png">

**Comment by Huskywyh** [comment]
思达同学您好，我想问下如果想加入深度通道训练，linemod数据集里renders和fuse的深度图在哪里？
