### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by TiRaMisu1024** [zju3dv/clean-pvnet#244]
思达同学你好！关于PVNet网络我想一下：
1.请问用于tless测试和训练的cache文件夹里tless_ct/result.json、tless_pose/test.json是如何生成的？
2.是否可以由train_net.py训练得到目标检测模型（就如ct/ct_cat/9.pth）？如果可以那训练数据还是提供的linemod数据集吗？
3.我用命令python run.py --type detector_pvnet --cfg_file configs/ct_linemod.yaml 想试一下多物体的位姿估计效果，但是在多个cat物体的图片里只能估计出一个，请问这个是什么原因？需要修改什么参数吗（我改过cfg.det_meta.heads = CN({'ct_hm': 1, 'wh': 2})的数值，但还是只能预测一个，效果如下图：）？
![Figure_1](https://user-images.githubusercontent.com/95954901/225609381-98df034b-cf68-456e-a8f6-ca6da21e1117.png)
期待你的回复。

**Comment by pengsida** [comment]
1. 用这个脚本：https://github.com/zju3dv/clean-pvnet/blob/master/tools/handle_custom_dataset.py
2. 请查看README来学习怎么训练模型。训练数据是自己的数据集。
3. @haotongl 有时间的时候帮忙看一下。

**Comment by TiRaMisu1024** [comment]
好的，感谢及时的回复！之前我有训练过几个位姿估计的样本，但是没有试过目标检测的，我再仔细看看。
请问一下自己的数据集就是参照README上的custom数据集来制作吧？抱歉麻烦了。

**Comment by pengsida** [comment]
是的。

**Comment by TiRaMisu1024** [comment]
好的，谢谢思达同学！期待对于python run.py --type detector_pvnet --cfg_file configs/ct_linemod.yaml 只能估计一个物体位姿的解答~

**Comment by TiRaMisu1024** [comment]
> 1. 用这个脚本：https://github.com/zju3dv/clean-pvnet/blob/master/tools/handle_custom_dataset.py
> 2. 请查看README来学习怎么训练模型。训练数据是自己的数据集。
> 3. @haotongl 有时间的时候帮忙看一下。

思达同学你好：
对于你提供的第二个解决方法，我尝试用指令 python train_net.py --cfg_file configs/ct_linemod.yaml model mycat cls_type cat 来训练带有2d detector的网络，修改了许多报错但还是无法训练。请问思达同学有提供训练network with detector的脚本文件吗？应该如何生成./data/model/ct/ct_cat/ 之下的训练权重文件？

**Comment by pengsida** [comment]
我们这个代码应该没有开源训练network with detector的代码。detector可以分开训练。

**Comment by pengsida** [comment]
是的。

**Comment by TiRaMisu1024** [comment]
请问可以给一些训练detector的提示吗？或者请问你是怎么训练的呢？我观察到2d dtection用的是dla框架，你是在dla的开源GitHub代码上对linemod数据集的cat进行训练的吗？（抱歉了）

**Comment by pengsida** [comment]
抱歉，因为已经很久之前了，我忘记了。
@haotongl 浩通可能记得。

**Comment by haotongl** [comment]
> 请问可以给一些训练detector的提示吗？或者请问你是怎么训练的呢？我观察到2d dtection用的是dla框架，你是在dla的开源GitHub代码上对linemod数据集的cat进行训练的吗？（抱歉了）

我们之前是把基于DLA的CenterNet复现在这个框架下的，建议你使用CenterNet完成2D detection任务；需要重新训练。
