### ISSUE TITLE
Sharepoint links with datasets not working

### ISSUE THREAD

**Issue by bohnjonas** [zju3dv/clean-pvnet#245]
I am currently endeavoring to establish PVNet and wish to conduct an evaluation by utilizing the provided datasets. Regrettably, the hyperlinks to the datasets and "example dataset" appear to be non-functional.

**Comment by pengsida** [comment]
It should work now.

**Comment by mizeller** [comment]
The links seem to be expired - at least that's my message when trying to download the datasets:

很抱歉，此链接已过期。
链接设置为在一段时间后过期。请联系与你共享此链接的人员。
