### ISSUE TITLE
训练linemod数据集时产生的权重文件找不到

### ISSUE THREAD

**Issue by willieChen58** [zju3dv/clean-pvnet#247]
作者你好，我想问一下训练linemod数据集时产生的权重文件在哪个文件夹下找呢？还是说权重文件会在训练一定数量的epoch之后才会保存？我看了train_net.py貌似没有看到保存文件的语句

**Comment by pengsida** [comment]
$ROOT/data/model/pvnet/cat/

**Comment by willieChen58** [comment]
我在这个目录下也找过了，没有生成权重文件，是我训练的epoch还不够吗？目前是第4个epoch

**Comment by pengsida** [comment]
是的。

**Comment by willieChen58** [comment]
好的谢谢大佬！我后面再看一下
