### ISSUE TITLE
Download link to cat with a detector has expired

### ISSUE THREAD

**Issue by mwilson-zSpace** [zju3dv/clean-pvnet#248]
Download the pretrained models [https://zjueducn-my.sharepoint.com/:u:/g/personal/haotongl_zju_edu_cn/EZxeOruBmGZLr8vldbB381ABo4cpI1VsE4HhqjizMw1Opw?e=OUGtql](url) and put them to $ROOT/data/model/pvnet/pvnet_cat/59.pth and $ROOT/data/model/ct/ct_cat/9.pth

Gives me this:
Sorry, this link has expired.
Links are set to expire after a certain period of time. Please contact the person who shared this link with you.

**Comment by pengsida** [comment]
I have updated the link.

**Comment by mwilson-zSpace** [comment]
Thank you.
