### ISSUE TITLE
训练自己的数据集时出错

### ISSUE THREAD

**Issue by BoBoINVIDICUS** [zju3dv/clean-pvnet#249]
当我训练自己的数据集时，评价指标的值都是nan或者0.0，请问是什么原因造成的？
![Screenshot from 2023-04-08 19-04-05](https://user-images.githubusercontent.com/102162738/230717989-060e47f4-6212-4457-a857-3e847386b2ca.png)

**Comment by pengsida** [comment]
Please check if your data is correct.

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/issues/250
