### ISSUE TITLE
Require extra test condition in cm_degree_5_metric

### ISSUE THREAD

**Issue by mwilson-zSpace** [zju3dv/clean-pvnet#250]
Inside ..lib/utils/pvnet/pvnet_pose_utils.py ->cm_degree_5(...) trace is filtered so that arccos() is not passed a value > +1 however if trace has a value < -1 then (trace - 1.) / 2. evaluates to less than -1.  So I added an additional test.  trace = trace if trace >= -1 else -1
Didn't search exhaustively but also found same condition in .../lib/evaluators/custom/pvnet.py -> cm_degree_5_metric(...).  This could be the reason some are getting loss values of nan or 0. #249

**Comment by pengsida** [comment]
Cool.

**Comment by pengsida** [comment]
Haotong Lin has fixed this bug.

**Comment by BoBoINVIDICUS** [comment]
> Inside ..lib/utils/pvnet/pvnet_pose_utils.py ->cm_degree_5(...) trace is filtered so that arccos() is not passed a value > +1 however if trace has a value < -1 then (trace - 1.) / 2. evaluates to less than -1. So I added an additional test. trace = trace if trace >= -1 else -1 Didn't search exhaustively but also found same condition in .../lib/evaluators/custom/pvnet.py -> cm_degree_5_metric(...). This could be the reason some are getting loss values of nan or 0. #249



> Cool.
谢谢您的回复，之前提问的时候忘记说了一个现象，在训练的前几个epoch时，这些指标还是有些不为0.0或者nan的，但是从后面的某一个epoch开始时出现0.0和nan时，接下来将都是0.0和nan,如图所示：
![Screenshot from 2023-04-09 15-22-32](https://user-images.githubusercontent.com/102162738/230771015-8889ecc1-0a06-4734-a947-4f8fb58e77a2.png)
![Screenshot from 2023-04-09 15-23-19](https://user-images.githubusercontent.com/102162738/230771021-3b343bc4-1d59-49ab-8be5-37dda67d9619.png)
我也按照热心的“mwilson-zSpace”的建议修改了代码，但训练的结果还是和之前一样的问题，不知道是哪里出错了，还请再指点一下。
![Screenshot from 2023-04-09 19-59-36](https://user-images.githubusercontent.com/102162738/230771460-59f81495-3f7b-452c-8270-d299726d95a3.png)

**Comment by assia855** [comment]
Hi @mwilson-zSpace I still have this error, you mention "condition in .../lib/evaluators/custom/pvnet.py -> cm_degree_5_metric(...)" but didn't explain. what should I change else to make it work please?

**Comment by Vemokaz** [comment]
> Hi @mwilson-zSpace I still have this error, you mention "condition in .../lib/evaluators/custom/pvnet.py -> cm_degree_5_metric(...)" but didn't explain. what should I change else to make it work please?

I have the same error ,have you had finished it?
