### ISSUE TITLE
请问一个6D位姿估计的基础问题

### ISSUE THREAD

**Issue by pange1802703882** [zju3dv/clean-pvnet#252]
您好，我是刚刚入门6D位姿估计领域，在看论文的过程中发现最近有的方法说不使用CAD模型，请问CAD模型在网络中起到什么作用呢？我看到网络的输入数据都是RGB和RGBD，好像没看到CAD相关的部分呀

**Comment by pengsida** [comment]
CAD模型用于提供三维关键点。PnP算法需要三维关键点和二维关键点的匹配关系来计算物体位姿。
