### ISSUE TITLE
Failure to download datasets and models from SharePoint

### ISSUE THREAD

**Issue by alimulhuda** [zju3dv/clean-pvnet#255]
SharePoint links seem to be broken. The following links from the Readme don't work right now
https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/Ec6Hd9j7z4lCiwDhqIwDcScBGPw2rsbn6FJh1C2FwbPJTw?e=xcKGAw
https://zjueducn-my.sharepoint.com/:f:/g/personal/pengsida_zju_edu_cn/EjoUiAwfPOhGgFGPnJANDqoBLxnUAc7DO77voz6-KVp5Wg?e=6UGB3p
https://zjueducn-my.sharepoint.com/:f:/g/personal/pengsida_zju_edu_cn/Eh27tt7m6fJNgcCKMp9BzjABRzJTju6bT2GIZzcIVGu9WA?e=vURdqJ

Shows the following error
很抱歉，此链接已过期。
链接设置为在一段时间后过期。请联系与你共享此链接的人员。 

Google Translate:
Sorry, this link has expired.
Links are set to expire after a certain period of time. Please contact the person who shared this link with you.

**Comment by pengsida** [comment]
I have reactivated the link: https://zjueducn-my.sharepoint.com/:f:/g/personal/pengsida_zju_edu_cn/Eh27tt7m6fJNgcCKMp9BzjABRzJTju6bT2GIZzcIVGu9WA?e=vURdqJ

**Comment by TAO-TAO-TAO-TAO-TAO** [comment]
Hello, the link to the dataset has expired again. Would it be convenient for you to republish it?

**Comment by pengsida** [comment]
I have updated the link: https://drive.google.com/drive/folders/1nxGbqO2AYnHekatPZLgdFNahNwSErSoq?usp=sharing
