### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Zephyr-One** [zju3dv/clean-pvnet#257]
复现的时候提示如下报错信息：
ImportError: /home/xjyang/project/ykying/fapvnet/clean-pvnet/lib/csrc/ransac_voting/ransac_voting.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
请问怎么解决呢？谢谢
因为我的环境是Ubuntu20.04，3080Ti，所以是Cuda11.1+Pytorch1.8.0，不知道是不是环境的原因

**Comment by Zephyr-One** [comment]
已解决，还是cuda和pytorch没安装正确

**Comment by WHHHHY** [comment]
> 你好，我在用3090配置pvnet遇到了和你一样的问题，关于ransac.so文件的符号未定义报错，请问你最后用的是什么版本的cuda和torch解决了呢

**Comment by Zephyr-One** [comment]
> > 你好，我在用3090配置pvnet遇到了和你一样的问题，关于ransac.so文件的符号未定义报错，请问你最后用的是什么版本的cuda和torch解决了呢

最后好像还是cuda11.1+torch1.8.0，因为有段时间了，我也有点忘了当时怎么解决的hh

**Comment by WHHHHY** [comment]
> 

谢谢，已解决
