### ISSUE TITLE
resnet18输出问题请教

### ISSUE THREAD

**Issue by BoBoINVIDICUS** [zju3dv/clean-pvnet#258]
我在debug时发现x16s和x32s的输出维度似乎存在问题，
![image](https://github.com/zju3dv/clean-pvnet/assets/102162738/5c66d7f4-0c38-447e-afcd-c3f9a32511aa)
![image](https://github.com/zju3dv/clean-pvnet/assets/102162738/302e5b09-d213-4757-a603-e69ec0b717f4)
按照resnet18的输出，x16s和x32s的输出维度应该是（1，256，30，40）和（1，512，15，20），而在您的网络里输出的是1，256，60，80）和（1，512，60，80），请问您是做了什么其他处理了吗？为什么这样做呢？

**Comment by pengsida** [comment]
This network is a modified ResNet18. Please read the code.
