### ISSUE TITLE
请教关于训练自己的数据集后，在推理时效果差的原因

### ISSUE THREAD

**Issue by BoBoINVIDICUS** [zju3dv/clean-pvnet#260]
您好！peng：
我在使用objectTools完成了数据集的制作，图片数量为1287张，训练效果如下：
![1BTJ$)T8J$Z0SXK580RHNA6](https://github.com/zju3dv/clean-pvnet/assets/102162738/7daed170-3272-4102-b372-2b75b1759051)
但是在推理的过程中，效果较差：
![image](https://github.com/zju3dv/clean-pvnet/assets/102162738/92b95480-12f9-42fa-9d1d-e175b39e9ddc)
![AW(P5U{IC(N($52{EF{JXUB](https://github.com/zju3dv/clean-pvnet/assets/102162738/2aaaa680-defa-4cea-b397-c26e870005ed)
![V5F4(37U7_FRP`J`RT47DZT](https://github.com/zju3dv/clean-pvnet/assets/102162738/ebdeffb8-91c0-46c8-adc9-555334033f51)
![UHFUK FVH19D03IQGX 03NC](https://github.com/zju3dv/clean-pvnet/assets/102162738/79be74be-d6d7-42f8-98e3-66f37e81319e)
大概测试了有三十几张图片，基本效果都不太好，请问是什么原因造成的呢？

**Comment by pengsida** [comment]
最后两张效果还不错的样子？

**Comment by BoBoINVIDICUS** [comment]
> 最后两张效果还不错的样子？

最后一张是训练数据集里的图片，倒数第二张是好了一点，可还是差的较远，很疑惑问题出在哪里了

**Comment by pengsida** [comment]
应该是网络泛化能力的问题。感觉训练过程应该没啥问题，不然出不了后面两张的结果。
