### ISSUE TITLE
Demo issue ..

### ISSUE THREAD

**Issue by AmokraneIlhem** [zju3dv/clean-pvnet#261]
Hello author, 
When I follow your instructions and run the command "python run.py --type demo --cfg_file configs/linemod.yaml demo_path demo_images/cat", the result is not displayed! 
Do you have any idea how to solve this?
Thank u in advance. 
<img width="454" alt="vis" src="https://github.com/zju3dv/clean-pvnet/assets/63933573/d7c9a406-3802-43c5-be04-99ece07f4ffc">

**Comment by pengsida** [comment]
Please read the code and revise the display part.
