### ISSUE TITLE
Questions about pose estimation of symmetrical objects

### ISSUE THREAD

**Issue by BoBoINVIDICUS** [zju3dv/clean-pvnet#264]
Thanks to your excellent work！
However, when estimating a symmetric object,  because different angles of view have the same characteristics, the X and Y axes of the coordinate system will be changed repeatedly in the actual estimation process, in other words, the X and Y axes will be changed around the rotation axis. How do you solve this problem?

**Comment by pengsida** [comment]
You could handle such case by pre-processing the data. Some papers have clearly described the strategy, such as [EPOS: Estimating 6D Pose of Objects With Symmetries](https://openaccess.thecvf.com/content_CVPR_2020/papers/Hodan_EPOS_Estimating_6D_Pose_of_Objects_With_Symmetries_CVPR_2020_paper.pdf).
