### ISSUE TITLE
Questions about Two-Class or more Setting 

### ISSUE THREAD

**Issue by Divyam10** [zju3dv/clean-pvnet#265]
Hello, thanks for publishing code to this amazing paper! 

1. I am trying to the train the data for two classes as an experiment. I achieved good results by training them with Ver_Dim : 18 and Seg_Dim: 3. Even though it is multi-class it detects only one object at a time, obviously. I read the issue #57  and it that you mentioned we will have to change `ransac_voting_layer_v3` to make it generate keypoints for two classes. Can you throw some light on how to do that? 
2. As a second experiment, I am trying to train two classes using ver_dim : 36 and Seg_dim : 3. In this the vertex data for class not present in the image should be zeroes? As my data consists of only one class per image.

**Comment by pengsida** [comment]
To detect more classes of object, an easier way is to add an object detector before PVNet, which is implemented in this code.
