### ISSUE TITLE
Could not reproduce paper results

### ISSUE THREAD

**Issue by LounesDev** [zju3dv/clean-pvnet#27]
Hi,

I tried to train your network on the Ape object. So I ran the command :
`python train_net.py --cfg_file configs/linemod.yaml model ape cls_type ape` but after 200 epochs I cannot find the same results than you. I followed every steps of your tutorial.

Regards

**Comment by pengsida** [comment]
Could you provide the tensorboard curves?
https://github.com/zju3dv/clean-pvnet#tensorboard

**Comment by LounesDev** [comment]
![trainValue](https://user-images.githubusercontent.com/13978618/75661029-d9e35880-5c6c-11ea-8b05-30d596bca6e3.png)

![eval](https://user-images.githubusercontent.com/13978618/75661046-e071d000-5c6c-11ea-8bdd-f260ead548f2.png)

**Comment by pengsida** [comment]
It seems that the training totally failed.

**Comment by LounesDev** [comment]
Are there parameters that I have to set to make it work ?

**Comment by pengsida** [comment]
I am not sure. I will check it.

**Comment by LounesDev** [comment]
I also see that loss value become NaN after a large number of epochs. Somewhere between 150 & 200 epochs.

**Comment by pengsida** [comment]
I retrain the network on ape and get similar training curves.
Maybe there are some problems in the data you use for training.
I also found a bug in `python run.py --type linemod cls_type ape`, which had been fixed.
