### ISSUE TITLE
About printing 3D models

### ISSUE THREAD

**Issue by BoBoINVICTUS** [zju3dv/clean-pvnet#274]
Hello, when I checked the size of the 3D model provided in your datasets, I found that the size is very small. If I want to 3D print the object, how many times do I need to enlarge the 3D model? Or is it just any?
![216782225c38f45558d68cfe8c40731](https://github.com/zju3dv/clean-pvnet/assets/102162738/c45f5ad3-5195-4499-8bf1-d2c39cf70a8e)

**Comment by pengsida** [comment]
You could take the size as the real metric and adjust it according to your need.
