### ISSUE TITLE
run_custom() is missing from run.py

### ISSUE THREAD

**Issue by ishang3** [zju3dv/clean-pvnet#28]
I have a custom dataset for which I would like to run through Clean-pvnet. I am following the instructions to run the run.py command for the custom dataset. I get the error below. I looked through the code for run.py and run_custom() function does not exist. Any information is greatly appreciated. 

Traceback (most recent call last):
  File "run.py", line 219, in <module>
    globals()['run_'+args.type]()
KeyError: 'run_custom'

**Comment by ishangupta3** [comment]
I found the function in an older commit:

https://github.com/zju3dv/clean-pvnet/blob/48a173b08c877ce0d0957a652ae87bad6f958f31/run.py

**Comment by pengsida** [comment]
I have updated the code.
