### ISSUE TITLE
关于TPAMI期刊里的PVNet的RGBD

### ISSUE THREAD

**Issue by Huskywyh** [zju3dv/clean-pvnet#289]
思达同学您好，我想问下您在TPAMI发表的PVNet论文里，在LINEMOD数据集上的ADD指标比较中，RGB-D方法里的OURS+ICP，这个D通道是用于ICP的是吗？还是将RGBD4个通道直接作为PVNet的encoder的输入呢？

**Comment by pengsida** [comment]
用于ICP的。

**Comment by Huskywyh** [comment]
还有想问下您训练的硬件环境是什么样的，以及您训练一轮需要多长时间？（包括renders和fuse大概总共是20000张图片）

**Comment by pengsida** [comment]
我五年前训练的，不记得了。

**Comment by Huskywyh** [comment]
好吧，想问下您我现在在4张2080Ti显卡训练一轮（20000张）大概要15min，这个时间有问题吗，我感觉有点慢，是不是哪里有问题？

**Comment by pengsida** [comment]
抱歉，我没有概念。

**Comment by Huskywyh** [comment]
好吧，谢谢您的解答
