### ISSUE TITLE
add metric 和 2D projections metric总是为0

### ISSUE THREAD

**Issue by ZYLer0510** [zju3dv/clean-pvnet#290]
eta: 0:00:04  epoch: 9  step: 24681  vote_loss: 0.0092  seg_loss: 0.0038  loss: 0.0130  data: 0.3746  batch: 0.5091  lr: 0.001000  max_mem: 5039
eta: 0:00:00  epoch: 9  step: 24689  vote_loss: 0.0087  seg_loss: 0.0039  loss: 0.0126  data: 0.3749  batch: 0.5099  lr: 0.001000  max_mem: 5039
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1002/1002 [02:40<00:00,  6.25it/s]
['vote_loss: 0.0066', 'seg_loss: 0.0040', 'loss: 0.0107']
2d projections metric: 0.0
ADD metric: 0.0
5 cm 5 degree metric: 0.0
mask ap70: 0.9700598802395209
eta: 0:21:43  epoch: 10  step: 24710  vote_loss: 0.0081  seg_loss: 0.0040  loss: 0.0121  data: 0.3670  batch: 0.5037  lr: 0.001000  max_mem: 5039
eta: 0:21:32  epoch: 10  step: 24730  vote_loss: 0.0084  seg_loss: 0.0040  loss: 0.0123  data: 0.3764  batch: 0.5069  lr: 0.001000  max_mem: 5039

**Comment by ZYLer0510** [comment]
可以修改/mnt/d/zyl/VSCode/MyCode/CVPapers/clean-pvnet-master/lib/networks/pvnet/resnet18.py中decode_keypoint()方法中调用的ransac_voting_layer_v3()改为ransac_voting_layer()方法。

**Comment by monajalal** [comment]
@pengsida @ZYLer0510 

It would be great to provide reasoning why this change has fixed the issue when you get a chance for other users' clarifications. Thank you for fixing this issue.
