### ISSUE TITLE
Error ：The metric value is always zero in Command line：Test or Demo

### ISSUE THREAD

**Issue by guohaot** [zju3dv/clean-pvnet#302]
My environment： Ubuntu20、CUDA11.1、torch==1.8、python==3.7

Question：I tried Ubuntu20 to install cuda9.0, but when it runs, there will be a version mismatch problem, so I can only use cuda11.1, and then I installed requirement.txt install the remaining python package,The only point that differs is the version of CUDA version and the torch version。And I've put cat.pth in /data/model/pvnet/cat/199.pth
![2](https://github.com/zju3dv/clean-pvnet/assets/149865769/b36edb27-a411-44d1-a488-6aec5791ccda)

Error turn out： but when run command line：python run.py --type evaluate --cfg fil:configs/linemod.yaml model cat cls type cat； the all of metric is zero；
![3](https://github.com/zju3dv/clean-pvnet/assets/149865769/e596a490-0118-403c-8eb0-0e386654eb29)
I tried this solution from #283，But it didn't work
![5](https://github.com/zju3dv/clean-pvnet/assets/149865769/96f76567-f85b-409f-890b-481a7aa013c6)

Error ：when run command line：python run.py --type demo --cfg_file configs/linemod.yaml demo_path demo_images/cat；  When visualizing, the box doesn't frame the object at all。
![4](https://github.com/zju3dv/clean-pvnet/assets/149865769/bc42b5c7-ab91-4b3d-8ca6-89dd1fe87182)

I've tried a lot of other versions of CUDA and Torch, and I'm having this problem, and I really don't know how to fix it，Please help me with this, thanks

**Comment by guohaot** [comment]
I try the Issue #298，Using the version ： torch=1.12 cuda=11.6 ,then the quesion done!

**Comment by ZhuangTingT** [comment]
> I try the Issue #298，Using the version ： torch=1.12 cuda=11.6 ,then the quesion done!

did you change other code？ i have changed follow #298, but it didn't work, may you give some advice?
