### ISSUE TITLE
Can I proceed to training with the feature point that I modified?

### ISSUE THREAD

**Issue by tjdalsckd** [zju3dv/clean-pvnet#31]
After I modified the fps.txt file, I did train. 

However, the fps.txt file was modified automatically.

**Comment by pengsida** [comment]
I do not get the problem.

**Comment by tjdalsckd** [comment]
run.py 

def run_custom():
    from tools import handle_custom_dataset
    data_root = 'data/custom'
    handle_custom_dataset.sample_fps_points(data_root) 
    handle_custom_dataset.custom_to_coco(data_root)

**Comment by pengsida** [comment]
`handle_custom_dataset.sample_fps_points(data_root)` will generate the fps points.
Since the fps algorithm randomly sample the points, so the content of fps.txt will be different if you run the `python run.py --type custom` multiple times.

**Comment by tjdalsckd** [comment]
Thank you for your reply.
