### ISSUE TITLE
Custom Dataset Training 

### ISSUE THREAD

**Issue by ishangupta3** [zju3dv/clean-pvnet#32]
Hello,

I have created a custom dataset (the dataset is in the exact format as the linemod dataset). These are some errors I am facing when running:

python run.py --type custom

**Error 1**
Traceback (most recent call last):
  File "run.py", line 226, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 222, in run_custom
    handle_custom_dataset.custom_to_coco(data_root)
  File "/home/ubuntu/clean-pvnet/tools/handle_custom_dataset.py", line 89, in custom_to_coco
    renderer = OpenGLRenderer(model_path)
  File "/home/ubuntu/clean-pvnet/lib/utils/linemod/opengl_renderer.py", line 21, in __init__
    self.model = self.load_ply(self.ply_path)
  File "/home/ubuntu/clean-pvnet/lib/utils/linemod/opengl_renderer.py", line 42, in load_ply
    line = f.readline().rstrip('\n').rstrip('\r') # Strip the newline character(s)
  File "/home/ubuntu/anaconda3/envs/pvnet/lib/python3.7/codecs.py", line 322, in decode

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 292: invalid continuation byte

I was able to bypass this error by running the code on a Python 2 environment and saving the dictionary into a .npz file then manually loading the dictionary in the python 3 environment. But essentially the function in opengl_renderer.py ---- **def load_ply(self, ply_path):** only works in a python 2 environment. 

**Error 2** (Currently stuck on) 
When running the train command:

**python train_net.py --cfg_file configs/linemod.yaml train.dataset CustomTrain test.dataset CustomTrain model mycat train.batch_size 4**

I get this error: FileNotFoundError: [Errno 2] No such file or directory: 'data/linemod/cat/cat.ply'

But I am not trying to use a cat, I have my own .ply file called model.ply which is stored in the directory structure mentioned in the repo like below:

├── /path/to/dataset
│   ├── model.ply
│   ├── camera.txt
│   ├── rgb/
│   │   ├── 0.jpg
│   │   ├── ...
│   │   ├── 1234.jpg
│   │   ├── ...
│   ├── mask/
│   │   ├── 0.png
│   │   ├── ...
│   │   ├── 1234.png
│   │   ├── ...
│   ├── pose/
│   │   ├── 0.npy
│   │   ├── ...
│   │   ├── 1234.npy
│   │   ├── ...
│   │   └──

Any information is greatly appreciated.

**Comment by pengsida** [comment]
1. I can use the code to load ply file with python 3.
2. Previous code did not provide the testing on the custom data. I added the testing code just now and updated the corresponding docs https://github.com/zju3dv/clean-pvnet#training-on-the-custom-object

**Comment by ishangupta3** [comment]
Thank you @pengsida, I am able to start training.

I appreciate all your help. Hope you have a great day.

**Comment by cgm6666** [comment]
> 你好，
> 
> 我创建了一个自定义数据集（该数据集的格式与linemod数据集的格式相同）。这些是我在运行时遇到的一些错误：
> 
> python run.py --type自定义
> 
> **错误1**
> 回溯（最近通话最后一个）：
> 文件“run.py”，线路226，在
> 全局（）'跑_' + args.type
> 文件“run.py”，生产线222，在run_custom
> handle_custom_dataset.custom_to_coco（data_root）
> 文件“ /home/ubuntu/clean-pvnet/tools/handle_custom_dataset.py”，第89行，在custom_to_coco
> 渲染器= OpenGLRenderer（model_path）
> 文件“ /home/ubuntu/clean-pvnet/lib/utils/linemod/opengl_renderer.py”中，第21行，在**初始化中**
> self.model = self.load_ply（self.ply_path）
> 文件“ /home/ubuntu/clean-pvnet/lib/utils/linemod/opengl_renderer.py”，第42行，在load_ply
> 行= f.readline（ ）.rstrip（'\ n'）。rstrip（'\ r'）＃删除换行符
> 解码时的文件“ /home/ubuntu/anaconda3/envs/pvnet/lib/python3.7/codecs.py”，第322行
> 
> UnicodeDecodeError：'utf-8'编解码器无法解码位置292中的字节0xf3：无效的连续字节
> 
> 通过在Python 2环境中运行代码并将字典保存到.npz文件，然后在python 3环境中手动加载字典，我能够绕过此错误。但是本质上，opengl_renderer.py中的函数---- **def load_ply（self，ply_path）：**仅在python 2环境中有效。
> 
> **错误2**（当前卡住）
> 运行train命令时：
> 
> **python train_net.py --cfg_file configs / linemod.yaml train.dataset CustomTrain test.dataset CustomTrain模型mycat train.batch_size 4**
> 
> 我收到此错误：FileNotFoundError：[Errno 2]没有这样的文件或目录：'data / linemod / cat / cat.ply'
> 
> 但是我不是在尝试使用猫，我有一个名为model.ply的.ply文件，该文件存储在回购中提到的目录结构中，如下所示：
> 
> ├──/路径/到/数据集
> │├──model.ply
> │├──camera.txt
> │├──RGB /
> ││├──0.jpg
> ││├──...
> ││├── 1234.jpg
> ││├──...
> │├──面膜/
> ││├──0.png
> ││├──...
> ││├──1234.png
> ││├──...
> │ ├──姿势/
> ││├──0.npy
> ││├──...
> ││├──1234.npy
> ││├──...
> ││└──
> 
> 任何信息都将不胜感激。

Hi, how did you create your dataset?
