### ISSUE TITLE
Visualization saving

### ISSUE THREAD

**Issue by ishangupta3** [zju3dv/clean-pvnet#33]
Hello, 

I have successfully completed training of the model; thank you for your support in that. I am running the code on an AWS instance; I am unable to view the visualization. Where would be the proper file to insert code to save the plots into a directory?

Would it be here?
https://github.com/zju3dv/clean-pvnet/blob/07e7c09e80cde938e013d8bc2880605add33a0ce/lib/visualizers/ct.py#L16

The same thing for evaluate, where would be the file where I can alter it to save the evaluations to a file, because I am unable to view anything in a remote cluster.

**Comment by pengsida** [comment]
Revise the code to `plt.savefig()` https://github.com/zju3dv/clean-pvnet/blob/master/lib/visualizers/pvnet.py#L48
The evaluation results are just words. If you want to save, add `np.save()` at here https://github.com/zju3dv/clean-pvnet/blob/master/lib/evaluators/custom/pvnet.py#L112

**Comment by ishangupta3** [comment]
Thanks, I will try.

**Comment by KatCla** [comment]
> plt.savefig()

Hello, 
I am running your code on google colab and I am also unable to view the visualization.

Currently I am working with the pretrained models of LINEMOD. As you suggested I added the line _plt.savefig()_ here: /content/clean-pvnet/lib/visualizers/linemod/pvnet.py#L46 (= at the end of _def visualize(self, output, batch)_)

Now it's creating an image in my clean_pvnet folder but it is blank/empty.

Do you have an suggestion how to get the full visualisation?

best regards

**Comment by pengsida** [comment]
cv2.imwrite()
