### ISSUE TITLE
May I pause training and continue training next time？

### ISSUE THREAD

**Issue by debugAllTheTime** [zju3dv/clean-pvnet#34]
May I pause training and continue training next time,due to the limitation I could use for training.
Thank you !

**Comment by pengsida** [comment]
Yes. The training option `resume True` allows us to resume the training.
Be careful to use `resume False`, since it will restart the training and delete the models.

**Comment by debugAllTheTime** [comment]
you mean when i want to resume the training. just retype the following command
 $ python train_net.py --cfg_file configs/linemod.yaml model mycat cls_type cat
What command should I modify?
thanks for your reply

**Comment by pengsida** [comment]
`python train_net.py --cfg_file configs/linemod.yaml model mycat cls_type cat resume True`

**Comment by debugAllTheTime** [comment]
ok thank you so much！
