### ISSUE TITLE
Question: Custom Test Data 

### ISSUE THREAD

**Issue by ishangupta3** [zju3dv/clean-pvnet#35]
Hello, 

I would like to create a brand new custom dataset to test without the aruco markers around the object to understand generalization. I have been going through the code, and it seems like the custom.yaml file and the dataset catalog are the necessary files where I have to add / change. 

I am also assuming for visualization / evaluation only inference is being done on a pre - trained model with a simple RGB image as the input. 

After creating this dataset, and adding it to the dataset catalog, what details should I be aware of. For example do I need an ann file or a value for 'split'? Is is fine to assume that inference on a pretrained model would only require a RGB image?

Also, why does the inference line in these 2 functions differ? 

def run_evaluate():
.......
output = network(inp)

def run_visualize():
.........
  output = network(batch['inp'], batch)

**Comment by pengsida** [comment]
If you want to evaluate the trained model, you need an ann file.
It is OK to assume that the inference requires only an RGB image.
There is no difference between `network(batch['inp'])` and `network(batch['inp'], batch)`.

**Comment by ishangupta3** [comment]
What would be the best way to generate the ann file from my own rgb images?

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/blob/master/tools/handle_custom_dataset.py#L43

**Comment by ishangupta3** [comment]
@pengsida This method would require me to collect another complete dataset. But I am only interested in running inference on a dataset containing RGB images, how would it be possible to refactor the code to simply run inference on a RGB image:

output = network(RGB IMAGE PATH)

I understand by doing so, I will not be able to visualize the ground truth; but the inference visualize should be self explanatory if the pose is incorrect or correct. 

The goal for me is to then get the output of the pre-trained model which will be the 2d keypoints, and visualize them accordingly to understand the pose. Looking through the code it seems you are able to compute the pose by doing pnp, but the inference only outputs the 2d keypoints. Does the pretrained model output a combination of 2d/3d keypoints?

**Comment by pengsida** [comment]
The 3d keypoints are predefined.

**Comment by ishangupta3** [comment]
I would like to create a custom real time demo using  on a pretrained model that I trained on. In this situation I would not have the 3d key points, in real time. How do you recommend to create a real time demo using the model I trained?

**Comment by pengsida** [comment]
This algorithm requires the pre-defined 3d keypoints.
If you do not have 3d keypoints, you cannot even train the network.

**Comment by ishangupta3** [comment]
Even for inference?

**Comment by ishangupta3** [comment]
I would like to have a webcam run the pre trained model in real time, detecting the pose of the object I used.

**Comment by pengsida** [comment]
If you have the pre-defined 3d keypoints, of course you can use these 3d points during inference.

**Comment by ishangupta3** [comment]
Got it, the 3d keypoints would just be from the .ply file right? This would be the same set of 3d keypoints for all inferences.

**Comment by pengsida** [comment]
Yes.

**Comment by ishangupta3** [comment]
Thank you @pengsida
