### ISSUE TITLE
File:diameter.txt in Custom/pvnet.py 

### ISSUE THREAD

**Issue by kevin860213** [zju3dv/clean-pvnet#36]
What does the diameter.txt means ? Is that the custom object's size? Thank your help

**Comment by pengsida** [comment]
diameter.txt stores the value of the object's diameter.

**Comment by kevin860213** [comment]
How can i get that value?

**Comment by pengsida** [comment]
I am not sure.
I only evaluated the ADD metric on the public datasets.

**Comment by kevin860213** [comment]
OK.
Thanks your help.

**Comment by KAOeric** [comment]
Sorry @kevin860213  did you solve the problem already? 
How did you solve this problem, I have the same problem like yours

**Comment by RoyAmoyal** [comment]
> object's diameter

same here, any idea?
