### ISSUE TITLE
Infer on LINEMOD with tless model

### ISSUE THREAD

**Issue by kashyap92** [zju3dv/clean-pvnet#38]
Hello @pengsida ,
is it possible to infer on linemod dataset with pretrained tless weights? 

Regards,
Mahesh kashyap.

**Comment by pengsida** [comment]
No.

**Comment by kashyap92** [comment]
Hello @pengsida,
Could you please brief about the metrics.

vsd metric: 0.0
adi metric: 0.37823490378234903
5 cm 5 degree metric: 0.15228931652289315

Regards,

**Comment by pengsida** [comment]
The vsd metric and adi metric can be found in https://github.com/thodan/sixd_toolkit/blob/master/doc/sixd_2017_measuring_error.pdf
You could google about the 5cm 5 degree metric.
