### ISSUE TITLE
Loading Pre-trained custom model 

### ISSUE THREAD

**Issue by ishangupta3** [zju3dv/clean-pvnet#39]
I am following the project structure and the custom.yaml file, I would like to load the pre trained model myself. Before loading the model, I would need to instantiate the class like this below:

model = TheModelClass(*args, **kwargs)

According to the custom.yaml file; the '**task' is pvnet**, but the **network is res**. 
 clean-pvnet/lib/networks/pvnet

Which class network would the appropriate one to use when loading the custom model in pytorch?

Would it be this one: Resnet18?
https://github.com/zju3dv/clean-pvnet/blob/07e7c09e80cde938e013d8bc2880605add33a0ce/lib/networks/pvnet/resnet18.py 

Or this one: PoseResNet?
https://github.com/zju3dv/clean-pvnet/blob/07e7c09e80cde938e013d8bc2880605add33a0ce/lib/networks/resnet.py

My end goal is to just take my pretrained model that I trained; and create a brand new inference code pipeline, where I can customize it with my own usecase.

**Comment by pengsida** [comment]
If you want to train the pvnet on your custom data, please follow these steps: https://github.com/zju3dv/clean-pvnet#training-on-the-custom-object

**Comment by ishangupta3** [comment]
I already have the custom trained model already trained. 

I would like to load it myself, I was asking which network class I should use to load the model.

**Comment by ishangupta3** [comment]
Pytorch requires you to set up model in this format: **(I already have the model trained on my own custom dataset) I would like to load the model myself.**

model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load(PATH))

**Comment by pengsida** [comment]
`python run.py --type visualize --cfg_file configs/custom.yaml`
The network is defined in `configs/custom.yaml`.
The network is https://github.com/zju3dv/clean-pvnet/blob/master/lib/networks/pvnet/__init__.py#L5
