### ISSUE TITLE
About tless dataset

### ISSUE THREAD

**Issue by g185211** [zju3dv/clean-pvnet#40]
Hi,thanks your perfect work.
I want to know "when you use TLESS dataset, how did you settle the original dataset?" Can I use the same way like the custom dataset to handle the TLESS dataset?
Thanks!

**Comment by pengsida** [comment]
I have provided the processed tless dataset.
![image](https://user-images.githubusercontent.com/11582122/76866714-7af22600-689f-11ea-87d8-ed1bbc776aec.png)
