### ISSUE TITLE
Model output segmentation classes & ver_dim  - LINEMOD

### ISSUE THREAD

**Issue by joydeepmedhi** [zju3dv/clean-pvnet#45]
Hi,
From what I have observed from the code, every class has separate models, which seems contradicting to the paper. Can you please explain this if I have understood correctly? 

Why there is separate model for each class instead of 1 model ? 

> Assuming there are C classes of objects and K keypoints for each class, PVNet takes as input the H × W × 3 image, processes it with a fully convolutional architecture, and outputs the H ×W ×(K ×2×C) tensor representing unit vectors and H×W ×(C+1) tensor representing class probabilities.

Moreover, for LineMOD ver_dim is taken as 18. Should it not be 8*2 = 16, for K = 8 key points.

Thnaks.

**Comment by pengsida** [comment]
Yes, every class has a separate model.
The number of keypoints is 9, including a center point.

**Comment by joydeepmedhi** [comment]
Thanks for the reply.
Is there any specific reason to have separate models for each class instead of one model with all the classes?

**Comment by pengsida** [comment]
Previous methods trained separate models for each class.
