### ISSUE TITLE
Tless renderings for training

### ISSUE THREAD

**Issue by fransonf** [zju3dv/clean-pvnet#46]
Hi! I'm currently training the network on the prepared Tless dataset and have a question about the renderings.

As I've understood it you add renderings to the training data as well which can be found in /data/tless/renders. I noticed however that there are no renderings for some of the objects in the dataset. Is this correct or have I failed a step where they were supposed to be added?
![yes](https://user-images.githubusercontent.com/36590759/77043322-97848000-69bd-11ea-9a2e-00baf21e0e8c.png)

**Comment by pengsida** [comment]
Yes, this is correct.
I did not render images for certain objects.
