### ISSUE TITLE
python setup.py build_ext --inplace

### ISSUE THREAD

**Issue by g185211** [zju3dv/clean-pvnet#47]
when I compiled "cd ../nn     python setup.py build_ext --inplace",I met some problems".
1.gcc: error: /usr/local/cuda-9.0/lib64/libcudart.so: No such file or directory
So, I found my cuda is 10.0.130,   and I change <setup.py>-cuda 9.0 to cuda 10.0.
Then, I met the problem2 again

2.In file included from tmpxft_00001f84_00000000-4_nearest_neighborhood.cudafe1.stub.c:1:0:
/tmp/tmpxft_00001f84_00000000-4_nearest_neighborhood.cudafe1.stub.c: In function ‘void __device_stub__Z27findNearestPoint3DIdxKernelPfS_Piiiii(float*, float*, int*, int, int, int, int)’:
/tmp/tmpxft_00001f84_00000000-4_nearest_neighborhood.cudafe1.stub.c:11:153: error: ‘__args_arr’ was not declared in this scope
 _par1, int *__par2, int __par3, int __par4, int __par5, int __par6){__cudaSetup
                                                                     ^
/tmp/tmpxft_00001f84_00000000-4_nearest_neighborhood.cudafe1.stub.c:11:164: error: ‘__args_idx’ was not declared in this scope
 *__par2, int __par3, int __par4, int __par5, int __par6){__cudaSetupArgSimple(_
                                                                     ^
In file included from tmpxft_00001f84_00000000-4_nearest_neighborhood.cudafe1.stub.c:1:0:
/tmp/tmpxft_00001f84_00000000-4_nearest_neighborhood.cudafe1.stub.c: In function ‘void __device_stub__Z27findNearestPoint2DIdxKernelPfS_Piiiii(float*, float*, int*, int, int, int, int)’:
/tmp/tmpxft_00001f84_00000000-4_nearest_neighborhood.cudafe1.stub.c:1:162: error: ‘__args_arr’ was not declared in this scope
/tmp/tmpxft_00001f84_00000000-4_nearest_neighborhood.cudafe1.stub.c:1:173: error: ‘__args_idx’ was not declared in this scope
generating ./_ext.c
(already up-to-date)
the current directory is '/home/yang/clean-pvnet-master/lib/csrc/nn'
running build_ext
building '_ext' extension
gcc -pthread -B /home/yang/anaconda3/envs/pvnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yang/anaconda3/envs/pvnet/include/python3.6m -c _ext.c -o ./_ext.o
gcc -pthread -shared -B /home/yang/anaconda3/envs/pvnet/compiler_compat -L/home/yang/anaconda3/envs/pvnet/lib -Wl,-rpath=/home/yang/anaconda3/envs/pvnet/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_ext.o src/nearest_neighborhood.cu.o /usr/local/cuda-10.0/lib64/libcudart.so -lstdc++ -o ./_ext.cpython-36m-x86_64-linux-gnu.so

Must I use cuda9.0?

**Comment by pengsida** [comment]
I did not use cuda-10.0 to compile the program, so I do not know what caused this problem.
