### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by g185211** [zju3dv/clean-pvnet#49]
Could you please add the visualization about TLESS.
Very Thanks!

**Comment by pengsida** [comment]
I have updated the code: https://github.com/zju3dv/clean-pvnet#visualization-on-tless

**Comment by g185211** [comment]
Thank you very much!
But I found that the muti-object result is not good, what about your experience?

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/77243629-2e17a200-6c47-11ea-8b28-3162d9d5e797.png)

**Comment by g185211** [comment]
I follow your steps, but it's very strang that my VSD metric=0 all the time, including the train and the test

**Comment by pengsida** [comment]
Are you sure that you loaded the pre-trained model correctly?

**Comment by g185211** [comment]
Yes, and it is 0 during training

**Comment by pengsida** [comment]
Since the information is not enough, I do not what caused the problem.

**Comment by Ji-Hu** [comment]
I have same issue 

my command : --type evaluate --cfg_file configs/tless/tless_06.yaml model tless_models/tless_06

and i used pre-trained model 

I would be grateful if you could check your code once more.

![Screenshot from 2020-03-24 16-05-30](https://user-images.githubusercontent.com/32670168/77397668-622ac880-6de9-11ea-9ae1-0b1b053a7c6b.png)

**Comment by pengsida** [comment]
The output is correct.
If you want to test the vsd metric, use `python run.py --type evaluate --cfg_file configs/tless/tless_01.yaml test.vsd True`.

**Comment by Ji-Hu** [comment]
oh! 
Thank you very much
