### ISSUE TITLE
About CUDA path 

### ISSUE THREAD

**Issue by firstdeep** [zju3dv/clean-pvnet#50]
Hello. 

I changed GPU to RTX2080 series this time.
Therefore, cuda 10.0 was installed. RTX does not support cuda 9.0.
But there is a problem setting the ransac voting.

Is there any place to modify cuda path other than the following?
https://github.com/zju3dv/clean-pvnet/blob/master/lib/csrc/nn/setup.py#L3

Always be careful of infection and hope nothing happens.

Regards,
David

**Comment by pengsida** [comment]
Replace all `cuda-9.0` with `cuda-10` in this file.

**Comment by firstdeep** [comment]
Does this mean the file?
https://github.com/zju3dv/clean-pvnet/blob/master/lib/csrc/nn/setup.py#L3
https://github.com/zju3dv/clean-pvnet/blob/master/lib/csrc/nn/setup.py#L19

Or do you mean another file?

**Comment by pengsida** [comment]
Yes.

**Comment by firstdeep** [comment]
cheers

Thanks david.
