### ISSUE TITLE
About the training time and the number of training data per epoch 

### ISSUE THREAD

**Issue by Ji-Hu** [zju3dv/clean-pvnet#51]
Thank you so much for sharing your code.

I'm running your Tless code.
I think you use (10,000(synthetic images) + 1296(object rgb images)) data per epoch to running your Tless code. 
Is that right?

I wonder your development environment and the time it takes to code.

**Comment by pengsida** [comment]
> I wonder your development environment and the time it takes to code.
What do you mean?

**Comment by Ji-Hu** [comment]
Your development environment, such as how many GPUs are used,
I am curious about the time it takes to progress the training.

**Comment by pengsida** [comment]
4 gpus.
About 8 hours.

**Comment by Ji-Hu** [comment]
Thanks!
