### ISSUE TITLE
Synthetic images training

### ISSUE THREAD

**Issue by fransonf** [zju3dv/clean-pvnet#53]
Hello! Are the synthetic images for Tless used automatically when training or is that an option? Sorry if this is written somewhere here or in the paper but I can't find it.

**Comment by pengsida** [comment]
Yes, the synthetic images are loaded automatically.
If you want to filter them, you could use the data type in the annotation: https://github.com/zju3dv/clean-pvnet/blob/9c9800bacffa616a6a08fb1eb17c3ceec9fe9de2/lib/datasets/tless/tless_to_coco.py#L177

**Comment by fransonf** [comment]
Thanks a lot for answering.
