### ISSUE TITLE
Tless using only synthetic data

### ISSUE THREAD

**Issue by fransonf** [zju3dv/clean-pvnet#54]
Hello! I'm currently working on domain adaptation for synthetic data in pose estimation tasks. I have two questions:

1. When training for example Tless object 15, how much of the total training data is real images and renderings respectively? (approximately)

2. Is it possible to exclude the real images when training? What would be the most convenient way of using only renderings in training?

Thanks in advance!

**Comment by pengsida** [comment]
1. About 5000 synthetic images and 1000 real images.
2. Yes. If you want to filter them, you could use the data type in the annotation: https://github.com/zju3dv/clean-pvnet/blob/9c9800bacffa616a6a08fb1eb17c3ceec9fe9de2/lib/datasets/tless/tless_to_coco.py#L124

**Comment by fransonf** [comment]
Thanks for answering however it's still not clear to me what I need to do to only train with synthetic images. Can you please give some more instructions regarding (2)? I'm going to run your renderings through a generative network and use the new renderings to train PVNet. Something like this (background has been removed here):

Before 
![image](https://user-images.githubusercontent.com/36590759/77656966-e5c4f080-6f74-11ea-9d51-7874cb0b16f9.png)  
After 
![image](https://user-images.githubusercontent.com/36590759/77657000-f4aba300-6f74-11ea-8532-52467df5cb5c.png)

So the pose will hopefully be the same before and after the generative part. I'm just simply gonna use the mask to insert the "new" object in the "old" background and use the same annotation. Maybe I can just remove all the real images or something.

Thanks again.

**Comment by pengsida** [comment]
Filter `img_ids` that contains `real` type annotation at here https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/tless_train/pvnet.py#L41

**Comment by fransonf** [comment]
Cheers!

**Comment by firstdeep** [comment]
Hello
Please let me know how to filter through the code?
I don't know how to access the annotation file in this line 
https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/tless_train/pvnet.py#L41

Thank you

**Comment by pengsida** [comment]
You could learn about the coco api.
Use the following code to access the annotation file:
```
ann_ids = self.coco.getAnnIds(imgIds=img_id)
anno = self.coco.loadAnns(ann_ids)[0]
```

**Comment by fransonf** [comment]
@pengsida Sorry to bring this up again but I haven't got it to work yet, I'm quite new to this type of stuff. I don't know how to properly remove all the real images from the training. Would returning 0 in `def record_real_ann(model_meta, img_id, ann_id, images, annotations):` in `/lib/datasets/tless/tless_to_coco.py` do it? Or would it completely ruin the training?

**Comment by fransonf** [comment]
ann_ids = self.coco.getAnnIds(imgIds=self.img_ids)
        anno = self.coco.loadAnns(ann_ids)

        for idx in range(0, len(ann_ids)):
            if anno[idx]['type'] == 'real':
                anno[idx].remove

Something like this? Not sure if `.remove` is the correct thing to do here.

**Comment by fransonf** [comment]
ann_ids = self.coco.getAnnIds(imgIds=self.img_ids)
        anno = self.coco.loadAnns(ann_ids)
        
        real_ids = []
        for idx in range(len(self.img_ids)):
            if anno[idx]['type'] == 'real': 
                real_ids.append(idx)

        new_ids = np.delete(self.img_ids, real_ids)
        self.img_ids = new_ids

This seems to work.

**Comment by pengsida** [comment]
Your code seems to work. You could also use the following code to filter the synthetic annotations:
```
new_ids = []
for img_id in self.img_ids:
    ann_ids = self.coco.getAnnIds(imgIds=img_id)
    anno = self.coco.loadAnns(ann_ids)[0]
    if anno['type'] == 'real':
        new_ids.append(img_id)
self.img_ids = np.array(sorted(new_ids))
```

**Comment by fransonf** [comment]
Thanks. Is the performance expected to drop significantly using only renderings?

**Comment by pengsida** [comment]
I don't know. I didn't train the network using only the rendering data.
