### ISSUE TITLE
Clean-PVnet issue

### ISSUE THREAD

**Issue by 545464598** [zju3dv/clean-pvnet#55]
Hello, may I ask what happened when running the program."python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat“.The error is as follows: The File "/ home/yanhao/path/to/clean - pvnet/lib/utils/net_utils py", line 312, in load_network
PTHS = [int(PTH. Split ('.')[0]) for PTH in os.listdir(model_dir) if 'PTH' in PTH]
The File "/ home/yanhao/path/to/clean - pvnet/lib/utils/net_utils py", line 312, in the < listcomp >
PTHS = [int(PTH. Split ('.')[0]) for PTH in os.listdir(model_dir) if 'PTH' in PTH]
ValueError: invalid literal for int() with base 10: 'cat_199', my Python version is 3.6.2

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/77750560-f6ea2c00-705e-11ea-9718-dc98a885fbda.png)

**Comment by 545464598** [comment]
Oh,thanks! I forget to change the name of the file.
