### ISSUE TITLE
The question of ver_dim and seg_dim 

### ISSUE THREAD

**Issue by kevin860213** [zju3dv/clean-pvnet#57]
Sorry, i saw their has an issue https://github.com/zju3dv/clean-pvnet/issues/13. You said seg_dim means the number of object classes, and ver_dim is seg_dim * 2 * num_keypoints. So i want to try do the multi-object, but i saw your code https://github.com/zju3dv/clean-pvnet/blob/master/lib/config/config.py. 
_heads_factory = {
    'pvnet': CN({'vote_dim': 18, 'seg_dim': 2}),
    'ct': CN({'ct_hm': 30, 'wh': 2})
}
It shows that the seg_dim is two , so it means that it has two classes?

**Comment by pengsida** [comment]
A foreground channel and a background channel.

**Comment by kevin860213** [comment]
Ok, I got it. So I need to change the seg_dim to 4 and vote_dim to 36 when I have two classes?

**Comment by pengsida** [comment]
It will get too costly.
You could change the seg_dim to 3 (a background class and two classes) and vote_dim to 18 (use segmentation to classify pixels).

**Comment by kevin860213** [comment]
Ok, I will try it. Thanks your help.

**Comment by kevin860213** [comment]
Sorry, i have another question. In this way, it can detect two objects' mask. But it only can produce nine keypoints? If i want to get two objects' keypoints , i still need to change vote_dim to 36?

**Comment by pengsida** [comment]
The network can output two objects' keypoints using 18 channels.
Using the objects' mask, we obtain the object pixels and use them to vote keypoints belonging to a specific object.

**Comment by kevin860213** [comment]
So should i need to chang the value in ransac_voting?(https://github.com/zju3dv/clean-pvnet/blob/36e2965fe2ae5763ee57c89a34dd17c4b203793b/lib/networks/pvnet/resnet18.py#L75)
Because in the seg_dim 3 and vote_dim 18 ,it only produce 9 kepoints.  So It can't detect the two objects at the same time?

**Comment by pengsida** [comment]
Yes, you need to revise the code.
