### ISSUE TITLE
Where is the trained model?

### ISSUE THREAD

**Issue by BryceQing** [zju3dv/clean-pvnet#59]
Hello, I want to know after training the model with PVnet, where I can find the model like 199.pth. I have trained on the demo dataset(cat) and configed the model name with mycat but I don't find the output model after training, is there I do something wrong?

**Comment by pengsida** [comment]
If your model name is new_cat, the model directory is data/model/pvnet/new_cat.

**Comment by BryceQing** [comment]
OK, I will check it again. Thanks a lot!

**Comment by BryceQing** [comment]
I noticed that you have set the save milestone at 5 and my test is only set epoch to 1. It's my incaution🤣
