### ISSUE TITLE
关于model.ply

### ISSUE THREAD

**Issue by shanniruo** [zju3dv/clean-pvnet#61]
你好，感谢你优秀的工作。
当我使用你提供的objectdatasetTools制作数据集时，我在第四步和第六步生成了两个ply文件，其中第六步运行create_label_files.py 代码时生成的是二进制文件。我该使用哪个ply文件作为model.ply呢？

**Comment by pengsida** [comment]
我没有用过objeectdatasetTools，我也不知道。
你可以看看哪个文件是正确的ply格式。

**Comment by shanniruo** [comment]
应该是那个二进制表示的ply文件是model.ply。但是是二进制文件，是否我运行把二进制文件转化为文本文件的代码即可?------------------ 原始邮件 ------------------
发件人: "pengsida"<notifications@github.com>
发送时间: 2020年4月10日(星期五) 晚上9:58
收件人: "zju3dv/clean-pvnet"<clean-pvnet@noreply.github.com>;
抄送: "shanniruo"<997354181@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zju3dv/clean-pvnet] 关于model.ply (#61)




 
我没有用过objeectdatasetTools，我不知道。
 你可以看看哪个文&#x4EF6;是正确的ply格式。
 
&mdash;

**Comment by pengsida** [comment]
我不知道。你可以参考代码提供的custom dataset里的model.ply的格式。

**Comment by shanniruo** [comment]
好的，感谢回答。------------------ 原始邮件 ------------------
发件人: "pengsida"<notifications@github.com>
发送时间: 2020年4月10日(星期五) 晚上10:18
收件人: "zju3dv/clean-pvnet"<clean-pvnet@noreply.github.com>;
抄送: "shanniruo"<997354181@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zju3dv/clean-pvnet] 关于model.ply (#61)




 
我不知道。你可以参考代码提供的custom dataset里的model.ply的格式。
 
&mdash;

**Comment by shanniruo** [comment]
@pengsida 你好，关于model.py的制作，还有其他办法吗？model.py与pose应该需要满足特定的对应关系，你有其他推荐的工具可以制作这两个文件吗？

**Comment by pengsida** [comment]
我没有推荐的工具。我们也很难重建出一个好的3d model。

**Comment by shanniruo** [comment]
@pengsida 关于检测结果的可视化，如何以一个视频的形式显示呢？并像cv2.waitkey()那样，可以设置每张图片的存在时间。plt库是否也有类似的方法？感谢回答

**Comment by pengsida** [comment]
opencv可以实现，plt我没试过。具体可以谷歌。

**Comment by shanniruo** [comment]
好的，谢谢------------------ 原始邮件 ------------------
发件人: "pengsida"<notifications@github.com>
发送时间: 2020年4月15日(星期三) 中午11:51
收件人: "zju3dv/clean-pvnet"<clean-pvnet@noreply.github.com>;
抄送: "shanniruo"<997354181@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [zju3dv/clean-pvnet] 关于model.ply (#61)




 
opencv可以实现，plt我没试过。具体可以谷歌。
 
&mdash;

**Comment by shanniruo** [comment]
@pengsida 关于三维重建的工具如elasticfusion是否可以用来制作相应的model.py?我看一些demo效果很好，你对此有了解吗？

**Comment by pengsida** [comment]
实际上不太好用，可能要专业做这个的能重建出来吧，至少要把背景都扣掉。

**Comment by shanniruo** [comment]
关于扣掉背景可以用meshlab实现,除此之外还有需要考虑的点吗？

**Comment by pengsida** [comment]
我指的是把图片的背景扣掉再输入。
我没有拿它成功重建过，不知道还要考虑什么。

**Comment by shanniruo** [comment]
好的，感谢回答------------------ 原始邮件 ------------------
发件人: "pengsida"<notifications@github.com>
发送时间: 2020年4月16日(星期四) 上午10:23
收件人: "zju3dv/clean-pvnet"<clean-pvnet@noreply.github.com>;
抄送: "shanniruo"<997354181@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [zju3dv/clean-pvnet] 关于model.ply (#61)




 
我指的是把图片的背景抠掉再输入。
 我没有拿它成功重建过，不知道还要考虑什么。
 
&mdash;

**Comment by shanniruo** [comment]
作者你好，我已经使用自制数据集训练好了结果，但是我想用rgb图片做测试，我自己尝试了却没有成功，我应该如何做？

**Comment by shanniruo** [comment]
我或许应该仿照train.json文件用测试图片制作新的train.json文件？但是这相当于我又制作了新的数据集？请指教一下

**Comment by pengsida** [comment]
可以提供更多的信息吗，我不知道你的具体问题。

**Comment by shanniruo** [comment]
当运行run_visualize时，原始的代码好像是在训练集上做的测试。我想要用一组新的rgb图做测试

**Comment by pengsida** [comment]
可以生成一个test.json，然后更改这一行文件路径：https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/dataset_catalog.py#L84

**Comment by shanniruo** [comment]
可是运行handle_custom_dataset.custom_to_coco函数时，我并没有pose，mask等信息，只有rgb图片,无法生成test.json.

**Comment by pengsida** [comment]
可以生成test.json，只是同时还要写一个额外的`dataset`，可以参考`lib/datasets/tless_test/pvnet.py`.

**Comment by shanniruo** [comment]
抱歉我没有能够理解。我保留了rgb图片，fps.txt与model.ply想尝试用python run.py --type custom生成test.json。这种做法似乎不行。毫无疑问在运行到这里时出错https://github.com/zju3dv/clean-pvnet/blob/master/tools/handle_custom_dataset.py#L110
我并不知道lib/dataset/custom_test的作用，因此，关于如何仿写，可以说的更详细一点吗？或者我应该还是取名custom把原本的文件夹替换掉吧

**Comment by pengsida** [comment]
1. 是的，用默认的`python run.py --type custom`，如果没有pose和mask无法生成test.json，需要你改一下里面的相关代码。
2. 代码会在[这里](https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/make_dataset.py#L19)调用相应的Dataset类，你需要写一个Dataset类来读取test.json。我有写了类似的tless_test，在`lib/datasets/tless_test/pvnet.py`。

**Comment by shanniruo** [comment]
抱歉还是得请教你一下。关于test.json文件，我注释了https://github.com/zju3dv/clean-pvnet/blob/master/tools/handle_custom_dataset.py 其中的65到71行，也去掉了字典中相应的部分，可以生成test.json。我不确定这种做法是否正确。
关于dataset类，我参考lib/datasets/custom/pvnet.py 。我仅仅改动的部分为 关于read_data这个函数，仅仅使他返回inp 。 __getitem__这个函数， 使之返回ret = {'inp': inp,'img_id': img_id, 'meta': {}}。
当我运行可视化代码时，返回的报错是TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'NoneType'>。我没有理解，我并没有改变返回值的数据类型。
抱歉五一假期还多次打扰你。祝生活愉快

**Comment by shanniruo** [comment]
我已经解决它了。但是用其他图片测试的结果，一言难尽

**Comment by pengsida** [comment]
可能是训练的问题。

**Comment by shanniruo** [comment]
训练可能具体是哪里的问题呢？我在训练集中评估结果为0.9左右，效果还好。可是我只使用了300来张图片做训练，训练集本身图片不多，与测试集图片分布有一些差别应该是一个原因。请问，是否需要增加一些额外的数据增强方法？或者，应该是其他做法？

**Comment by pengsida** [comment]
300张图片挺多的。
如果测试图片和训练图片差别比较大，可能需要适当的data augmentation。
如果测试图片和训练图片的背景差别比较大，建议先做detection。

**Comment by shanniruo** [comment]
再次观察了图片，应该是背景的原因。感谢回答

**Comment by shanniruo** [comment]
我在测试时有三个疑问:第一，detection是为了做均值归一化吗？是否需要改动这里的参数https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/transforms.py#L81 。
第二，当我在测试的时候，我发现使用20张图片一次性测试时，会有两三张图片结果很离谱，但是当我使用在20张图片5张一组分别检测时，结果却都还不错，并没有很离谱的图片。我的理解检测时图片之间应该是独立的，但是实验表明似乎同一张图片的检测结果会被其他图片所影响。为什么会产生这种现象？
第三，在使用在5张一组进行测试时，同样的图片，不同的两次测试结果之间有时会有差别，请问，测试时关于6D位姿估计网络 ，其中有什么随机性吗

**Comment by pengsida** [comment]
1. detection用来把物体从图片中crop出来。为什么会联想到均值归一化？
2. 检测时图片是独立的，我们是一张一张检测的，没试过几张图片一起检测。
3. 会有随机性，但在这个仓库里我们把random seed固定了：https://github.com/zju3dv/clean-pvnet/blob/master/run.py#L67

**Comment by shanniruo** [comment]
我一开始理解有误，感谢指导。关于random seed，我也仿照你的做法在运行可视化时固定了。但是我还是有一点不太理解。在测试时加载的权重文件是固定的，为什么还需要生成随机数？

**Comment by pengsida** [comment]
ransac voting的过程是随机的。

**Comment by cgm6666** [comment]
> 作者你好，我已经使用自制数据集训练好了结果，但是我想用rgb图片做测试，我自己尝试了却没有成功，我应该如何做？

你好,请问你是怎么制作的数据集呢?我使用作者提供的ojbectdatasettools第六步生成的ply文件导入meshlab,另存为成文本的格式,但是在训练过程中有四个验证的参数(ap,proj2d,cmd5等)始终不变,请问你知道是什么原因吗?
