### ISSUE TITLE
Posefile's name(0.npy) of the custom dataset

### ISSUE THREAD

**Issue by takuya-ikeda-tri** [zju3dv/clean-pvnet#62]
About the below custom dataset tree in this readme, pose data  should be `pose0.npy` or `pose1234.npy`, not `0.npy` or `1234.npy`?
Also, could you teach me how to create `pose*.npy` using [ObjectDatasetTools](https://github.com/F2Wang/ObjectDatasetTools) because I cannot see the generation script for `pose*.npy` in the library, although I can see the `*.npy` in `transforms` directory using ObjectDatasetTools?

``` 
├── /path/to/dataset
│   ├── model.ply
│   ├── camera.txt
│   ├── diameter.txt  // the object diameter, whose unit is meter
│   ├── rgb/
│   │   ├── 0.jpg
│   │   ├── ...
│   │   ├── 1234.jpg
│   │   ├── ...
│   ├── mask/
│   │   ├── 0.png
│   │   ├── ...
│   │   ├── 1234.png
│   │   ├── ...
│   ├── pose/
│   │   ├── 0.npy
│   │   ├── ...
│   │   ├── 1234.npy
│   │   ├── ...
│   │   └──
```
Thanks in advance!!!

**Comment by pengsida** [comment]
1. Yes, pose data should be `pose*.npy`.
2. `pose*.npy` stores the 6d pose, aka [R; t].

**Comment by takuya-ikeda-tri** [comment]
Thank you for your information!

This `pose*.npy` is not same as the [R; t](`*.npy`) in transforms directory came from [ObjectDatasetTools](https://github.com/F2Wang/ObjectDatasetTools), right?
How do you usually make or convert this required `pose*.npy` from the ObjectDatasetTools' output??

**Comment by pengsida** [comment]
I am not sure, since I never use the ObjectDatasetTools, which is recommended by others.
If the `*.npy` from ObjectDatasetTools is [R; t], I think that `*.npy` is probably the same as `pose*.npy`.

**Comment by shanniruo** [comment]
you can modify the code in tool/handle_custom_dataset.py.and I did a training with timer.but the result is bad,maybe wo can Communication on  it.
