### ISSUE TITLE
EPnP solves for R and t

### ISSUE THREAD

**Issue by 545464598** [zju3dv/clean-pvnet#63]
Hello, may I ask that the solution of R and t mentioned in the paper adopts the method of EPnP initialization based on four key points? What part of the program of EPnP is reflected in the program file

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/blob/9463242d7084353c269e5e0e06da83c5610dab54/lib/csrc/uncertainty_pnp/un_pnp_utils.py#L29

**Comment by 545464598** [comment]
Hello, in this un_pnp_utils.py file is this R, t directly solved by calling the CV function and then solving the LM algorithm mentioned in the paper (5)? Does the un_pnp_utils.py file code have related articles to explain the procedure?
