### ISSUE TITLE
Program problem

### ISSUE THREAD

**Issue by 545464598** [zju3dv/clean-pvnet#64]
Hello, in this un_pnp_utils.py file is this R, t directly solved by calling the CV function and then solving the LM algorithm mentioned in the paper (5)? Does the un_pnp_utils.py file code have related articles to explain the procedure?Or can there be program comments?Thanks！

**Comment by pengsida** [comment]
Yes, the [R; t] is initialized by EPnP and then refined by the LM algorithm.
The procedure is "the [R; t] is initialized by EPnP and then refined by the LM algorithm".

**Comment by 545464598** [comment]
> 
> 
> Yes, the [R; t] is initialized by EPnP and then refined by the LM algorithm.
> The procedure is "the [R; t] is initialized by EPnP and then refined by the LM algorithm".

Is there any article explaining this part of the program?

**Comment by pengsida** [comment]
Our paper describes this procedure.

**Comment by 545464598** [comment]
> 
> 
> Our paper describes this procedure.

Oh, but there are some difficulties to understand this program. There are not many comments on the program.

**Comment by pengsida** [comment]
Sorry, I would not comment this program since there are only a few codes.

**Comment by 545464598** [comment]
> 
> 
> Sorry, I would not comment this program since there are only a few codes.

Oh, I'll look into it, thanks!
