### ISSUE TITLE
EPnP Problem

### ISSUE THREAD

**Issue by 545464598** [zju3dv/clean-pvnet#65]
Hello, in un_pnp_utils.py,
R_exp, t = cv2.solvepnp (np.expand_dims(points_3d[idxs,:], 0),
                                     np. expand_dims (points_2d [idxs:], 0)，
                                     camera_matrix, dist_coeffs, None, None, False,
                                     flags = cv2. SOLVEPNP_P3P)
Is this the solution for P3P? Is it the solution for EPnP? Why is it necessary to directly return the result of R|t when pn=4 in the first step? In the rest of the cases, the unnp.cpp program is called with the relevant pointer operation to return the solved R|t. In the case of the EPnP algorithm, it's not just case 1,2,3,4, pn>=4, is that 8 key points? In the following program, did you find the LM algorithm program mentioned last time?

**Comment by pengsida** [comment]
1. We use P3P to compute the pose.
2. PnP algorithm requires at least 4 points.
3. LM algorithm: https://github.com/zju3dv/clean-pvnet/blob/master/lib/csrc/uncertainty_pnp/un_pnp_utils.py#L53

**Comment by 545464598** [comment]
Oh oh, thank you, recently in the replication of your program, forgot to reply, I see the paper is written to use EPnP ah, directly call P3P can be used?

**Comment by pengsida** [comment]
Yes.

**Comment by 545464598** [comment]
Oh,thanks!
