### ISSUE TITLE
Custom synthetic dataset

### ISSUE THREAD

**Issue by fransonf** [zju3dv/clean-pvnet#66]
Hello, hope you're doing well. I have been using your renderings on T-LESS (object 15) for some experiments and now want to do the same experiments on a custom object (still only renderings). I am a bit confused what exactly I need in order to do this. Is there some neat automated way of generating a custom synthetic dataset If I have the .ply file for the object?

Thanks in advance.

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet-rendering

**Comment by fransonf** [comment]
At first glance this looks, to me, like it is made for creating synthetic data on LINEMOD objects. Is it tedious doing it for my own object? 

Thanks for the quick answer by the way!

**Comment by pengsida** [comment]
If you are not familiar with blender, it is probably cumbersome.

**Comment by fransonf** [comment]
Thanks for the info, stay safe!
