### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by 545464598** [zju3dv/clean-pvnet#67]
Hello, in the clean - pvnet Linemod data set point in the program is stored in the Linemod/cat/farthest file? I see the format of the homemade dataset is saved in fps.txt. But it's not in the Linemod data set folder. What are the key files in the Linemod data set? Is there no conflict between the key reads of the downloaded data set and the key reads of the homemade data set?

**Comment by 545464598** [comment]
Does the Linemod data set's key point sampling have to be regenerated by a program in github-pvnet? Isn't there a program in github-clean-pvnet?

**Comment by pengsida** [comment]
If you are Chinese, please comment in Chinese, because your English is difficult for me to understand.

**Comment by 545464598** [comment]
你好，请问在clean-pvnet程序中Linemod数据集的关键点是保存在Linemod/cat/farthest 文件中吗。我看自制数据集的格式是保存在fps.txt。但Linemod数据集文件夹中并没有这个文件呀。Linemod数据集中的关键点是通过什么文件引入进来的呀？这些下载好的数据集的关键点读取和自制的数据集关键点读取没有冲突吗？这个Linemod数据集的关键点的采样还要通过github-pvnet里的程序重新生成吗？github-clean-pvnet中没有相关的程序吗？

**Comment by pengsida** [comment]
1. 下载的数据集和自制的数据集不会冲突，因为是不同代码处理的。
2. 关键点采样：https://github.com/zju3dv/clean-pvnet/blob/master/tools/handle_custom_dataset.py#L19

**Comment by 545464598** [comment]
如果我想重新生成linemod数据集的关键点，需要用那个pvnet那个老程序吗？还是在这个clean-pvnet中直接就可以实现呀

**Comment by 545464598** [comment]
程序中是采用ann文件来调用关键点的吗？

**Comment by pengsida** [comment]
1. clean-pvnet里的实现可以用，不建议重新生成linemod数据集的关键点。
2. 我们把数据转成了coco格式再读取的。

**Comment by 545464598** [comment]
那如果想要再此模型上修改寻找关键点的方法，是不是需要去重新生成linemod数据集呀

**Comment by pengsida** [comment]
1. 什么叫修改寻找关键点的方法
2. 重新生成linemod还是重新生成linemod的数据集？

**Comment by 545464598** [comment]
就是想在pvnet原模型的基础上对寻找关键点的方法进行修改，不使用这个FPS算法，那样的话在Linemod数据集中找到的关键点就需要用新的算法重新修改了吧，不能直接用CoCO文件导入了吧，就比如把FPS换回原来的八个顶点的方法

**Comment by 545464598** [comment]
修改之后就不能继续使用通过你们给的链接下载好的数据集了吧，需要对关键点重新生成吧

**Comment by pengsida** [comment]
生成好fps.txt文件以后，可以用这个函数将数据转成coco格式：https://github.com/zju3dv/clean-pvnet/blob/master/tools/handle_custom_dataset.py#L86

**Comment by 545464598** [comment]
哦哦，感谢你的答复，感觉这样做的话任务量有些大，每个种类的图片需要修改配置单独运行程序吧

**Comment by pengsida** [comment]
嗯嗯
