### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by redredraccoon** [zju3dv/clean-pvnet#69]
After executing testing & visualization on Linemod successfully, I try to train on Linemod. 
The first step instruction: `python run.py --type linemod cls_type cat` can succeed, but the second step: `python train_net.py --cfg_file configs/linemod.yaml model mycat cls_type cat` failded and error message: 
`(pvnet) raccoon@nmsocadmin-734:~/pvnet$ python train_net.py --cfg_file configs/                                                linemod.yaml model mycat cls_type cat`
`/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/paralle                                                l/data_parallel.py:26: UserWarning:`
`There is an imbalance between your GPUs. You may want to exclude GPU 1 which                                           has less than 75% of the memory or cores of GPU 2. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEV                                                ICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos])                                                )`
`loading annotations into memory...`
`Done (t=0.15s)`
`creating index...`
`index created!`
`loading annotations into memory...`
`Done (t=2.19s)`
`creating index...`
`index created!`
`loading annotations into memory...`
`Done (t=0.07s)`
`creating index...`
`index created!`
`Traceback (most recent call last):`
  `File "train_net.py", line 57, in <module>`
  `  main()`
  `File "train_net.py", line 53, in main`
  `  train(cfg, network)`
  `File "train_net.py", line 28, in train`
  `  trainer.train(epoch, train_loader, optimizer, recorder)`
  `File "/home/raccoon/pvnet/lib/train/trainers/trainer.py", line 38, in train`
   ` output, loss, loss_stats, image_stats = self.network(batch)`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__ `
   ` result = self.forward(*input, **kwargs)`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward`
   ` outputs = self.parallel_apply(replicas, inputs, kwargs)`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply`
  `  return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply`
  `  raise output`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker`
  `  output = module(*input, **kwargs)`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__`
  `  result = self.forward(*input, **kwargs)`
  `File "lib/train/trainers/pvnet.py", line 16, in forward`
  `  output = self.net(batch['inp'])`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__`
    `result = self.forward(*input, **kwargs)`
  `File "lib/networks/pvnet/resnet18.py", line 79, in forward`
  `  x2s, x4s, x8s, x16s, x32s, xfc = self.resnet18_8s(x)`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__`
   ` result = self.forward(*input, **kwargs)`
  `File "lib/networks/pvnet/resnet.py", line 206, in forward`
  `  x4s = self.layer1(x)`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__`
   ` result = self.forward(*input, **kwargs)`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward`
  `  input = module(input)`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__`
  `  result = self.forward(*input, **kwargs)`
  `File "lib/networks/pvnet/resnet.py", line 60, in forward`
  `  out = self.conv2(out)`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__`
  `  result = self.forward(*input, **kwargs)`
  `File "/home/raccoon/anaconda3/envs/pvnet/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 338, in forward`
   ` self.padding, self.dilation, self.groups)`
`RuntimeError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 7.93 GiB total capacity; 849.84 MiB already allocated; 40.56 MiB free; 42.16 MiB cached)`

**Comment by pengsida** [comment]
CUDA out of memory.
Reduce the batch size.

**Comment by redredraccoon** [comment]
Sorry for interrupting again.
After reducing the batch size, it still show error message about CUDA out of memory.
I want to confirm that the adjustment batch size is in this place? As shown below
![image](https://user-images.githubusercontent.com/38128523/80356823-a0198180-88ac-11ea-88b7-dfe84d69efbc.png)
