### ISSUE TITLE
Uncertainty-pnp

### ISSUE THREAD

**Issue by 545464598** [zju3dv/clean-pvnet#76]
你好，我在编译pnp的时候遇到了这个问题，想问一下这是哪个环境出现了问题呀？
(pvnet) yanhao@amax:~/path/to/clean-pvnet/lib/csrc/uncertainty_pnp$ python setup.py build_ext --inplace
generating ./_ext.c
(already up-to-date)
the current directory is '/home/yanhao/path/to/clean-pvnet/lib/csrc/uncertainty_pnp'
running build_ext
building '_ext' extension
gcc -pthread -B /home/yanhao/anaconda3/envs/pvnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yanhao/anaconda3/envs/pvnet/include/python3.7m -c _ext.c -o ./_ext.o
gcc -pthread -shared -B /home/yanhao/anaconda3/envs/pvnet/compiler_compat -L/home/yanhao/anaconda3/envs/pvnet/lib -Wl,-rpath=/home/yanhao/anaconda3/envs/pvnet/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_ext.o src/uncertainty_pnp.cpp.o ./lib/libceres.so ./lib/libglog.so -lstdc++ -o ./_ext.cpython-37m-x86_64-linux-gnu.so
/home/yanhao/anaconda3/envs/pvnet/compiler_compat/ld:./lib/libceres.so: file format not recognized; treating as linker script
/home/yanhao/anaconda3/envs/pvnet/compiler_compat/ld:./lib/libceres.so:0: syntax error
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/distutils/unixccompiler.py", line 205, in link
    self.spawn(linker + ld_args)
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/distutils/command/build_ext.py", line 559, in build_extension
    target_lang=language)
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/distutils/unixccompiler.py", line 207, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    ffibuilder.compile(verbose=True)
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/yanhao/anaconda3/envs/pvnet/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

**Comment by pengsida** [comment]
```
/home/yanhao/anaconda3/envs/pvnet/compiler_compat/ld:./lib/libceres.so: file format not recognized; treating as linker script
/home/yanhao/anaconda3/envs/pvnet/compiler_compat/ld:./lib/libceres.so:0: syntax error
collect2: error: ld returned 1 exit status
```

你看看这两个文件`libceres.so`，`./lib/libceres.so:0`是不是软链接。

**Comment by 545464598** [comment]
![QQ图片20200426154711](https://user-images.githubusercontent.com/58974326/80301193-42fecc80-87d5-11ea-8f9f-5cd8b690c622.png)
是软连接然后点不进去

**Comment by 545464598** [comment]
只能到ld那个目录

**Comment by 545464598** [comment]
/home/yanhao/anaconda3/envs/pvnet/compiler_compat/ld:.

**Comment by 545464598** [comment]
你好，这个是/home/yanhao/anaconda3/envs/pvnet/compiler_compat/ld:.的目录，github上不能发图片


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pengsida"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月26日(星期天) 下午3:44
收件人:&nbsp;"zju3dv/clean-pvnet"<clean-pvnet@noreply.github.com&gt;;
抄送:&nbsp;"闫号"<545464598@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/clean-pvnet] Uncertainty-pnp (#76)





 /home/yanhao/anaconda3/envs/pvnet/compiler_compat/ld:./lib/libceres.so: file format not recognized; treating as linker script /home/yanhao/anaconda3/envs/pvnet/compiler_compat/ld:./lib/libceres.so:0: syntax error collect2: error: ld returned 1 exit status  
你看看这两个文件libceres.so，./lib/libceres.so:0是不是软链接。

**Comment by pengsida** [comment]
`libceres.so`在`clean-pvnet/lib/csrc/uncertainty_pnp/lib/`目录下

**Comment by 545464598** [comment]
libceres.so这个文件有

**Comment by 545464598** [comment]
我需要怎么操作呀？

**Comment by 545464598** [comment]
![QQ图片20200426090102](https://user-images.githubusercontent.com/58974326/80302931-937b2780-87df-11ea-8ea2-4ba9741882aa.png)

**Comment by 545464598** [comment]
这个问题有被解决，谢谢

**Comment by zhuyazhi** [comment]
请问最后这个问题怎么解决的呢？我也遇到相同的问题

**Comment by WW-0** [comment]
同问这个问题怎么解决的

**Comment by 545464598** [comment]
> 同问这个问题怎么解决的

有些忘记啦，好像
是cd ../uncertainty_pnp
sudo apt-get install libgoogle-glog-dev
sudo apt-get install libsuitesparse-dev
sudo apt-get install libatlas-base-dev
python setup.py build_ext --inplace
这个需要安装正确，重新下载文件

**Comment by 545464598** [comment]
> 请问最后这个问题怎么解决的呢？我也遇到相同的问题

同下，试一下吧

**Comment by WW-0** [comment]
> > 同问这个问题怎么解决的
> 
> 有些忘记啦，好像
> 是cd ../uncertainty_pnp
> sudo apt-get install libgoogle-glog-dev
> sudo apt-get install libsuitesparse-dev
> sudo apt-get install libatlas-base-dev
> python setup.py build_ext --inplace
> 这个需要安装正确，重新下载文件

刚移除又重新安装了一遍，报的错误还是一样😭

**Comment by WW-0** [comment]
软连接出错，进入clean-pvnet-master/lib/csrc/uncertainty_pnp/lib/ 删除libceres.so libceres.so.2
再执行以下命令重新创建软连接：
ln -s libceres.so.2.0.0 libceres.so.2
ln -s libceres.so.2 libceres.so
再执行 python setup.py build_ext --inplace

**Comment by 545464598** [comment]
> 软连接出错，进入clean-pvnet-master/lib/csrc/uncertainty_pnp/lib/ 删除libceres.so libceres.so.2
> 再执行以下命令重新创建软连接：
> ln -s libceres.so.2.0.0 libceres.so.2
> ln -s libceres.so.2 libceres.so
> 再执行 python setup.py build_ext --inplace

修复了是嘛

**Comment by WW-0** [comment]
> > 软连接出错，进入clean-pvnet-master/lib/csrc/uncertainty_pnp/lib/ 删除libceres.so libceres.so.2
> > 再执行以下命令重新创建软连接：
> > ln -s libceres.so.2.0.0 libceres.so.2
> > ln -s libceres.so.2 libceres.so
> > 再执行 python setup.py build_ext --inplace
> 
> 修复了是嘛，感觉当时没弄这些操作呀


解决了，不知道咋回事反正我重新apt-get了你说的几个包发现还是一样的问题，看到作者问你那两个文件是不是软链接我就试着重新搞了下软链接，就可以运行了
