### ISSUE TITLE
Adjusted batch size

### ISSUE THREAD

**Issue by redredraccoon** [zju3dv/clean-pvnet#78]
#69 
Sorry for interrupting again.
After reducing the batch size, it still show error message about CUDA out of memory.
I want to confirm that the adjustment batch size is in this place? As shown below
![image](https://user-images.githubusercontent.com/38128523/80358083-75c8c380-88ae-11ea-9eeb-7304c2286e0c.png)

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/blob/master/configs/linemod.yaml#L16

**Comment by redredraccoon** [comment]
Thanks ! It works.
