### ISSUE TITLE
RuntimeError: solve_cuda: For batch 0: U(1,1) is zero, singular U

### ISSUE THREAD

**Issue by changewOw** [zju3dv/clean-pvnet#8]
我用pvnet在我自己的小数据集上进行训练，然后进行预测。在ransac_voting阶段，经常碰到`RuntimeError: solve_cuda: For batch 0: U(1,1) is zero, singular U` 这个错误
错误发生在这里
`def b_inv(b_mat):
    '''
    code from
    https://stackoverflow.com/questions/46595157/how-to-apply-the-torch-inverse-function-of-pytorch-to-every-sample-in-the-batc
    :param b_mat:
    :return:
    '''
    eye = b_mat.new_ones(b_mat.size(-1)).diag().expand_as(b_mat)
    b_inv, _ = torch.solve(eye, b_mat)
    return b_inv
`
请问有什么解决办法吗

torch 1.3.1
torchvision 0.4.2
windows10系统

**Comment by pengsida** [comment]
我更新代码了

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/commit/e2c8c88558f2532bd1861d6a0d6220d558aaf9d2

**Comment by changewOw** [comment]
哈哈哈！。好快！非常感谢大佬
