### ISSUE TITLE
关于train.json，test.json, occ.json和linemod_to_coco.py的请教

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/clean-pvnet#80]
您好我想请问一下，如果要训练每个物体的pvnet模型，是不是需要先用linemod_to_coco.py这个代码来生成每个物体的train.json，test.json, occ.json这三个标注文件呀？
因为我目前只看到cat种类下面有这三个.json文件。
![image](https://user-images.githubusercontent.com/48109799/80852778-d0bb3b80-8c5d-11ea-99f3-377f67609a7d.png)

如果我要训练别的物体，是不是应该
1.先用pvnet-rendering合成其他每个物体的20000张合成图片（因为目前看到数据集中只提供了cat的合成图片）；
2.用linemod_to_coco.py生成train.json，test.json, occ.json这三个文件，才可以开始训练呢？
3.linemod_to_coco.py是需要我们在得到合成图片之后，线下自己运行吗？
感谢赐教

**Comment by pengsida** [comment]
如果是想训练Linemod的物体，直接用已经处理好的数据集就可以。
如果要训练别的物体，可以参考这里的步骤：https://github.com/zju3dv/clean-pvnet#training-on-the-custom-object

**Comment by zhuyazhi** [comment]
感谢您的回复~
我是想训练Linemod的物体，但是我目前还疑问的是:
1. 项目提供的linemod数据集的renders文件夹下面只包含cat一个种类的合成图片，其他物体的合成图片都还没有，训练的时候不是需要真实图片和20000张合成图片一起训练吗？所以我在想是不是需要得到合成图片之后才能训练。
2. train.json，test.json, occ.json这三个标注文件也不是所有物体的文件夹下面都有，不需要得到合成图片之后，自己运行linemod_to_coco.py来生成这三个.json吗~
![image](https://user-images.githubusercontent.com/48109799/80855346-06b6ea80-8c73-11ea-8b67-37bfb051469a.png)
希望得到您的指教！

**Comment by pengsida** [comment]
1. 需要自己合成图片才能训练。
2. 需要运行linemod_to_coco.py来生成三个json文件。

**Comment by zhuyazhi** [comment]
非常感谢！我知道了~linemod_to_coco.py自己线下用Pycharm运行就可以吗，还是说也得在ubuntu环境下用命令行运行呢？
另外，我看到fuse文件夹下的10000张合成图片里面包含多种物体及对应的位姿标注，是不是linemod数据集中13种物体都共用fuse的这10000张合成图片来训练，然后还需要分别render每种物体的10000张合成图片。如果是这样的话，fuse文件夹下面只需10000张就行了，我另外就不需要fuse合成了，只需要再分别render每种物体的10000张合成图片就可以了，请问是这样吗？

**Comment by pengsida** [comment]
1. 建议用`python run.py --type linemod cls_type <class_type>`. <class_type>是你想训练的物体。
2. 共用fuse图片，分别render每个物体10000张合成图片。

**Comment by zhuyazhi** [comment]
好的！感谢您的回复~
也就是用pvnet-rendering代码render每个物体10000张合成图片后（放到对应的位置），然后用python run.py --type linemod cls_type <class_type>这句命令行来生成对应物体的3个json文件后，再开始训练每个物体，这个顺序对吗~

**Comment by pengsida** [comment]
是的。
