### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/clean-pvnet#85]
您好~训练时1 epoch 大概用时 1 hour，请问您有什么建议可以加快训练速度吗
我的环境是pytorch1.1+cuda9，按照requirement.txt配置的

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/issues/4

**Comment by zhuyazhi** [comment]
thanks~将pip3 install torch==1.1.0 -f https://download.pytorch.org/whl/cu90/stable
替换成pip3 install torch==0.4.1 -f https://download.pytorch.org/whl/cu90/stable这样吗

**Comment by pengsida** [comment]
应该是

**Comment by zhuyazhi** [comment]
thank you~
