### ISSUE TITLE
2D projection指标

### ISSUE THREAD

**Issue by 545464598** [zju3dv/clean-pvnet#86]
你好，请问这个指标不是预测值和真实值之间距离吗？为什么训练出来的图像和指标都是趋于1的呢？

**Comment by pengsida** [comment]
是准确度。

**Comment by 545464598** [comment]
在程序中没看到这部分的计算呢？

**Comment by pengsida** [comment]
https://github.com/zju3dv/clean-pvnet/blob/master/lib/evaluators/linemod/pvnet.py#L59
