### ISSUE TITLE
torch_shm_manager: error while loading shared libraries: libcudart.so.10.0:

### ISSUE THREAD

**Issue by hhaAndroid** [zju3dv/clean-pvnet#87]
There is only cuda10.1 in my computer. I compiled successfully with 10.1, but I get an error when running，I don't know why

**Comment by pengsida** [comment]
What error.

**Comment by hhaAndroid** [comment]
May be my problem

**Comment by hhaAndroid** [comment]
Should I specify the pytorch version，I found that it can be run on pytorch1.1.0, but not on pytorch1.2.0

**Comment by pengsida** [comment]
https://github.com/rusty1s/pytorch_geometric/issues/114

**Comment by hhaAndroid** [comment]
I created a new environment and the result is correct ,pytorch1.1.0 cuda 10.1
