### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by hhaAndroid** [zju3dv/clean-pvnet#88]
My configuration is successful, and it runs completely according to the process. The result of the visualization is completely wrong. What is the possible reason?

2d projections metric: 0.0
ADD metric: 0.0
5 cm 5 degree metric: 0.0
mask ap70: 0.9960079840319361

![image](https://user-images.githubusercontent.com/17425982/81940133-d6375f00-9629-11ea-81e8-7f83d7e09b79.png)

**Comment by hhaAndroid** [comment]
Pre-training weights loaded ，

print info:

Load model: data/model/pvnet/cat/199.pth
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
Backend Qt5Agg is interactive backend. Turning interactive mode on.
loading annotations into memory...
Done (t=0.08s)
creating index...

**Comment by pengsida** [comment]
What is your command?
And Did you download the dataset from this repository?

**Comment by hhaAndroid** [comment]
I can guarantee to use it exactly as you ordered,Today, I created a new conda environment, exactly according to your configuration, it's ok, the result is correct
Since the mask ap is completely correct, the problem must be handled in cuda post code, but I compiled successfully, it is not clear why

**Comment by shuluoshu** [comment]
> I can guarantee to use it exactly as you ordered,Today, I created a new conda environment, exactly according to your configuration, it's ok, the result is correct
> Since the mask ap is completely correct, the problem must be handled in cuda post code, but I compiled successfully, it is not clear why

Same problem, did you solve it ? @hhaAndroid @pengsida

**Comment by pengsida** [comment]
The problem has been solved as he said.

**Comment by shuluoshu** [comment]
> > I can guarantee to use it exactly as you ordered,Today, I created a new conda environment, exactly according to your configuration, it's ok, the result is correct
> > Since the mask ap is completely correct, the problem must be handled in cuda post code, but I compiled successfully, it is not clear why
> 
> Same problem, did you solve it ? @hhaAndroid @pengsida

Solved by replace the 'ransac_voting'  in clean-pvnet with original pvnet.

**Comment by cgm6666** [comment]
> > > 我可以保证完全按照您的命令使用它，今天，我完全根据您的配置创建了一个新的conda环境，没关系，结果是正确的
> > > 由于mask ap是完全正确的，因此必须在cuda邮政编码中处理该问题。 ，但我编译成功，目前尚不清楚为什么
> > 
> > 
> > 同样的问题，您解决了吗？@hhaAndroid  @pengsida
> 
> 解决方法是将clean-pvnet中的“ ransac_voting”替换为原始pvnet。

Hi, how did you solve this question, I found my mask ap alway 1

**Comment by tendernesswty** [comment]
> I created a new conda environment, exactly according to your configuration, it's ok, the result is correct
> Since the mask ap is completely correct, the problem must be handled in cuda post cod
Hi，I met the same question.But at the beginning, my add metri, 2d projections metric and 5 cm 5 degree metric were not zero. And in the approximately 15 epoches, these values became zero. How did you solve this question?

**Comment by tendernesswty** [comment]
Hi，I met the same question.But at the beginning, my add metri, 2d projections metric and 5 cm 5 degree metric were not zero. And in the approximately 15 epoches, these values became zero. How did you solve this question?

**Comment by QRayMoor** [comment]
@tendernesswty 请问你是如何解决的？我跑自建数据集也遇到这种情况

**Comment by RoyCopter** [comment]
> > > I can guarantee to use it exactly as you ordered,Today, I created a new conda environment, exactly according to your configuration, it's ok, the result is correct
> > > Since the mask ap is completely correct, the problem must be handled in cuda post code, but I compiled successfully, it is not clear why
> > 
> > 
> > Same problem, did you solve it ? @hhaAndroid @pengsida
> 
> Solved by replace the 'ransac_voting' in clean-pvnet with original pvnet.

hey, what exactly you replaced? all the folder of the ransac_voting or just the python file?

because when I replaced all the ransac_voting to ransac_voting_gpu_layer it didn't solve that problem.

any idea how to fix it?

**Comment by rhalder2023** [comment]
@hhaAndroid how did you solve that issue, im getting the same bad results. any clue would help

**Comment by assia855** [comment]
Hi I'm struggling with  the same error. Any solution to overcome this error please?

**Comment by monajalal** [comment]
I still have the same results -- after 5 epoch of training for my own custom data:

```
['vote_loss: 0.1271', 'seg_loss: 0.0286', 'loss: 0.1558']
2d projections metric: 0.0
ADD metric: 0.0
5 cm 5 degree metric: 0.0
mask ap70: 0.968
```

I don't have this problem with the custom dataset that the author has shared.

**Comment by assia855** [comment]
Hi @monajalal what worked for me was to increase the batch value and the metrics values started increasing

**Comment by monajalal** [comment]
> Hi @monajalal what worked for me was to increase the batch value and the metrics values started increasing

@assia855  could you please share the line of code you have changed?

Also, how large (number of data points/rgb images) is your custom dataset?
