### ISSUE TITLE
2D-3D correspondences

### ISSUE THREAD

**Issue by fransonf** [zju3dv/clean-pvnet#89]
Hello! I am having a hard time understanding how you get 2D-3D correspondences to solve PnP from you paper. Roughly speaking, I've understood that:

You get 2D keypoint hypotheses from PVNet where each pixel has a unit vector pointing towards the keypoints. The keypoints are based on the 3D model, placed on the object surface using the FPS algorithm. 

But how do you actually pair the 2D keypoints with the 3D keypoints?

Thanks in advance!

**Comment by pengsida** [comment]
The ground truth 2d keypoints are the projection of 3d keypoints.

**Comment by fransonf** [comment]
That makes sense, thanks!
