### ISSUE TITLE
lib.ransac_voting error

### ISSUE THREAD

**Issue by RollingInTheBed** [zju3dv/clean-pvnet#9]
hello,

I followed the steps and now trying to test the model with the command:
python run.py --type evaluate --cfg_file configs/linemod.yaml model cat

But I got an error as :
ModuleNotFoundError: No module named 'lib.csrc.ransac_voting.ransac_voting'

As I have already setup the 'ransac_voting' with no error. Can I get any advice about why is this happening?

**Comment by pengsida** [comment]
Are you sure that the ransac_voting is compiled correctly?
What is your python version?
And list the content under 'lib/csrc/ransac_voting'.

**Comment by RollingInTheBed** [comment]
Thanks for answering so fast, it is solved now.

**Comment by QuanNguyen94** [comment]
hi @pengsida @RollingInTheBed , do you have any suggest to combine ransac lib on Window
