### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by mandywoo** [zju3dv/clean-pvnet#90]
When creating the custom dataset, is it necessary to have the aruco markers? I'm training it to be used to detect objects in real time where there won't be any markers. I'm also creating the dataset with blender, keeping the camera at the default location, is pose different for blender? I tested the pose from the given custom dataset and it's different.

**Comment by pengsida** [comment]
You could equip PVNet with a detector, which can crop the object from the background.
I never use the Custom dataset.
