### ISSUE TITLE
resume training

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/clean-pvnet#93]
您好，由于训练时间的限制，一次性训练不了200 epoch，中断本次训练之后，下次继续训练。
我之前中断过一次，后来继续训练显示会在之前的基础上，比如34.pth重新调用模型进行训练。
我看了[#34](https://github.com/zju3dv/clean-pvnet/issues/34)的回答，下次继续训练必须需要加上 resume True吗？

**Comment by pengsida** [comment]
默认是resume True。
