### ISSUE TITLE
 about ransac_voting_gpu.py

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/clean-pvnet#95]
![image](https://user-images.githubusercontent.com/48109799/83893421-7d6b6a00-a782-11ea-9888-c276cc7d06ff.png)
hello,I can't understand the use of these code in ransac_voting_gpu.py，why "compute mean intersection again"  after we get the hypothsis with highest score? I will be very appreciated if you can give me some directions.thanks~

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet/issues/54

**Comment by zhuyazhi** [comment]
thanks for your reply, I understand the code do generate hypotheses and let pixels vote for hypotheses.
Find out the hypothesis with the largest amount of votes and mark these pixels voting for this hypothesis as inliers.
if we don't use un pnp, do we need to "compute mean intersection again"?

**Comment by zhuyazhi** [comment]
thans for your reply, i understand the code does
(1).Generate hypotheses and let pixels vote for hypothesis.
(2).Find out the hypothesis with the largest amount of votes and mark these pixels voting for this hypothesis as inliers.
 if we don't use un pnp, we can use the 9 hypothesis with highest voting score as the final localized keypoints.
I just can't understand is there any link between the code "compute mean intersection again"  and (1)&(2)?

**Comment by zhuyazhi** [comment]
thanks for your reply, i understand the code does
(1).Generate hypothesis and let pixels vote for hypothesis.
(2).Find out the hypothesis with the largest amount of votes and mark these pixels voting for this hypothesis as inliers.
if we don't use un pnp, we can use the 9 hypothesis with highest voting score as the final localized keypoints.
I just can't understand is there any link between the code "compute mean intersection again" and (1)&(2)?

**Comment by pengsida** [comment]
`compute mean intersection again`: use the selected pixels to vote the final keypoints.

**Comment by zhuyazhi** [comment]
I understand, that means we don't use the hypothesis with highest voting score as the final localized
keypoints directlly,Find out the hypothesis with the largest amount of votes and mark these pixels voting for this hypothesis as inliers., and use the unit vector 
from inliers t

**Comment by zhuyazhi** [comment]
thanks very much.
at privious time，I think when we don't use un pnp,we just use the ｋ　hypotheses with highest voting score as the final localized keypoints directly．
I understand,  you mean we don't use the hypothesis with highest voting score 
as the final localized keypoints directly,after finding out the hypothesis with the largest amount of 
votes and mark these pixels voting for this hypothesis as inliers, and use the unit vectors of inliers to compute the mean initersection, use the mean intersection generated by inliers as the final localized keypoint. 
Is that right?

**Comment by zhuyazhi** [comment]
thanks very much.
at previous time，I think when we don't use un pnp,we just use the ｋ　hypotheses with highest voting score as the final localized keypoints directly．
I understand, you mean we don't use the hypothesis with highest voting score
as the final localized keypoints directly,after finding out the hypothesis with the largest amount of
votes and mark these pixels voting for this hypothesis as inliers, and use the unit vectors of inliers to compute the mean initersection, use the mean intersection generated by inliers as the final localized keypoint.
Is that right?

**Comment by pengsida** [comment]
Yes.
