### ISSUE TITLE
Change in Camera Intrinsic Values for Fuse Images

### ISSUE THREAD

**Issue by Anshul-Gupta24** [zju3dv/clean-pvnet#96]
Hi, thanks for the great code. I had a doubt regarding the camera intrinsic matrix. In lib/datasets/linemod/linemod_to_coco.py I noticed that the camera intrinsic values are being changed in the 'record_fuse_ann' function. I have also confirmed this by printing out the values for a batch. Can you explain the reason for this? Also, is it possible to generate our own fuse data such that camera intrinsic matrix values are not changed? Thanks!

**Comment by pengsida** [comment]
We generate the fused data by randomly pasting the objects into the image.
Changing either camera intrinsic matrix or object pose achieves the visual effect.

**Comment by Anshul-Gupta24** [comment]
I see, thanks for the clarification. Looking at the code, I see the change is happening in cx and cy values of the intrinsic matrix. So the original intrinsic matrix can be recovered by translating the image? Also, is there any code to generate our own fuse images? Thanks.

**Comment by pengsida** [comment]
The original intrinsic matrix can be preserved by revising the object pose matrix.
The code to generate the fuse data: https://github.com/zju3dv/pvnet-rendering

**Comment by Anshul-Gupta24** [comment]
Thanks!
