### ISSUE TITLE
data parallel with multi-gpu

### ISSUE THREAD

**Issue by shuluoshu** [zju3dv/clean-pvnet#99]
Hi @pengsida @JiamingSuen 
if I use only one GPU, it's OK. 
But if I use multi-gpu : 
```
cfg.train.num_workers： 6
gpu_ids: (0, 1, 2)
train: batch_size: 12
```
It will stuck in `data.scatter `(see below) during forward, could you please help me? 
`inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)`  within "torch/nn/parallel/data_parallel.py". 
Thank you!

**Comment by pengsida** [comment]
What are your pytorch version and cuda version?

**Comment by shuluoshu** [comment]
> What are your pytorch version and cuda version?

pytorch is 1.0.0, cuda is 9.0

**Comment by pengsida** [comment]
You could try pytorch==0.4.1 compiled from cuda 9.0.
`conda install pytorch=0.4.1 cuda90 -c pytorch`.

**Comment by shuluoshu** [comment]
> You could try pytorch==0.4.1 compiled from cuda 9.0.
> `conda install pytorch=0.4.1 cuda90 -c pytorch`.

If I use pytorch=1.0.0 running pvnet, it works well, is there any diff between clean-pvnet and pvnet in data parallel?

**Comment by pengsida** [comment]
No.

**Comment by shuluoshu** [comment]
> You could try pytorch==0.4.1 compiled from cuda 9.0.
> `conda install pytorch=0.4.1 cuda90 -c pytorch`.

I tried, still the same question for clean-pvnet. It will stuck during forward. Any suggestions?

**Comment by pengsida** [comment]
I do not know.
I never encontoured such problem.
